### ISSUE TITLE
Unofficial.py does not recognize the Log in button when logging in

### ISSUE THREAD

**Issue by ToviHe** [acheong08/ChatGPT#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When using the Unofficial.py version this afternoon, after successfully opening the Chrome browser and accessing the openai URL, there was no response on the login page, and the Log in button was not automatically recognized before being pressed and clicked, causing WebDriverWait to time out

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

1.run Unofficial.py
2.automatically open chrome
3.Wait for the Log in button to appear and click (the current problem is that the button has not been recognized until the timeout)

### Version where the problem happens

The latest version, since Unofficial.py has not been updated

### What Python version are you running this with?

3.9.6

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Traceback (most recent call last):
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/src/revChatGPT/Unofficial.py", line 859, in <module>
    main()
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/src/revChatGPT/Unofficial.py", line 855, in main
    chatGPT_main(configure())
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/src/revChatGPT/Unofficial.py", line 787, in chatGPT_main
    chatbot = Chatbot(config)
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/src/revChatGPT/Unofficial.py", line 72, in __init__
    self.__email_login()
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/src/revChatGPT/Unofficial.py", line 505, in __email_login
    WebDriverWait(driver, 120).until(
  File "/Users/tovi/Projects/python/ChatGPT-2.2.7/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   undetected_chromedriver             0x00000001010ea138 undetected_chromedriver + 4923704
1   undetected_chromedriver             0x00000001010629d3 undetected_chromedriver + 4368851
2   undetected_chromedriver             0x0000000100cab787 undetected_chromedriver + 472967
3   undetected_chromedriver             0x0000000100cefba3 undetected_chromedriver + 752547
4   undetected_chromedriver             0x0000000100cefdf1 undetected_chromedriver + 753137
5   undetected_chromedriver             0x0000000100d36734 undetected_chromedriver + 1042228
6   undetected_chromedriver             0x0000000100d18fdd undetected_chromedriver + 921565
7   undetected_chromedriver             0x0000000100d33c0f undetected_chromedriver + 1031183
8   undetected_chromedriver             0x0000000100d18d23 undetected_chromedriver + 920867
9   undetected_chromedriver             0x0000000100cdfa4b undetected_chromedriver + 686667
10  undetected_chromedriver             0x0000000100ce1044 undetected_chromedriver + 692292
11  undetected_chromedriver             0x00000001010b58fe undetected_chromedriver + 4708606
12  undetected_chromedriver             0x00000001010bae22 undetected_chromedriver + 4730402
13  undetected_chromedriver             0x00000001010c36bf undetected_chromedriver + 4765375
14  undetected_chromedriver             0x00000001010bbe80 undetected_chromedriver + 4734592
15  undetected_chromedriver             0x000000010108c975 undetected_chromedriver + 4540789
16  undetected_chromedriver             0x00000001010dde78 undetected_chromedriver + 4873848
17  undetected_chromedriver             0x00000001010ddff5 undetected_chromedriver + 4874229
18  undetected_chromedriver             0x00000001010f26de undetected_chromedriver + 4957918
19  libsystem_pthread.dylib             0x00007ff80846b259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff808466c7b thread_start + 15
```

### Additional information

Finally I solved this problem by updating the XPATH expression
$x("//button[contains(text(), 'Log in')]")  -》  $x("//button[contains(., 'Log in')]")

**Comment by acheong08** [comment]
Not supported. Make a pull request if you wish
