### ISSUE TITLE
[Bug]: Got error "invalid_api_key"

### ISSUE THREAD

**Issue by chelishchev** [acheong08/ChatGPT#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I just run my script to work with ChatGPT v1 api.
It works good about week. But couple days ago I've been getting error after 4-5 mins.

My script just sends request sequentially.
When I rerun script with the same access token it is working 4-5 mins and crash again.

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

It should work :)

### Version where the problem happens

Name: revChatGPT
Version: 3.0.5
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: asyncio, httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:

### What Python version are you running this with?

Python 3.10.5

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
2023-03-03 10:08:51,221 - revChatGPT.V1 - ERROR - ask - Field missing
NoneType: None
Traceback (most recent call last):
  File "/Users/ivan/Projects/test/chatgpt.py", line 285, in <module>
    asyncio.run(run_infinitive())
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ivan/Projects/test/chatgpt.py", line 281, in run_infinitive
    raise e
  File "/Users/ivan/Projects/test/chatgpt.py", line 259, in run_infinitive
    await work_with_posts(chatbot)
  File "/Users/ivan/Projects/test/chatgpt.py", line 209, in work_with_posts
    answer = await ask_chatgpt(chatbot, text_to_ask)
  File "/Users/ivan/Projects/test/chatgpt.py", line 159, in ask_chatgpt
    json_answer = await ask_chatgpt_inner(chatbot, question)
  File "/Users/ivan/Projects/test/chatgpt.py", line 141, in ask_chatgpt_inner
    for part_answer in chatbot.ask(question):
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/V1.py", line 515, in ask
    if line.get("detail", {}).get("code") == "invalid_api_key":
AttributeError: 'str' object has no attribute 'get'
Error: 'str' object has no attribute 'get'
```

**Comment by zhangxianwei2015** [comment]
Have the same issue.

**Comment by lmmsoft** [comment]
same issue either

**Comment by zhangxianwei2015** [comment]
I realized that it might be because the same account can only ask one question at the same time. I added some accounts, and it seems that there is no problem at present.

**Comment by chelishchev** [comment]
> I realized that it might be because the same account can only ask one question at the same time. I added some accounts, and it seems that there is no problem at present.

But I ask sequentially, I don't run it parallel

**Comment by acheong08** [comment]
Fixed
