### ISSUE TITLE
Check for ratelimits

### ISSUE THREAD

**Issue by bird** [acheong08/ChatGPT#101]
Currently there is no check anywhere for rate limits. This ends up making some errors misleading, such as a failing login with no explanation why.

Implementing a check should be as easy as just checking for 429 status on each request.

**Comment by Matthieu92-arch** [comment]
Hey bird, I saw this too. By any chance, do you know the structure of the dict I should give to get_chat_text() to make a request ?

**Comment by rawandahmad698** [comment]
Not every ratelimit (or a soft-ban) gives out 429. There are 400/502's

**Comment by acheong08** [comment]
Added

**Comment by talwrii** [comment]
Hit a rate limit just now. 429 response

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 182, in __get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/local/bin/llmchat", line 33, in <module>
    sys.exit(load_entry_point('large-language-model-cli', 'console_scripts', 'llmchat')())
  File "/Users/tomwright/mine/llmcli/llmcli/__init__.py", line 62, in chatgpt_main
    chatgpt(args)
  File "/Users/tomwright/mine/llmcli/llmcli/__init__.py", line 140, in chatgpt
    response = chat.get_chat_response(prompt)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 227, in get_chat_response
    return self.__get_chat_text(data)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 186, in __get_chat_text
    raise Exception("Not a JSON response") from exc2
Exception: Not a JSON response
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python3.10/site-packages/revChatGPT/revChatGPT.py(186)__get_chat_text()
-> raise Exception("Not a JSON response") from exc2
(Pdb) response.text
'{"detail":"Too many requests, please slow down"}'
(Pdb) response.headers
{'Content-Length': '48', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Cache': 'CONFIG_NOCACHE', 'X-Azure-Ref': '0SIyUYwAAAAASYFzdBjC+RoA2Cvl98PBkTE9OMjFFREdFMTYxOABlNjZiOGIwMy0wNzkzLTQ0MDktOTc3My0yZTYxMmU3MWExZTM=', 'Date': 'Sat, 10 Dec 2022 13:40:24 GMT', 'Connection': 'close'}
```

It might be nice to raise a specific excpetion for this. Unfortunately they don't seem to be telling us how long rate limit error lasts for.

**Comment by acheong08** [comment]
> Unfortunately they don't seem to be telling us how long rate limit error lasts for.

Tends to be a limit

> It might be nice to raise a specific excpetion for this.

WIP

**Comment by acheong08** [comment]
If you can, please do contribute.
