### ISSUE TITLE
[Bug]: Using 'match' causes problems for Python < 3.10

### ISSUE THREAD

**Issue by jrosebr1** [acheong08/ChatGPT#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Previous versions of `revChatGPT` were compatible with Python 3.9; however, `revChatGPT.V3.py` uses `match` syntax ([direct link to line](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V3.py#L222)) which is not supported in Python 3.9 (nor is it documented on the repo).

### Steps to reproduce the problem

1. Install Python 3.9
2. pip install latest version of `revChatGPT`
3. The following will throw the error:

```
from revChatGPT.V3 import Chatbot
```

### What should have happened?

Refactor to use `if/elif/else` statements to ensure maximum compatibility with Python versions.

### Version where the problem happens

revChatGPT==3.0.8

### What Python version are you running this with?

Python 3.9.5

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
N/A
```

### Console logs

```Shell
$ python manage.py foobar
Traceback (most recent call last):
  File "/Users/adrianrosebrock/Documents/Jaybird/jaybird-pegasus/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adrianrosebrock/.virtualenvs/pegasus/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/adrianrosebrock/.virtualenvs/pegasus/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/adrianrosebrock/.virtualenvs/pegasus/lib/python3.9/site-packages/django/core/management/__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/adrianrosebrock/.virtualenvs/pegasus/lib/python3.9/site-packages/django/core/management/__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/adrianrosebrock/Documents/Jaybird/jaybird-pegasus/apps/content_creation/management/commands/foobar.py", line 6, in <module>
    from revChatGPT.V3 import Chatbot
  File "/Users/adrianrosebrock/.virtualenvs/pegasus/lib/python3.9/site-packages/revChatGPT/V3.py", line 222
    match command:
```
```


### Additional information

_No response_

**Comment by jrosebr1** [comment]
I created the following PR to provide Python 3.9 compatability:

https://github.com/acheong08/ChatGPT/pull/1019

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/3.0.9
