### ISSUE TITLE
[Bug]: Getting "Too many requests in 1 hour" error after multiple tries

### ISSUE THREAD

**Issue by sromexs** [acheong08/ChatGPT#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When using the app, I received the error message "Too many requests in 1 hour. Try again later." after trying to make requests several times. This issue is happening repeatedly and it's preventing me from using the app effectively.

### Steps to reproduce the problem

Continue making requests until the app displays an error message "Too many requests in 1 hour. Try again later.", Sometimes getting empty string too.

### What should have happened?

Should get chatgpt valid response

### Version where the problem happens

Version: 3.2.0

### What Python version are you running this with?

Python 3.11.2

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Nothing
```

### Console logs

```Shell
$ python app.py
Chatbot: 
{"detail":"Too many requests in 1 hour. Try again later."}
Traceback (most recent call last):
  File "C:\Users\Sadra\Desktop\Ai\app.py", line 14, in <module>
    for data in chatbot.ask(
  File "C:\Users\Sadra\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 509, in ask
    self.__check_response(response)
  File "C:\Users\Sadra\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sadra\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 630, in __check_response
    raise Error(
revChatGPT.V1.Error: OpenAI: {"detail":"Too many requests in 1 hour. Try again later."} (code: 400)
```

### Additional information

The ChatGpt is not limited this error is wrong

**Comment by sushmitxo** [comment]
Getting the Same error. maybe openai is messing with this. 
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You: 
Hello, how are you?

Chatbot: 
{"detail":"Too many requests in 1 hour. Try again later."}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 1051, in <module>
    main(configure())
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 1029, in main
    for data in chatbot.ask(prompt):
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 509, in ask
    self.__check_response(response)
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/wsl/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 630, in __check_response
    raise Error(
__main__.Error: OpenAI: {"detail":"Too many requests in 1 hour. Try again later."} (code: 400)

**Comment by youmebangbang** [comment]
If I loop requests with try/catch and 10 second timeout I will get successful response, but infrequently.

**Comment by youyou-lv** [comment]
same problem here, run directly in us vps

**Comment by fredi-python** [comment]
I got the same error
i think it got fixed now : )

**Comment by acheong08** [comment]
Rate limit by OpenAI. It's account based. I can't fix this for you.

**Comment by acheong08** [comment]
Their rate limits have gotten worse as they roll out paid tiers
