### ISSUE TITLE
config.json  error

### ISSUE THREAD

**Issue by zlc000190** [acheong08/ChatGPT#1128]
python3 -m revChatGPT.V1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 360
    "access_tokens":{"someone@example.com": 'this account's access token', }

**Comment by acheong08** [comment]
Because that is not how you define the token. Please read the wiki
