### ISSUE TITLE
[Bug]: Uncaught error

### ISSUE THREAD

**Issue by justin-jiajia** [acheong08/ChatGPT#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I got these when I use V1 with my session cookies:
```
Chatbot:
|DNS-request| bypass.duti.tech
|S-chain|-<>-127.0.0.1:10808-<><>-4.2.2.2:53-<><>-OK
|DNS-response| bypass.duti.tech is 104.21.57.124
|S-chain|-<>-127.0.0.1:10808-<><>-104.21.57.124:443-<><>-OK
2023-03-11 17:50:27,362 - __main__ - ERROR - ask - Field missing
NoneType: None
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 1051, in <module>
    main(configure())
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 1029, in main
    for data in chatbot.ask(prompt):
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 581, in ask
    raise Error(
__main__.Error: ask: Field missing (code: 1)
```

### Steps to reproduce the problem

```
proxychains python -m revChatGPT.V1
```

### What should have happened?

answer me

### Version where the problem happens

Name: revChatGPT
Version: 3.3.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/ubuntu/xn/gp/lib/python3.8/site-packages
Requires: requests, tiktoken, OpenAIAuth, httpx, prompt-toolkit
Required-by:

### What Python version are you running this with?

Python 3.8.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
NO
```

### Console logs

```Shell
ProxyChains-3.1 (http://proxychains.sf.net)

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.
|DNS-request| explorer.api.openai.com
|S-chain|-<>-127.0.0.1:10808-<><>-4.2.2.2:53-<><>-OK
|DNS-response| explorer.api.openai.com is 52.152.96.252
|S-chain|-<>-127.0.0.1:10808-<><>-52.152.96.252:443-<><>-OK

You:
hi

Chatbot:
|DNS-request| bypass.duti.tech
|S-chain|-<>-127.0.0.1:10808-<><>-4.2.2.2:53-<><>-OK
|DNS-response| bypass.duti.tech is 104.21.57.124
|S-chain|-<>-127.0.0.1:10808-<><>-104.21.57.124:443-<><>-OK
2023-03-11 17:50:27,362 - __main__ - ERROR - ask - Field missing
NoneType: None
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 1051, in <module>
    main(configure())
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 1029, in main
    for data in chatbot.ask(prompt):
  File "/home/ubuntu/xn/gp/lib/python3.8/site-packages/revChatGPT/V1.py", line 581, in ask
    raise Error(
__main__.Error: ask: Field missing (code: 1)
```
```


### Additional information

_No response_

**Comment by acheong08** [comment]
Expired access token. Fetch new one manually or delete cache at `~/.config/revChatGPT.cache.json`. Also could be account issue. Try with different account

**Comment by justin-jiajia** [comment]
Ok Thanks
