### ISSUE TITLE
[Bug]: OpenAIAuth.Error

### ISSUE THREAD

**Issue by dbbice** [acheong08/ChatGPT#1157]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "E:/LineaRE-master (2)/LineaRE-master/new code/test.py", line 4, in <module>
    chatbot = Chatbot(config={
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 237, in __init__
    self.__check_credentials()
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 270, in __check_credentials
    raise error
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 268, in __check_credentials
    self.login()
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\revChatGPT\V1.py", line 413, in login
    auth.begin()
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error

### Steps to reproduce the problem

1. call interface
2. bug ....
3. ...

### What should have happened?

normal operation

### Version where the problem happens

V1

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error
```

**Comment by yegethebadd** [comment]
+1

**Comment by acheong08** [comment]
Track at 
- #1158
