### ISSUE TITLE
[Feature Request]: GPT-4 support.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

See [here](https://openai.com/product/gpt-4) for more details.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
Supported in V1. Draft for V3 https://github.com/acheong08/ChatGPT/pull/1169 requires minor changes

**Comment by hongyi-zhao** [comment]
For V1, once I've already finished the login authentication manually in browser, can I let it update the outdated [access token](https://github.com/acheong08/ChatGPT#--access-token) from [here](https://chat.openai.com/api/auth/session) automatically?

**Comment by acheong08** [comment]
Currently an internal function:
```
__set_access_token(self, access_token)
```

**Comment by acheong08** [comment]
I can expose it if necessary

**Comment by hongyi-zhao** [comment]
Please go ahead.

Another question: If we can always use the latest OpenAI API via `V1`, then the name `V1` seems a bit inappropriate, or more precisely, is it really necessary to implement various API call wrappers for different OpenAI API versions?

**Comment by acheong08** [comment]
> Considering that access_token is quite lengthy and cumbersome to set, why not add api_key authentication support in V1?

Because it's not supported

**Comment by acheong08** [comment]
> If we can always use the latest OpenAI API via V1, then the name V1 seems a bit inappropriate. OpenAI API iteration updates are very fast, and it is certain that the latest version is always the best. Based on this fact, is it really necessary to implement various API call wrappers for different OpenAI API versions?

I named them in the order which I wrote them. V1 refers to `chat.openai.com`

**Comment by LiuTangLei** [comment]
So using ChatGPT-Proxy-V4 allows us to use GPT-4 without worrying about being banned, right? (Assuming, of course, that we don't abuse it excessively)

**Comment by acheong08** [comment]
Proxy-V4 is still risky. Try to avoid it for now just in case. I'm working on V5 to make it safer

**Comment by acheong08** [comment]
GPT-4 supported on V3 (official API. Will cost you)

**Comment by hongyi-zhao** [comment]
Do you mean GPT-4 will be used automatically when I run V3?

**Comment by acheong08** [comment]
> Do you mean GPT-4 will be used automatically when I run V3?

No. Set engine to `gpt-4` or add `--model gpt-4` in command line

**Comment by hongyi-zhao** [comment]
```python
(datasci) werner@X10DAi:~$ python3 -m revChatGPT.V3 --api_key sk-xxx --proxy socks5h://127.0.0.1:18890 --model gpt-4

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
Are you use GPT-4 in this conversation with me?

ChatGPT: 
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 551, in <module>
    main()
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 544, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 151, in ask_stream
    response = self.session.post(
               ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))


```

**Comment by acheong08** [comment]
I've mentioned this before. OpenAI is blocked in China and Chinese associated DNS

**Comment by hongyi-zhao** [comment]
But if I removed the `--model gpt-4`, it will work:
```python
werner@X10DAi:~$ pyenv shell datasci 
(datasci) werner@X10DAi:~$ python3 -m revChatGPT.V3 --api_key sk-xxx --proxy socks5h://127.0.0.1:18890

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
Hello.

ChatGPT: 
Hello there! How can I assist you today?
```
How to explain this behavior?

**Comment by acheong08** [comment]
> requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

The error is obviously an SSL error. No changes are made by `--model gpt-4` other than max tokens and the model name. This should not cause SSL errors

**Comment by acheong08** [comment]
If it does cause an error, this is not the error it should cause

**Comment by hongyi-zhao** [comment]
When I switched to a US proxy, the following error occurred:

```python
(datasci) werner@X10DAi:~$ python3 -m revChatGPT.V3 --api_key sk-xxx --proxy socks5h://127.0.0.1:10103 --model gpt-4

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
Hello.

ChatGPT: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 551, in <module>
    main()
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 544, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 180, in ask_stream
    raise error
revChatGPT.typing.APIConnectionError: Error: 404 Not Found {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
```

**Comment by acheong08** [comment]
It means you haven't gotten access yet

**Comment by acheong08** [comment]
```py
 $ python3 -m revChatGPT.V3 --api_key sk-... --model gpt-4

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
你会说英文吗？

ChatGPT: 
是的，我会说英文。请问有什么我可以帮助您的？

User: 
```

**Comment by hongyi-zhao** [comment]
So, what are the prerequisites for using this feature? Must I use the plus version and purchase its services? I currently use a free account, as shown below:

![image](https://user-images.githubusercontent.com/11155854/226146908-9279ce8f-9b70-46d6-a14d-9d2bb224e41d.png)

**Comment by acheong08** [comment]
You must apply to the GPT-4 API and join the waitlist

**Comment by acheong08** [comment]
I also currently have free account but got accepted into their beta

**Comment by hongyi-zhao** [comment]
Do you mean to fill out the application form [here](https://openai.com/waitlist/gpt-4-api)?

![image](https://user-images.githubusercontent.com/11155854/226151763-47e214fd-5c4a-4ef2-b982-4ad4cb50858a.png)

**Comment by acheong08** [comment]
Yup

**Comment by hongyi-zhao** [comment]
But after I click on the `Join waitlist` button, the following error information returned:

![image](https://user-images.githubusercontent.com/11155854/226151911-ba275bb9-c482-4aa7-8729-a429597cf680.png)
