### ISSUE TITLE
[Bug]: revChatGPT.typing.CommandError: command line program unknown error

### ISSUE THREAD

**Issue by miljkovicjovan** [acheong08/ChatGPT#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

There is an error when I try to use the bot.

### Steps to reproduce the problem

1. I installed 
2. Made the config.json file
3. Tried to run V1

### What should have happened?

I should get a reply

### Version where the problem happens

4.0.5

### What Python version are you running this with?

Python 3.9.13

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
python3 -m revChatGPT.V1
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 997, in main
    for data in chatbot.ask(prompt):
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 453, in ask
    response = self.session.post(
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 68, in create_connection
    return six.raise_from(
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: '...', label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jovan/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jovan/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 1021, in <module>
    main(configure())
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 59, in wrapper
    out = func(*args, **kwargs)
  File "/Users/jovan/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 1007, in main
    raise error from e
revChatGPT.typing.CommandError: command line program unknown error
```

**Comment by acheong08** [comment]
Looks like a network issue

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by CoolPlayLin** [comment]
Is this problem accidental? Or do you always encounter this problem?

**Comment by qinjinghub2** [comment]
clash fro windows的端口改了，如果你是和我一样，把端口改成配置文件中的端口一直就可以了。

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
