### ISSUE TITLE
I try it and happen this

### ISSUE THREAD

**Issue by joytianya** [acheong08/ChatGPT#12]
I try it and happen this, please help me
```
Press enter twice to submit your question.


You: hello
Please wait for ChatGPT to formulate its full response...
{"detail":{"message":"Incorrect API key provided: <API_KEY>. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param"


Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/__main__.py", line 68, in <module>
    print("Chatbot:", response['message'])
TypeError: 'ValueError' object is not subscriptable
```

**Comment by acheong08** [comment]
It has been updated. Do `pip3 install revChatGPT --upgrade`

You can manually refresh the API key by doing `!refresh`
