### ISSUE TITLE
[Bug]: HOW TO USE THE PROXY IN V1 AND V3?

### ISSUE THREAD

**Issue by GAgHimama** [acheong08/ChatGPT#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

My proxy can work in requests like this：
import requests
http_proxy  = "http://127.0.0.1:57263"
https_proxy = "http://127.0.0.1:57263"

proxyDict = {
    "https" : https_proxy,
    "http"  : http_proxy

}
response = requests.get(url,proxies=proxyDict)

But I just don't know how it works when I use the V1 and V3 version.I have tried to use like:
V1:chatbot = Chatbot(config={"access_token":accesstoken,"proxy":"http://127.0.0.1:57263"})
V3:chatbot = Chatbot(api_key="<api_key>",proxy="http://127.0.0.1:57263")
All of them could not work as well.

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

My proxy can work in requests like this：
import requests
http_proxy  = "http://127.0.0.1:57263"
https_proxy = "http://127.0.0.1:57263"

proxyDict = {
    "https" : https_proxy,
    "http"  : http_proxy

}
response = requests.get(url,proxies=proxyDict)
I don't know how the proxy works in this.

### Version where the problem happens

version:3.3.1

### What Python version are you running this with?

3.10.2

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bypass.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\test.py", line 29, in <module>
    for data in chatbot.ask(prompt_0,conversation_id=cc,parent_id=pp):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 507, in ask
    response = self.session.post(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bypass.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```

**Comment by freebr** [comment]
No needed to use any proxy since there is a costless way to build a server accessing to openai. Just start to know Replit.
![image](https://user-images.githubusercontent.com/12162720/227702742-539b0203-191d-407e-996f-488eb289e917.png)

**Comment by limeiyang** [comment]
> No need to use any proxy since there is a costless way to build a server to invoke OpenAI API comfortably. Just start to know Replit. ![image](https://user-images.githubusercontent.com/12162720/227702812-7ebdca58-3e30-4264-a04f-e823db163547.png)

Thanks! Replit is amazing, I will try doing it. But what can I do to run it locally in IDEA?

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
