### ISSUE TITLE
[Bug]: Conection Error

### ISSUE THREAD

**Issue by HumanBot000** [acheong08/ChatGPT#1214]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

I was writing code for my private discord bot some weeks ago.
```py
@nextcord.slash_command(description="Ask ChatGPT")
    async def askgpt(self, interaction, prompt):
        # await interaction.channel.create_thread(name="ChatGPT", type=nextcord.ChannelType.public_thread) #TODO add thread support for conversations
        msg = await interaction.response.send_message("One moment please")
        load_dotenv()
        username = os.environ.get("EMAIL")
        password = os.environ.get("PASSWORD")
        # cookie = os.environ.get("COOKIE")
        config = {  # TODO use V2 after https://github.com/acheong08/ChatGPT#under-maintenance
            "email": username,
            "password": password
        }
        chatbot = Chatbot(config=config)

        response = ""

        for data in chatbot.ask(prompt):
            response = data["message"]
        await msg.edit(f"```{response}```")
   ```
   
   Everything worked fine until today. I get the error 
   ```
   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000269EC9EB970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

```

### Steps to reproduce the problem

1.Use the ```py

config = {  # TODO use V2 after https://github.com/acheong08/ChatGPT#under-maintenance
            "email": username,
            "password": password
        }
        chatbot = Chatbot(config=config)

        response = ""

        for data in chatbot.ask(prompt):
            response = data["message"]
            
``` code with a real password and username

2.See the console


### What should have happened?

The response should be visible in the discord message.

### Version where the problem happens

Name: revChatGPT
Version: 2.3.21
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: e:\.tobias\programmierung\python\installs\lib\site-packages
Requires: asyncio, httpx, OpenAIAuth, prompt-toolkit, requests
Required-by:

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\nextcord\client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "E:\.anonymous\Programmierung\Python\Projekte\MiniGamesBot\bot\bot.py", line 63, in on_application_command_error
    raise error
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\nextcord\application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "E:\.anonymous\Programmierung\Python\Projekte\MiniGamesBot\bot\cogs\Ki stuff.py", line 41, in askgpt
    for data in chatbot.ask(prompt):
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\revChatGPT\V1.py", line 473, in ask
    response = self.session.post(
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "E:\.anonymous\Programmierung\Python\Installs\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000269EC9EB970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

### Additional information

It already worked some weeks ago.The password and username out of the .env file are okay

**Comment by acheong08** [comment]
Your version is so incredible outdated. Many changes since then. We're up to https://github.com/acheong08/ChatGPT/releases/tag/4.0.9

**Comment by HumanBot000** [comment]
The Last time I noticed was V2 unser maintendance.Can you please give me a Code example of a simple Input Output Programm

**Comment by acheong08** [comment]
V2 no longer works

**Comment by acheong08** [comment]
Check readme

**Comment by HumanBot000** [comment]
OK thank you

**Comment by HumanBot000** [comment]
In the readme you wrote about V1.I use V1 with the Same Code as in the readme

**Comment by acheong08** [comment]
You just need to upgrade version `pip3 install --upgrade revChatGPT`

**Comment by HumanBot000** [comment]
OK thank you
