### ISSUE TITLE
[Bug]: Error code produced when including `--enable_internet` string

### ISSUE THREAD

**Issue by ElliotBadinger** [acheong08/ChatGPT#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I get an error message when trying to run the following line of code:
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet
(replace "sk-xxx" with your OpenAI API key)

The error code is as follows:

<frozen runpy>:128: RuntimeWarning: 'revChatGPT.V3' found in sys.modules after import of package 'revChatGPT', but prior to execution of 'revChatGPT.V3'; this may result in unpredictable behaviour

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

C:\Users\ellii\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\revChatGPT\V3.py:473: DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  config = path("revChatGPT", "config").__str__()
Traceback (most recent call last):
  File "C:\Users\ellii\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\revChatGPT\V3.py", line 554, in <module>
    main()
  File "C:\Users\ellii\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\revChatGPT\V3.py", line 474, in main
    chatbot.load(os.path.join(config, "enable_internet.json"), "conversation")
  File "C:\Users\ellii\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\revChatGPT\V3.py", line 262, in load
    with open(file, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '<contextlib._GeneratorContextManager object at 0x0000016D70197DD0>\\enable_internet.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ellii\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\revChatGPT\V3.py", line 557, in <module>
    raise error from e
revChatGPT.typings.CLIError: Command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

### Steps to reproduce the problem

1. Open PowerShell on Windows 10
2. Paste the code: python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet 
3. Replace "sk-xxx" with your OpenAI API key
4. Press enter and the error will show

### What should have happened?

The program should have loaded normally by typing in the following code:  
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet

This message should have then been displayed:

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

User:

### Version where the problem happens

version: 4.0.9

### What Python version are you running this with?

Python 3.11.0

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
N/A
```

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
