### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by betawarrior12** [acheong08/ChatGPT#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Each time I run the program it gives me this error:
KeyError: 'accessToken'
I tried many times but it is not working.
I think it is the Openai Auth

### Steps to reproduce the problem

I run it in a file

Here is code:

from revChatGPT.V1 import Chatbot
chatbot = Chatbot(config={"session_token": token})

def handle_commands(command: str) -> bool:
        if command == "!help":
            print(
                """
            !help - Show this message
            !reset - Forget the current conversation
            !config - Show the current configuration
            !rollback x - Rollback the conversation (x being the number of messages to rollback)
            !exit - Exit this program
            """,
            )
        elif command == "!reset":
            chatbot.reset_chat()
            print("Chat session successfully reset.")
        elif command == "!config":
            print(json.dumps(chatbot.config, indent=4))
        elif command.startswith("!rollback"):
            # Default to 1 rollback if no number is specified
            try:
                rollback = int(command.split(" ")[1])
            except IndexError:
                rollback = 1
            chatbot.rollback_conversation(rollback)
            print(f"Rolled back {rollback} messages.")
        elif command.startswith("!setconversation"):
            try:
                chatbot.config["conversation"] = command.split(" ")[1]
                print("Conversation has been changed")
            except IndexError:
                print("Please include conversation UUID in command")
        elif command == "!exit":
            exit(0)
        else:
            return False
        return True

def main():
    while True:
        prompt = input("\nYou:\n")
        if prompt.startswith("!"):
            if handle_commands(prompt):
                continue
        print("Chatbot: ")
        for data in chatbot.ask(prompt):
            message = data["message"]
        print(message, end="", flush=True)
        t = str(datetime.datetime.now().strftime("%a-%d-%b-%Y--%I.%M.%S.%p"))
        with open(t + ".txt", "w") as file:
            file.write(data["message"])
        print()

if __name__ == '__main__':
    main()

python chat.py

### What should have happened?

It should have shown:
!help - Show this message
            !reset - Forget the current conversation
            !config - Show the current configuration
            !rollback x - Rollback the conversation (x being the number of messages to rollback)
            !exit - Exit this program
You:

### Version where the problem happens

V1

### What Python version are you running this with?

3.8.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "chat.py", line 10, in <module>
    chatbot = Chatbot(config={"session_token": token})
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packag
es\revChatGPT\V1.py", line 66, in __init__
    self.__login()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packag
es\revChatGPT\V1.py", line 96, in __login
    auth.get_access_token()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packag
es\OpenAIAuth.py", line 313, in get_access_token
    self.access_token = response.json()["accessToken"]
```

**Comment by hrizal** [comment]
try using access_token

**Comment by betawarrior12** [comment]
Thanks it works

**Comment by betawarrior12** [comment]
Now it keeps showing:
Traceback (most recent call last):
  File "C:\Users\USER\Pemi\PYTHON\Projects\Made\chat\chat.py", line 64, in <module>
    main()
  File "C:\Users\USER\Pemi\PYTHON\Projects\Made\chat\chat.py", line 55, in main
    for data in chatbot.ask(prompt):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8\lib\site-packages\revChatGPT\V1.py", line 164, in ask
    response = self.session.post(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x02D2E2B0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by acheong08** [comment]
Very old version... `pip3 install --upgrade revChatGPT`

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
Track at #1236
