### ISSUE TITLE
[Bug]: ssl handshake error with explorer.api.openai.com

### ISSUE THREAD

**Issue by zer0mania** [acheong08/ChatGPT#1236]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

While running an api on replit with flask, I restarted the repl to make some changes for logging.

### Steps to reproduce the problem

1. Import revChatGPT and configurate the chatbot with session token

### What should have happened?

It should authenticate with no issues

### Version where the problem happens

Name: revChatGPT
Version: 4.0.11
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/runner/fr/venv/lib/python3.10/site-packages
Requires: OpenAIAuth, requests, tiktoken, openai, httpx, prompt-toolkit
Required-by: 

### What Python version are you running this with?

Python 3.10.8

### What is your operating system ?

Other/Cloud

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/fr/venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    chatbot = Chatbot(config={
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 163, in __init__
    self.__check_credentials()
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 187, in __check_credentials
    self.login()
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 329, in login
    auth.get_access_token()
  File "/home/runner/fr/venv/lib/python3.10/site-packages/OpenAIAuth.py", line 314, in get_access_token
    response = self.session.get(
  File "/home/runner/fr/venv/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/fr/venv/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))
```

### Additional information

https://replit.com/@zer0mania/fr if you want to see the code

**Comment by Germey** [comment]
+1

**Comment by Lcatss** [comment]
same problem

**Comment by acheong08** [comment]
OpenAIAuth ☠️

OpenAI shut down endpoint. Trying to find alternative endpoints

**Comment by Germey** [comment]
@acheong08 Do you think it will recovered? Seems their SSL cert is wrong for https://explorer.api.openai.com/

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8678661/228736687-431022da-6950-4d20-ad15-388fade96075.png">

**Comment by pengzhile** [comment]
> @acheong08 Do you think it will get recovered later? Seems their SSL cert is wrong for https://explorer.api.openai.com/, I think OpenAI should be responisble for fixing it.
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/8678661/228736687-431022da-6950-4d20-ad15-388fade96075.png">

It probably won't be fixed. But [https://chat.zhile.io](https://chat.zhile.io) works like a charm.

**Comment by acheong08** [comment]
I can fix it but would require using a proxy like your's. I don't think users would like their credentials to pass through such a service

**Comment by pengzhile** [comment]
> I can fix it but would require using a proxy like your's. I don't think users would like their credentials to pass through such a service

I provided a clear warning before logging in, allowing them to decide whether or not they want to use it.

**Comment by acheong08** [comment]
Yeah. That's all good. What I mean is for this repo, such a service cannot be adopted. They're welcome to use your UI.

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/discussions/1237

Will ask users for opinions

**Comment by AmarnathCJD** [comment]
> I also got an API working now. Though with the amount of time access tokens last these days, I think it's better than email/password authentication through somewhat untrusted services
> 
> Just gonna delete email/password auth from wiki

Then how are we gonna auth from now own in v1?

**Comment by acheong08** [comment]
Access token. Check wiki

**Comment by acheong08** [comment]
> Also curious about the solution.

A proxy server with cf_clearance or puid both works

**Comment by peanut996** [comment]
Got the same error on my vps, but when i run it on github codespaces, it works well. I do not know why.

**Comment by caohangabc** [comment]
> * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> 
> Will ask users for opinions

before get the API of GPT-4， this is the only way to use gpt-4 in script，So, fix it, please

**Comment by peanut996** [comment]
> > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > 
> > Will ask users for opinions
> 
> before get the API of GPT-4， this is the only way to use gpt-4 in script，So, fix it, please

why not use the `access_token` method? it can still work.

**Comment by yxjiang** [comment]
Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.

**Comment by peanut996** [comment]
> Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.

yes

**Comment by acheong08** [comment]
> Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.

It will. History is done through conversation_id

**Comment by yxjiang** [comment]
> 

oh, yes, I see it can be added as option config. Where to find it? I didn't see it from Cookies.

**Comment by Jirafey** [comment]
> > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> 
> It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token

how do we get conversation_id or parent_id?

**Comment by AkiyaKiko** [comment]
> > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > 
> > 
> > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> 
> how do we get conversation_id or parent_id?

same question, how can i get conversation_id

**Comment by Jirafey** [comment]
> > > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > > 
> > > 
> > > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> > 
> > 
> > how do we get conversation_id or parent_id?
> 
> same question, how can i get conversation_id

i got it:
1. get over to https://chat.openai.com/chat
2. Tap on a previous chat, in the link of the website you'll find the:
https://chat.openai.com/chat/your_conversation_id

**Comment by AkiyaKiko** [comment]
> > > > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > > > 
> > > > 
> > > > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> > > 
> > > 
> > > how do we get conversation_id or parent_id?
> > 
> > 
> > same question, how can i get conversation_id
> 
> i got it:
> 
>     1. get over to https://chat.openai.com/chat
> 
>     2. Tap on a previous conversation, (not the newly created one).
>        In the link of the website you'll find the:
>        https://chat.openai.com/chat/your_conversation_id

got it
but it still can't continue the conversation with the history before, it still start through a new conversation

**Comment by Jirafey** [comment]
> > > > > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > > > > 
> > > > > 
> > > > > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> > > > 
> > > > 
> > > > how do we get conversation_id or parent_id?
> > > 
> > > 
> > > same question, how can i get conversation_id
> > 
> > 
> > i got it:
> > ```
> > 1. get over to https://chat.openai.com/chat
> > 
> > 2. Tap on a previous conversation, (not the newly created one).
> >    In the link of the website you'll find the:
> >    https://chat.openai.com/chat/your_conversation_id
> > ```
> 
> got it but it still can't continue the conversation with the history before, it still start through a new conversation

maybe you need the first parent_id in the chat
endpoint:
<ip>:<port>/api/conversation/<chat_id>

![image](https://user-images.githubusercontent.com/97115044/229097518-bdaff25f-ddcb-4ecb-8de2-09deabe07ed6.png)

**Comment by caohangabc** [comment]
> it can still work.

thank you, it works

**Comment by AkiyaKiko** [comment]
> > > > > > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > > > > > 
> > > > > > 
> > > > > > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> > > > > 
> > > > > 
> > > > > how do we get conversation_id or parent_id?
> > > > 
> > > > 
> > > > same question, how can i get conversation_id
> > > 
> > > 
> > > i got it:
> > > ```
> > > 1. get over to https://chat.openai.com/chat
> > > 
> > > 2. Tap on a previous conversation, (not the newly created one).
> > >    In the link of the website you'll find the:
> > >    https://chat.openai.com/chat/your_conversation_id
> > > ```
> > 
> > 
> > got it but it still can't continue the conversation with the history before, it still start through a new conversation
> 
> maybe you need the first parent_id in the chat endpoint: "(ip):(port)/api/conversation/(chat_id)"
> 
> ![image](https://user-images.githubusercontent.com/97115044/229097518-bdaff25f-ddcb-4ecb-8de2-09deabe07ed6.png)
> 
> i dont know what im doing but hope somehting like this helps

OK, i got it. But how can i get the parent_id,? Dose every post get response with different parent_id?

**Comment by Jirafey** [comment]
> > > > > > > > Use `access_token` works, but the conversation won't have a history. A new session will be created on every call.
> > > > > > > 
> > > > > > > 
> > > > > > > It will. History is done through conversation_id. All OpenAIAuth does is fetch the access token
> > > > > > 
> > > > > > 
> > > > > > how do we get conversation_id or parent_id?
> > > > > 
> > > > > 
> > > > > same question, how can i get conversation_id
> > > > 
> > > > 
> > > > i got it:
> > > > ```
> > > > 1. get over to https://chat.openai.com/chat
> > > > 
> > > > 2. Tap on a previous conversation, (not the newly created one).
> > > >    In the link of the website you'll find the:
> > > >    https://chat.openai.com/chat/your_conversation_id
> > > > ```
> > > 
> > > 
> > > got it but it still can't continue the conversation with the history before, it still start through a new conversation
> > 
> > 
> > maybe you need the first parent_id in the chat endpoint: "(ip):(port)/api/conversation/(chat_id)"
> > ![image](https://user-images.githubusercontent.com/97115044/229097518-bdaff25f-ddcb-4ecb-8de2-09deabe07ed6.png)
> > i dont know what im doing but hope somehting like this helps
> 
> OK, i got it. But how can i get the parent_id,? Dose every post get response with different parent_id?

yeah seems like it... I am kinda busy with another project, we just need to wait for the fix of ssl3 handsake error,
sidenote:
I looked over this: and its also a pretty interesting project
[chat.zhile.io](https://chat.zhile.io/)

**Comment by MagzhanUnited** [comment]
It doesn't work with session token

**Comment by MagzhanUnited** [comment]
I have the same issue when I use session token

**Comment by pengzhile** [comment]
> * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> 
> Will ask users for opinions

A very interesting auth service. It is safe and quite ingenious: [https://chat.gateway.do/auth](https://chat.gateway.do/auth)

**Comment by Jirafey** [comment]
> > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > 
> > Will ask users for opinions
> 
> A very interesting auth service. It is safe and quite ingenious: https://chat.gateway.do/auth

yeah i saw that too, this website got the endpoints well

**Comment by gruberdev** [comment]
> > > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > > 
> > > Will ask users for opinions
> > 
> > 
> > A very interesting auth service. It is safe and quite ingenious: [chat.gateway.do/auth](https://chat.gateway.do/auth)
> 
> yeah I saw that too, this website got the endpoints well

I think it would be more productive to talk about self-hosted alternatives since there are plenty of users with ChatGPT plus accounts that have been blocked by these new changes. Those who want services and 3rd hosted providers will benefit from server providers having information readily available on how to solve this issue as well, which is not the case today. Plus adds a lot of noise to non-related discussions. 

For example, is this the only library that provides access to the non-official endpoints? I haven't been able to find another example.


> > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > 
> > Will ask users for opinions
> 
> A very interesting auth service. It is safe and quite ingenious: [chat.gateway.do/auth](https://chat.gateway.do/auth)

Also, this website is very suspicious, I hope you are not using your real accounts there. How do you know it is safe?

**Comment by RoseLoverX** [comment]
> > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > 
> > Will ask users for opinions
> 
> A very interesting auth service. It is safe and quite ingenious: https://chat.gateway.do/auth

how is it used?? after we get the https://explorer.api.openai.com/api/auth/callback/auth0, whats the next step

**Comment by pengzhile** [comment]
> > > * [The fate of Email/Password authentication #1237](https://github.com/acheong08/ChatGPT/discussions/1237)
> > > 
> > > Will ask users for opinions
> > 
> > 
> > A very interesting auth service. It is safe and quite ingenious: https://chat.gateway.do/auth
> 
> how is it used?? after we get the https://explorer.api.openai.com/api/auth/callback/auth0, whats the next step

Paste this URL back into the textarea on the previous page.

**Comment by acheong08** [comment]
> I think it would be more productive to talk about self-hosted alternatives since there are plenty of users with ChatGPT plus accounts that have been blocked by these new changes.

https://github.com/acheong08/OpenAIAuth/blob/main/auth/OpenAiAuth.go

If people got plus accounts, they can use PUID to host it

**Comment by acheong08** [comment]
But I won't be using any third party authentication servers because of possible security concerns

**Comment by acheong08** [comment]
Please just use access tokens. They take 2 weeks to expire

**Comment by Jirafey** [comment]
How to use access_token with the proxy though? I dont seem to understand what to do, I see links but I have no idea whats the plan.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/wiki/Authentication#access-token

**Comment by acheong08** [comment]
Copy the token from the URL to config

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT#--access-token

**Comment by AmarnathCJD** [comment]
https://github.com/AmarnathCJD/ChatGPT/blob/master/auth.go

sus site but accesstoken gen from email/pass working nice 🙂

**Comment by AmarnathCJD** [comment]
> Please just use access tokens. They take 2 weeks to expire

30 days I getting like 719Hours as expireTime

**Comment by AmarnathCJD** [comment]
@acheong08 https://github.com/AmarnathCJD/ChatGPT/blob/72e8dc13a082221c41ec3c1c7a871a194095cef1/ask.go#L214

The chat history thing is not working, each message is out of context

Could you please point out what I'm doing wrong here 🫠

**Comment by acheong08** [comment]
> @acheong08 [AmarnathCJD/ChatGPT@`72e8dc1`/ask.go#L214](https://github.com/AmarnathCJD/ChatGPT/blob/72e8dc13a082221c41ec3c1c7a871a194095cef1/ask.go#L214)
> 
> The chat history thing is not working, each message is out of context
> 
> Could you please point out what I'm doing wrong here 🫠

Missing conversation id

**Comment by RoseLoverX** [comment]
> > @acheong08 [AmarnathCJD/ChatGPT@`72e8dc1`/ask.go#L214](https://github.com/AmarnathCJD/ChatGPT/blob/72e8dc13a082221c41ec3c1c7a871a194095cef1/ask.go#L214)
> > The chat history thing is not working, each message is out of context
> > Could you please point out what I'm doing wrong here 🫠
> 
> Missing conversation id

got it fixed tnqqq

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by MagzhanUnited** [comment]
will it be solved?

**Comment by AkiyaKiko** [comment]
> Copy the token from the URL to config
the conversation_id doesn't work in config, but it works in parameter of bot.ask(), i don't know why

**Comment by acheong08** [comment]
> will it be solved?

Probably not. Mass authentication from a proxy will get accounts banned.

**Comment by acheong08** [comment]
Access tokens now the only way

**Comment by HarutaLuna** [comment]
> will it be solved?

@MagzhanUnited 

you can use access token can be obtained through
https://chat.openai.com/api/auth/session
make sure you have logged in first

**Comment by hacksman** [comment]
same error
