### ISSUE TITLE
[Bug]: httpx._exceptions.HTTPError: 429 Client Error

### ISSUE THREAD

**Issue by HumanBot000** [acheong08/ChatGPT#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I have the following code:
```py
config = {  # TODO use V2 after https://github.com/acheong08/ChatGPT#under-maintenance
                "email": username,
                "password": password,
                "conversation_id": "11c127dd-f136-46cc-88a7-876782c4291c",
                "parent_id": "11c127dd-f136-46cc-88a7-876782c4291c"
            }
            chatbot = AsyncChatbot(config=config,conversation_id="11c127dd-f136-46cc-88a7-876782c4291c")
            response = ""
            for data in chatbot.ask(message.content):
                response = data["message"]
  ```
  But I get the error TypeError: 'async_generator' object is not iterable.
  
  I did the same with the normal/non async class.It worked fine

### Steps to reproduce the problem

Use the code above and change username password and conversation id

### What should have happened?

I get the answer.

### Version where the problem happens

```
Name: revChatGPT
Version: 4.0.11
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Requires: httpx, openai, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:
```

4.0.11

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Ignoring exception in on_message
Traceback (most recent call last):
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\nextcord\client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "E:\.Tobias\Programmierung\Python\Projekte\MiniGamesBot\bot\cogs\Ki stuff.py", line 42, in on_message
    for data in chatbot.ask(message.content):
TypeError: 'async_generator' object is not iterable
```

**Comment by acheong08** [comment]
Incorrect usage. `async for ...`

**Comment by HumanBot000** [comment]
Ah sorry I never used async loops before

**Comment by HumanBot000** [comment]
```py
question = message.content
            load_dotenv()
            username = os.environ.get("EMAIL")
            password = os.environ.get("PASSWORD")
            # cookie = os.environ.get("COOKIE")
            config = {
                "email": username,
                "password": password
            }
            chatbot = AsyncChatbot(config=config,conversation_id="11c127dd-f136-46cc-88a7-876782c4291c")
            response = ""
            async for data in chatbot.ask(question):
                response = data["message"]
                ```

**Comment by acheong08** [comment]
Not sure about this error. Need more debug info

**Comment by HumanBot000** [comment]
What do you need?

**Comment by HumanBot000** [comment]
No I got 
```
HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))
```
With the non async method.This worked just fine before

**Comment by AmarnathCJD** [comment]
> No I got
> 
> ```
> HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))
> ```
> 
> With the non async method.This worked just fine before

#1236

**Comment by HumanBot000** [comment]
Somehow I fixed the non async thing again but the async does not woork

**Comment by HumanBot000** [comment]
Ops missclicked

**Comment by zorrol** [comment]
今天也出现了429错误。 
Traceback (most recent call last):
  File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 333, in ask
    full_response: str = "".join(response)
  File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 200, in ask_stream
    raise error
revChatGPT.typings.APIConnectionError: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by lss233** [comment]
> 今天也出现了429错误。 Traceback (most recent call last): File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 333, in ask full_response: str = "".join(response) File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 200, in ask_stream raise error revChatGPT.typings.APIConnectionError: 429 Too Many Requests { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }

`You exceeded your current quota, please check your plan and billing details.` 这是欠费了 😂

**Comment by HumanBot000** [comment]
In the docs was something said about 3 messages every 5 seconds or not?

**Comment by HumanBot000** [comment]
"3:35 PM - Rate limit at 5 requests / 10 seconds due to small server (I ran out of budget.)"

**Comment by acheong08** [comment]
Seems like an async issue

**Comment by HumanBot000** [comment]
Yes I know.What can I do

**Comment by acheong08** [comment]
Not much until I can find a way to fix it. Consider the async version barely maintained.

**Comment by acheong08** [comment]
It's sending too many requests for some reason. Perhaps try upgrading and see if lazy loading helps

**Comment by HumanBot000** [comment]
Thank you.Can you notify me if it is fixed.

**Comment by acheong08** [comment]
Keep open. I will track the issue here

**Comment by zorrol** [comment]
> > 今天也出现了429错误。 Traceback (most recent call last): File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 333, in ask full_response: str = "".join(response) File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 200, in ask_stream raise error revChatGPT.typings.APIConnectionError: 429 Too Many Requests { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }
> 
> `You exceeded your current quota, please check your plan and billing details.` 这是欠费了 😂

是OpenAI欠费，还是什么欠费？

**Comment by karbonnanroid** [comment]
t

**Comment by Imccccc** [comment]
> > > 今天也出现了429错误。 Traceback (most recent call last): File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 333, in ask full_response: str = "".join(response) File "/Users/bin/PycharmProjects/ChatGPT/src/revChatGPT/V3.py", line 200, in ask_stream raise error revChatGPT.typings.APIConnectionError: 429 Too Many Requests { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }
> > 
> > 
> > `You exceeded your current quota, please check your plan and billing details.` 这是欠费了 😂
> 
> 是OpenAI欠费，还是什么欠费？

免费额度花完了。
you have to add a credit to pay the bill.

**Comment by HumanBot000** [comment]
Read the conversation it is a bug

**Comment by Porcupine96** [comment]
I don't know if this related but I'm getting a similar error:
```
{"detail":"Too many requests in 1 minute. Try again later."}
```

This happens when I initialize the V1 chatbot passing only the `conversation_id` (like you did @HumanBot000). 

It works fine if:
a) I don't set any `conversation_id`
b) I set both the `conversation_id` and `parent_id`

Maybe passing only `conversation_id` results in some additional requests to retrieve the last `parent_id`?

**Comment by HumanBot000** [comment]
Hi okay I will try it and say if it works

Łukasz Kaźmierczak ***@***.***> schrieb am So., 2. Apr. 2023,
20:42:

**Comment by acheong08** [comment]
> {"detail":"Too many requests in 1 minute. Try again later."}

This error is from OpenAI

**Comment by acheong08** [comment]
@Porcupine96 Is lazy loading enabled? It reduces the number if requests. Try upgrading to latest  version which has that enabled by default for sync (idk async)

**Comment by HumanBot000** [comment]
> I don't know if this related but I'm getting a similar error:
> 
> ```
> {"detail":"Too many requests in 1 minute. Try again later."}
> ```
> 
> This happens when I initialize the V1 chatbot passing only the `conversation_id` (like you did @HumanBot000).
> 
> It works fine if: a) I don't set any `conversation_id` b) I set both the `conversation_id` and `parent_id`
> 
> Maybe passing only `conversation_id` results in some additional requests to retrieve the last `parent_id`?




```py
config = {
                "email": username,
                "password": password
            }
            chatbot = AsyncChatbot(config=config,conversation_id="11c127dd-f136-46cc-88a7-876782c4291c",parent_id="11c127dd-f136-46cc-88a7-876782c4291c")
            response = ""
            async for data in chatbot.ask(question):
                response = data["message"]
                
```


ends in 

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))
```

**Comment by HumanBot000** [comment]
Information:
my IDE gives me in 
```py
async for data in chatbot.ask(question):
``` specific in chatbot.ask(question)

the warning
```
Expected type 'collections.AsyncIterable', got 'dict' instead 
```

**Comment by HumanBot000** [comment]
Information:
I reinstalled revchatgpt and now I got 
```ValueError: PUID is required```
with the same code

**Comment by acheong08** [comment]
OpenAIAuth is broken. Use access tokens instead. Check readme and wiki

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by HumanBot000** [comment]
```py
    @commands.Cog.listener()
    async def on_message(self, message):
        # Prüfen, ob die Nachricht im richtigen Channel ist und der Autor kein Bot ist
        if message.channel.id == 1089194242175418398 and message.author.id != self.bot.user.id:
            question = message.content
            load_dotenv()
            #username = os.environ.get("EMAIL")
            #password = os.environ.get("PASSWORD")
            token  = os.environ.get("GPTTOKEN")
            config = {
                "access_token": ""
            }
            chatbot = AsyncChatbot(config=config,conversation_id="4cff500a-e7a5-4faa-b6cc-ae54aa650b96",parent_id="4cff500a-e7a5-4faa-b6cc-ae54aa650b96")
            response = ""
            async for data in chatbot.ask(question):
                response = data["message"]
            await message.channel.send(f"```{response}```")
```


```
Ignoring exception in on_message
Traceback (most recent call last):
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\nextcord\client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "E:\.Tobias\Programmierung\Python\Projekte\MiniGamesBot\bot\cogs\Ki stuff.py", line 39, in on_message
    async for data in chatbot.ask(question):
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\revChatGPT\V1.py", line 738, in ask
    data["conversation_id"],
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_client.py", line 1525, in __aenter__
    self.response = await self.client.send(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_client.py", line 1168, in send
    response = await self.send_handling_redirects(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_client.py", line 1195, in send_handling_redirects
    response = await self.send_handling_auth(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_client.py", line 1264, in send_single_request
    ) = await transport.request(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpcore\_async\connection_pool.py", line 152, in request
    response = await connection.request(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpcore\_async\connection.py", line 78, in request
    return await self.connection.request(method, url, headers, stream, timeout)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpcore\_async\http11.py", line 55, in request
    await self._send_request(method, url, headers, timeout)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpcore\_async\http11.py", line 81, in _send_request
    event = h11.Request(method=method, target=target, headers=headers)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\h11\_events.py", line 55, in __init__
    self.headers = _headers.normalize_and_validate(
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\h11\_headers.py", line 77, in normalize_and_validate
    validate(_field_value_re, value, "Illegal header value {!r}", value)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\h11\_util.py", line 108, in validate
    raise LocalProtocolError(msg)
h11._util.LocalProtocolError: Illegal header value b'Bearer '
```

**Comment by HumanBot000** [comment]
Should I open a new one?

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.
