### ISSUE TITLE
[Bug]: Error Code 1020

### ISSUE THREAD

**Issue by CyberDie22** [acheong08/ChatGPT#1239]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I use the V1 API, anything that I do results in Error 1020. This seems to have happened 2 weeks ago and was fixed, but it seems that it is happening again.

### Steps to reproduce the problem

```python
from revChatGPT import V1
chatbot = V1.Chatbot(config: { 'access_token': 'ACCESS_TOKEN' })
chatbot.get_conversations() # OpenAI: error code 1020 (code 403)
```

### What should have happened?

Return the conversations on the account

### Version where the problem happens

4.0.11

### What Python version are you running this with?

3.10.10

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
error code: 1020
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/name/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/Users/name/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 573, in get_conversations
    self.__check_response(response)
  File "/Users/name/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/Users/name/.asdf/installs/python/3.10.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 557, in __check_response
    raise error
revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)
```

**Comment by harryeffinpotter** [comment]
Same! just started happening!

**Comment by Jxells** [comment]
昨天还是能用的，早上起来就1020了

**Comment by nikolaiharkov** [comment]
same

**Comment by acheong08** [comment]
Fixed

**Comment by trentluo** [comment]
> Fixed

thanks，but what shoud i  do ?

**Comment by trentluo** [comment]
> Fixed

it is fixed, thanks
