### ISSUE TITLE
[Bug]: HTTPSConnectionPool(host='explorer.api.openai.com', port=443),what should I do?

### ISSUE THREAD

**Issue by zhouwei713** [acheong08/ChatGPT#1247]
### Is there an existing issue for this?

- [X] #1248

### What happened?

import os
from revChatGPT.V1 import Chatbot

os.environ["HTTP_PROXY"] = "127.0.0.1:10810"
os.environ["HTTPS_PROXY"] = "http://127.0.0.1:10810"

config={
  "email": "xxxxx@outlook.com",
  "password": "xxxxx"
}
chatbot = Chatbot(config=config)

prompt = "help me generate something"
response = ""

for data in chatbot.ask(
  prompt
):
    response = data["message"]

print(response)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

no

### Version where the problem happens

Name: revChatGPT
Version: 2.3.14
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: c:\python3\lib\site-packages
Requires: asyncio, httpx, OpenAIAuth, requests
Required-by:

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Python3\lib\site-packages\urllib3\connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "C:\Python3\lib\site-packages\urllib3\util\ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "C:\Python3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python3\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Python3\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Python3\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Python3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Python_project/auto_weibo/test_gpt.py", line 21, in <module>
    chatbot = Chatbot(config=config)
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 147, in __init__
    self.__check_credentials()
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 161, in __check_credentials
    self.__login()
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\revChatGPT\V1.py", line 267, in __login
    auth.begin()
  File "C:\Python3\lib\site-packages\OpenAIAuth.py", line 72, in begin
    headers=headers,
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python3\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1091)')))
```

**Comment by acheong08** [comment]
- #1236
