### ISSUE TITLE
V3 failed once more.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1252]
See below:

```python
(datasci) werner@X10DAi:~$ revChatGPT 3

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
hello.

ChatGPT: 
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 688, in <module>
    main()
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 681, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 171, in ask_stream
    response = self.session.post(
               ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 691, in <module>
    raise error from e
revChatGPT.typings.CLIError: Command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

```

**Comment by Pengchengistaken** [comment]
same

**Comment by hongyi-zhao** [comment]
The error message is mutable, I also encountered the following one:

```python
werner@X10DAi:~$ revChatGPT 3

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
请详细描述群论基本定理。

ChatGPT: 
当我们谈论群论基本定理时，通常是指三个基本定理：拉格朗日定理、卡西迪定理和第一同构定理。这些定理是群论中最基本的定理之一，对于理解群论的基本概念和性质非常重要。

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 688, in <module>
    main()
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 681, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 203, in ask_stream
    for line in response.iter_lines():
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 691, in <module>
    raise error from e
revChatGPT.typings.CLIError: Command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
```

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
