### ISSUE TITLE
[Bug]: requests.exceptions.ChunkedEncodingError  when calling ChatGPT API 

### ISSUE THREAD

**Issue by zhaozh10** [acheong08/ChatGPT#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I hope to call ChatGPT API to translate hundreds of English text. 

In practice, I define "chatbot" as a global variable.
`chatbot = Chatbot(engine="gpt-3.5-turbo",api_key="API_KEY")`

Then I define this function and call it in each iteration of for loop
```
def chat_with_gpt(prompt):
    message = chatbot.ask(prompt)
    chatbot.reset()
    return message
```

I define a for loop to iterate over hundreds of pieces of English texts, just like:

```
for i in tqdm(range(len(info))):
        content = info[i]
        prompt="Translate the paragraph below into Chinese:\n"+content
        repeat=0
        while repeat<=5:
            try:
                message=chat_with_gpt(prompt)
            except:
                repeat+=1
                time.sleep(2)
                continue
            break
        res.append([content,message])
```
The issue is that it will raise the mentioned error by accident after running over 40 minutes.

### Steps to reproduce the problem

1. Run the code
2. Wait...
3. sometimes, it will raise in 40 minutes, but sometimes it can hold on for over 3 hours, quite weird.

### What should have happened?

Normally, it should iterate over all English paragraphs and translate them all.

### Version where the problem happens

`revchatgpt   4.0.11`

### What Python version are you running this with?

3.8.13

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No command Line, I just run in the vscode.
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 748, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 815, in read_chunked
    self._update_chunk_length()
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 752, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 844, in read_chunked
    self._original_response.close()
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/urllib3/response.py", line 460, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zihao/LMFlow/translate.py", line 71, in <module>
    tranverse(info_todo)
  File "/home/zihao/LMFlow/translate.py", line 45, in tranverse
    message=chat_with_gpt(prompt)
  File "/home/zihao/LMFlow/translate.py", line 20, in chat_with_gpt
    message = chatbot.ask(prompt)
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/revChatGPT/V3.py", line 226, in ask
    full_response: str = "".join(response)
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/revChatGPT/V3.py", line 188, in ask_stream
    for line in response.iter_lines():
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/home/zihao/anaconda3/envs/idea/lib/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by acheong08** [comment]
try except, timeout retry. This is an issue of OpenAI

**Comment by zhaozh10** [comment]
Thanks!
