### ISSUE TITLE
提取指定URL的文章中的latax公式。

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1266]
不知道下面的是否可以实现？
```python
werner@X10DAi:~$ revChatGPT 3

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.


User: 
http://cs231n.stanford.edu/reports/2017/pdfs/815.pdf
提取上面文章中的latax公式
 

ChatGPT: 
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/home/werner/.pyenv/versions/3.11.1/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 688, in <module>
    main()
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 681, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 171, in ask_stream
    response = self.session.post(
               ^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/Public/repo/github.com/acheong08/ChatGPT.git/src/revChatGPT/V3.py", line 691, in <module>
    raise error from e
revChatGPT.typings.CLIError: Command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

```

**Comment by CoolPlayLin** [comment]
你的网络有问题

**Comment by CoolPlayLin** [comment]
![image](https://user-images.githubusercontent.com/96709586/229962468-206010d7-f58d-48cb-8648-29348ec094c7.png)

**Comment by hongyi-zhao** [comment]
我再次尝试，结果如下：

```
V1:

You: 
http://cs231n.stanford.edu/reports/2017/pdfs/815.pdf
提取上面文章中的latax公式

Chatbot: 
抱歉，作为AI语言模型，我无法直接访问网页并提取其中的LaTeX公式。但我可以告诉您，LaTeX公式通常在文本中用“$”符号包围。在文章中搜索这个符号可以帮助您找到其中的LaTeX公式。另外，如果您使用Chrome浏览器，可以安装一些扩展程序，如MathJax Plugin for Github和TeX All the Things，它们可以在网页中渲染LaTeX公式，使其更容易查看和复制。


V3:

User: 
http://cs231n.stanford.edu/reports/2017/pdfs/815.pdf
提取上面文章中的latax公式

ChatGPT: 
抱歉，我无法直接从文章中提取LaTeX公式，但是我可以告诉你如何在LaTeX中编写常见的数学公式。例如，要编写一个简单的方程式，可以使用以下代码：

```
\begin{equation}
    y = mx + b
\end{equation}
```

这将生成以下方程式：

$$y = mx + b$$

如果您需要更复杂的数学公式，可以在LaTeX中使用各种符号和命令来创建它们。如果您需要帮助，请告诉我您需要编写的特定公式，我会尽力帮助您。
```

**Comment by hongyi-zhao** [comment]
然后，再次使用V3尝试，给出如下结果：

```
User: 
http://cs231n.stanford.edu/reports/2017/pdfs/815.pdf
提取上面文章中的latax公式

ChatGPT: 
好的，以下是该文章中出现的一些LaTeX公式：

1. 感知器模型公式：

$$\hat{y} = f(w^Tx + b)$$

2. 损失函数公式：

$$L_i = \sum_{j \neq y_i} \max(0, s_j - s_{y_i} + \Delta)$$

3. Softmax函数公式：

$$p_j = \frac{e^{s_j}}{\sum_k e^{s_k}}$$

4. 交叉熵损失函数公式：

$$L_i = -\log\left(\frac{e^{f_{y_i}}}{\sum_je^{f_j}}\right)$$

5. Dropout正则化公式：

$$\text{dropout}(x) = x \odot \text{mask}$$

其中，$\odot$表示哈达玛积（即元素级乘法），$\text{mask}$是一个与$x$相同形状的二进制掩码，其中每个元素都独立地以概率$p$设置为$0$或$1$。
```

但是，这些都是胡编乱造的，原文中根本没有这些。

**Comment by hongyi-zhao** [comment]
进一步使用 [gpt-4 测试](https://nat.dev/)，结果依然是胡编乱造：

![image](https://user-images.githubusercontent.com/11155854/229974796-fb6f7264-4027-4be1-b510-e4d1ea192c17.png)

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.
