### ISSUE TITLE
[Bug]: ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed)

### ISSUE THREAD

**Issue by zhangxiaoyuan1988** [acheong08/ChatGPT#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

streamlit run web_demo2.py
Traceback (most recent call last):
  File "/opt/conda/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/opt/conda/lib/python3.10/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/opt/conda/lib/python3.10/site-packages/streamlit/delta_generator.py", line 42, in <module>
    from streamlit.elements.arrow import ArrowMixin
  File "/opt/conda/lib/python3.10/site-packages/streamlit/elements/arrow.py", line 31, in <module>
    from pandas.io.formats.style import Styler
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/formats/style.py", line 56, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/opt/conda/lib/python3.10/site-packages/pandas/compat/_optional.py", line 171, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).

### Steps to reproduce the problem

pandas                 1.5.3

### What should have happened?

1

### Version where the problem happens

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

### Command Line Arguments

```Shell
麻烦问下大佬这个错误是啥原因？
```

### Console logs

```Shell
1
```

**Comment by zhangxiaoyuan1988** [comment]
错误
