### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BlackSleepYT** [acheong08/ChatGPT#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

drop me this : 
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Version: 4.2.0

Type '!help' to show a full list of commands
←[1m←[93mPress Esc followed by Enter or Alt+Enter to send a message.←[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\revchatgpt-4.2.1-py3.11.egg\revChatGPT\V1.py", line 1315, in <module>
  File "C:\Python311\Lib\site-packages\revchatgpt-4.2.1-py3.11.egg\revChatGPT\V1.py", line 54, in wrapper
  File "C:\Python311\Lib\site-packages\revchatgpt-4.2.1-py3.11.egg\revChatGPT\V1.py", line 1192, in configure
  File "C:\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 71)

after write the file "config.json" and ejecute this command "python -m revChatGPT.V1" 

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

0

### Version where the problem happens

0

### What Python version are you running this with?

0

### Command Line Arguments

```Shell
0
```

### Console logs

```Shell
0
```

### Additional information

0

**Comment by acheong08** [comment]
Invalid JSON
