### ISSUE TITLE
[Bug]: 429 Client Error: Too Many Requests for url:

### ISSUE THREAD

**Issue by HumanBot000** [acheong08/ChatGPT#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I just requested one time and waited 5 minutes and then I got the same error.

### Steps to reproduce the problem

```py

 async def on_message(self, message):
        if message.channel.id == 1096821821103411360 and message.author.id != self.bot.user.id:
            question = message.content
            print(question)
            load_dotenv()
            #username = os.environ.get("EMAIL")
            #password = os.environ.get("PASSWORD")
            token  = os.environ.get("GPTTOKEN")
            config = {
                "access_token": token
            }
            chatbot = AsyncChatbot(config=config,conversation_id="4cff500a-e7a5-4faa-b6cc-ae54aa650b96",parent_id="4cff500a-e7a5-4faa-b6cc-ae54aa650b96")
            response = ""
            async for data in chatbot.ask(question):
                response = data["message"]
            await message.channel.send(f"```{response}```")
            
            
            
```

### What should have happened?

.

### Version where the problem happens

Version: 4.1.3
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: e:\.tobias\programmierung\python\installs\lib\site-packages
Requires: httpx, openai, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
For more information check: https://httpstatuses.com/429
test
Ignoring exception in on_message
Traceback (most recent call last):
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\nextcord\client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "E:\.Tobias\Programmierung\Python\Projekte\MiniGamesBot\bot\cogs\Ki stuff.py", line 40, in on_message
    async for data in chatbot.ask(question):
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\revChatGPT\V1.py", line 748, in ask
    self.__check_response(response)
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\revChatGPT\V1.py", line 867, in __check_response
    response.raise_for_status()
  File "E:\.Tobias\Programmierung\Python\Installs\lib\site-packages\httpx\_models.py", line 841, in raise_for_status
    raise HTTPError(message, response=self)
httpx._exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://bypass.churchless.tech/api/conversation
For more information check: https://httpstatuses.com/429
```

**Comment by HumanBot000** [comment]
Note:


If I test the same code with the non async modell it works fine

**Comment by AmreshSinha** [comment]
I guess the IP of the proxy server is banned again just like last week.

**Comment by HumanBot000** [comment]
What can I do?

**Comment by AmreshSinha** [comment]
Wait for the owner. He will fix it.

**Comment by xixixi2000** [comment]
> Wait for the owner. He will fix it. You can also try hosting your own proxy server. https://github.com/acheong08/ChatGPT-Proxy-V4

it's no use, because it's the same with plus account and the normal account now

**Comment by Kooldguy92** [comment]
> This issue is stale because it has been open for 2 days with no activity.

How to fix that issue?

**Comment by MagzhanUnited** [comment]
How to fix issue?

**Comment by HumanBot000** [comment]
I do not know just wait I think
