### ISSUE TITLE
[BUG] Login errors

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#134]
**Describe the bug**
Login error

**Output**
```
 $ python3 -m revChatGPT --debug --text

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
Beginning part four
Error in part four
Status code: 302
Rate limit hit

Login failed
Something went wrong! Please run with --debug to see the error.
Rate limit hit
```

**Additional context**
Service down

**Comment by acheong08** [comment]
More details https://github.com/rawandahmad698/PyChatGPT/issues/38

**Comment by acheong08** [comment]
```
 $ python3 -m revChatGPT --debug --text

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
Beginning part four
Beginning part five
Beginning part six
Beginning part seven
Request went through
Response code is 302
New state found
Beginning part eight
Beginning part nine
SUCCESS
Part eight called
```

**Comment by steegecs** [comment]
I have been having trouble logging in as well. It says I have invalid credentials, but I have checked and double checked my email, password, and session-token. Also, I am not using 3rd part authentication. Might this be related or something else? 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 305, in part_seven
    self.part_eight(old_state=state, new_state=new_state)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 362, in part_eight
    raise Exception("Invalid credentials")
Exception: Invalid credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/mf", line 33, in <module>
    sys.exit(load_entry_point('mindflow', 'console_scripts', 'mf')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steegecs/Desktop/repos/MindFlow/main.py", line 274, in main
    MindFlow()
  File "/Users/steegecs/Desktop/repos/MindFlow/main.py", line 96, in __init__
    getattr(self, args.command)()
  File "/Users/steegecs/Desktop/repos/MindFlow/main.py", line 267, in question
    self._handle_prompt(args, prompt)
  File "/Users/steegecs/Desktop/repos/MindFlow/main.py", line 220, in _handle_prompt
    model = get_chat_gpt()
            ^^^^^^^^^^^^^^
  File "/Users/steegecs/Desktop/repos/MindFlow/mindflow/models/chat_gpt.py", line 19, in get_chat_gpt
    model = Chatbot(config)
            ^^^^^^^^^^^^^^^
  File "/Users/steegecs/Desktop/repos/MindFlow/ChatGPT/src/revChatGPT/revChatGPT.py", line 32, in __init__
    self.refresh_session()
  File "/Users/steegecs/Desktop/repos/MindFlow/ChatGPT/src/revChatGPT/revChatGPT.py", line 223, in refresh_session
    raise exc
  File "/Users/steegecs/Desktop/repos/MindFlow/ChatGPT/src/revChatGPT/revChatGPT.py", line 220, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/Users/steegecs/Desktop/repos/MindFlow/ChatGPT/src/revChatGPT/revChatGPT.py", line 247, in login
    raise exc
  File "/Users/steegecs/Desktop/repos/MindFlow/ChatGPT/src/revChatGPT/revChatGPT.py", line 240, in login
    auth.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin
    self.part_two()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two
    self.part_three(token=csrf_token)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 144, in part_three
    self.part_four(url=url)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 178, in part_four
    self.part_five(state=state)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 216, in part_five
    self.part_six(state=state, captcha=None)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 259, in part_six
    self.part_seven(state=state)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 311, in part_seven
    raise Exception("State not found")
```

**Comment by LuckyHead11** [comment]
Wow the website is down that's very surprising

**Comment by superswan** [comment]
Doesn't give detailed information but can be used to track the status.
https://status.openai.com/

**Comment by LuckyHead11** [comment]
Ok, the website is up now... it should work

**Comment by edmund5** [comment]
E:\local-www\GitHub_Repo\ChatGPT-main>python -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
Beginning part four
Beginning part five
Error in part five
Captcha detected
Login failed
Something went wrong! Please run with --debug to see the error.
Captcha detected``

**Comment by acheong08** [comment]
I don't support captcha yet. Check out https://github.com/rawandahmad698/PyChatGPT for captcha support.

**Comment by Ancestral5ahgor** [comment]
I'm in the same situation

**Comment by alexandreteles** [comment]
> I don't support captcha yet. Check out https://github.com/rawandahmad698/PyChatGPT for captcha support.

Do you plan on supporting this feature? I was hoping I didn't had to submit a PR to either ChatGPT or PyChatGPT so they can support programmatic resolution of captchas (https://github.com/rawandahmad698/PyChatGPT/issues/57), but I'm willing to write the infrastructure as long as most of the captcha authentication part is already dealt with.

**Comment by acheong08** [comment]
The issue with captcha is the image. I can't render it on servers which much of ChatGPT is running on. I plan to support it as an option for users to specify whether they want to solve captcha or not. It is still a WIP

**Comment by acheong08** [comment]
https://github.com/rawandahmad698/PyChatGPT/issues/57#issuecomment-1343274007

This is a valid suggestion but would only work with async.
