### ISSUE TITLE
[Bug]: 502 Bad Gateway in bypass.churchless.tech

### ISSUE THREAD

**Issue by emeralddesignz** [acheong08/ChatGPT#1341]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I was working on my python application with revchatgpt integrated and just a few hours ago I encountered this problem in the cloudflare server both in my application and then when I went to https://bypass.churchless.tech/ , it says that it's a 502 Bad Gateway error.
![image](https://user-images.githubusercontent.com/130757859/232312819-9781549c-79a0-4d27-8637-d299a4de7f00.png)

I thought it would be resolved in a few hours, but to no prevail, it's still like that. Is it something only on my end? Or do you have the same issue? Thanks a lot!

### Steps to reproduce the problem

1. Go to [....](https://bypass.churchless.tech/)
2. Or run your python project with revchatgpt on it and if the server's down there, it should run into a problem.

### What should have happened?

My python application should have worked with AI and generated the text prompts I needed.

### Version where the problem happens

4.21

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Nope.
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 680, in __check_response
    response.raise_for_status()
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://bypass.churchless.tech/api/conversation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\New Movie Recapper\chat.py", line 119, in <module>
    ask_chatGPT(ap)
  File "E:\New Movie Recapper\chat.py", line 24, in ask_chatGPT
    for data in chatbot.ask(ap):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 568, in ask
    yield from self.post_messages(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 525, in post_messages
    yield from self.__send_request(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 376, in __send_request
    self.__check_response(response)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 687, in __check_response
    raise error
revChatGPT.typings.Error: OpenAI: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>bypass.churchless.tech | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">



    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">

              <span class="inline-block">Bad gateway</span>
              <span class="code-label">Error code 502</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2023-04-16 13:02:44 UTC</div>
        </header>

        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Colombo</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">bypass.churchless.tech</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>

            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>

                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>

        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">7b8c9fd8d9e54cb0</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">123.231.126.150</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=bypass.churchless.tech" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

 (code: 502)
```

**Comment by Minry** [comment]
This happened to me in the morning,and i have no idea

**Comment by emeralddesignz** [comment]
> This happened to me in the morning,and i have no idea

Oh, so it's just not me! Hopefully the problem should be resolved soon.

**Comment by DevHaoZi** [comment]
#1336

**Comment by Wanrell** [comment]
Currently having issues with this as well.

**Comment by emeralddesignz** [comment]
What actions should be taken? I have a big project plus a deadline and I really need this to be fixed :/

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`

**Comment by acheong08** [comment]
Keep close watch on releases when stuff like this happens. It tends to be somewhat resolved within a day and fully resolved within a week.

**Comment by emeralddesignz** [comment]
Thank you so much!!
