### ISSUE TITLE
[Bug]: Max retries exceeded with url when typing in input message for revChatGPT.V1

### ISSUE THREAD

**Issue by emeralddesignz** [acheong08/ChatGPT#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I faced a similar issue before with a cloudflare 502 gateway issue. Now I've upgraded the library and it's been hours working properly , but just now I think the new host is down?

### Steps to reproduce the problem

You can't really reproduce the problem, unless you run your revchatgpt application and see it run into a problem.

### What should have happened?

It should generate text prompts.

### Version where the problem happens

Version: 4.2.3

### What Python version are you running this with?

Python 3.10.11

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Nope
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001BC6383E8C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.gateway.do', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BC6383E8C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\New Movie Recapper\chat.py", line 113, in <module>
    ask_chatGPT(ap)
  File "E:\New Movie Recapper\chat.py", line 24, in ask_chatGPT
    for data in chatbot.ask(ap):
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 575, in ask
    yield from self.post_messages(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 530, in post_messages
    yield from self.__send_request(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 375, in __send_request
    response = self.session.post(
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Wishvajith\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.gateway.do', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BC6383E8C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by FriendlyUser** [comment]
I am getting the same issue. was working earlier this morning.

**Comment by seanliu96** [comment]
Same issue.

**Comment by tmlnv** [comment]
Same

**Comment by Walbre** [comment]
Worked fine this morning, the issue appeared when running the script this afternoon.

**Comment by maminiainalaic** [comment]
same

**Comment by gogoods** [comment]
same

**Comment by cyrus-go** [comment]
same error

**Comment by emeralddesignz** [comment]
Gosh~ Anyone got any solutions? I've got a deadline for a revchatgpt project for my client!

**Comment by frorayz** [comment]
+1

**Comment by flymorn** [comment]
Same issue.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/4.2.4

**Comment by acheong08** [comment]
> Gosh~ Anyone got any solutions? I've got a deadline for a revchatgpt project for my client!

Please don't depend on unofficial APIs for commercial stuff. It's quite unstable and subject to OpenAI's takedown requests

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/232655988-d88b0e54-66b1-41e9-a43e-5e778143f5d4.png)

**Comment by emeralddesignz** [comment]
Wait, so I can't keep using the access token anymore?

**Comment by FriendlyUser** [comment]
What does this mean for Chatgpt access going forward?

**Comment by acheong08** [comment]
> Wait, so I can't keep using the access token anymore?

you can and it works

**Comment by acheong08** [comment]
> What does this mean for Chatgpt access going forward?

Upgrade to latest version and it'll work

**Comment by acheong08** [comment]
You can use https://github.com/linweiyuan/go-chatgpt-api to run locally

**Comment by TuqicZ** [comment]
Please try again after upgrading
