### ISSUE TITLE
[Bug]: New endpoint return 500

### ISSUE THREAD

**Issue by Malomalsky** [acheong08/ChatGPT#1346]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```
`Traceback (most recent call last):
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1175, in __check_response
    response.raise_for_status()
  File "C:\Python310\chatgpt\venv\lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://ai.fakeopen.com/api/conversation'
For more information check: https://httpstatuses.com/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\chatgpt\asyncmain.py", line 135, in run
    response = await _ask_fabric(chatbot, item.strip())
  File "C:\Python310\chatgpt\asyncmain.py", line 72, in _ask_fabric
    async for data in bot.ask(item.strip(), timeout=300):
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1012, in ask
    async for msg in self.post_messages(
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 965, in post_messages
    async for msg in self.__send_request(
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 853, in __send_request
    await self.__check_response(response)
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1183, in __check_response
    raise error from e
revChatGPT.typings.Error: OpenAI: Internal Server Error (code: 500)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1175, in __check_response
    response.raise_for_status()
  File "C:\Python310\chatgpt\venv\lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://ai.fakeopen.com/api/conversation'
For more information check: https://httpstatuses.com/500

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\chatgpt\asyncmain.py", line 192, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Python310\chatgpt\asyncmain.py", line 185, in main
    await asyncio.gather(
  File "C:\Python310\chatgpt\asyncmain.py", line 139, in run
    await _ask_fabric(chatbot, INITIAL_PROMPT_NEW)
  File "C:\Python310\chatgpt\asyncmain.py", line 72, in _ask_fabric
    async for data in bot.ask(item.strip(), timeout=300):
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1012, in ask
    async for msg in self.post_messages(
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 965, in post_messages
    async for msg in self.__send_request(
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 853, in __send_request
    await self.__check_response(response)
  File "C:\Python310\chatgpt\venv\lib\site-packages\revChatGPT\V1.py", line 1183, in __check_response
    raise error from e
revChatGPT.typings.Error: OpenAI: Internal Server Error (code: 500)`
```

### Steps to reproduce the problem

Usual usage

### What should have happened?

-

### Version where the problem happens

4.2.4

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by acheong08** [comment]
Your access token is probably expired. Update it from https://chat.openai.com/api/auth/session

**Comment by Malomalsky** [comment]
> Your access token is probably expired. Update it from https://chat.openai.com/api/auth/session

Updated my tokens. It's now turn to 502 and 429

**Comment by acheong08** [comment]
It seems that the public proxy is getting rate limited by OpenAI

**Comment by acheong08** [comment]
If you must, `export CHATGPT_BASE_URL="https://bypass.churchless.tech/"`. I'm not gonna set that as default until I get my own implementation fully stable

**Comment by fresure** [comment]
> If you must, `export CHATGPT_BASE_URL="https://bypass.churchless.tech/"`. I'm not gonna set that as default until I get my own implementation fully stable

大佬加油~

**Comment by gogoods** [comment]
`ConnectionError(MaxRetryError(\"HTTPSConnectionPool(host='ai.fakeopen.com', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9068e51330>: Failed to establish a new connection: [Errno 101] Network is unreachable'))\"))`

@acheong08 the error above always happened in these days, is this same reason?

**Comment by gogoods** [comment]
`export CHATGPT_BASE_URL="https://bypass.churchless.tech/"`

@acheong08 this doesn't work?

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/233036774-a667ee89-bd5f-4cfc-a08d-46a83b69ddd3.png)

**Comment by gogoods** [comment]
> ![image](https://user-images.githubusercontent.com/36258159/233036774-a667ee89-bd5f-4cfc-a08d-46a83b69ddd3.png)

@acheong08 i tried, but that MaxRetryError still sometimes occoured.. not each time.

**Comment by dawhdb** [comment]
> 您的访问指令牌可能已经过期。[从https://chat.openai.com/api/auth/session](https://chat.openai.com/api/auth/session)更新[](https://chat.openai.com/api/auth/session)

这个更新是post请求吗，需要传入什么参数？
