### ISSUE TITLE
[Bug]: RuntimeError: The content for this response was already consumed

### ISSUE THREAD

**Issue by Barbery** [acheong08/ChatGPT#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

call ask function error: 
```
Traceback (most recent call last):
  File "/root/chatgpt/chatQueue.py", line 90, in ask
    for data in chatbot.ask(q,conversation_id,parent_id,timeout):
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 480, in ask
    log.error(response.text)
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 923, in text
    if not self.content:
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 894, in content
    raise RuntimeError("The content for this response was already consumed")
RuntimeError: The content for this response was already consumed
```

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

return result

### Version where the problem happens

Name: revChatGPT
Version: 4.0.11
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.9/dist-packages
Requires: httpx, openai, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:

### What Python version are you running this with?

Python 3.9.16

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/root/chatgpt/chatQueue.py", line 90, in ask
    for data in chatbot.ask(q,conversation_id,parent_id,timeout):
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 480, in ask
    log.error(response.text)
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 923, in text
    if not self.content:
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 894, in content
    raise RuntimeError("The content for this response was already consumed")
RuntimeError: The content for this response was already consumed
```
```


### Additional information

_No response_

**Comment by harryeffinpotter** [comment]
Same issue

**Comment by acheong08** [comment]
Upgrade to https://github.com/acheong08/ChatGPT/releases/tag/4.2.4
