### ISSUE TITLE
[Feature Request]: Add support for browsing (not compatible currently)

### ISSUE THREAD

**Issue by noname01t1** [acheong08/ChatGPT#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

To support the latest model: gpt-4-browsing

### Proposed workflow

Working when "model" is set to "gpt-4-browsing"

### Additional information

Current error:
```
'parts'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/<privacy delete>.py", line <privacy delete>, in ask
    for data in chatbot[i].ask(
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 575, in ask
    yield from self.post_messages(
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 530, in post_messages
    yield from self.__send_request(
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 414, in __send_request
    message: str = line["message"]["content"]["parts"][0]
KeyError: 'parts'
```

If I get enough time, I'll try to submit a PR.

**Comment by acheong08** [comment]
I currently don't have access to browsing and thus can't reverse on my own. Please provide a sample browsing request and the resulting stream. You can find this from F12

**Comment by Erol444** [comment]
Hi @acheong08 ,
So I am not entirely sure what yalls approach is (using openai's official API / using sockets for their chat.openai.com / using browser to navigate there / etc.) but this is the POST request to `https://chat.openai.com/backend-api/conversation` inside the chat.openai.com when you select GPT4 browsing:
```
{
  "action": "next",
  "messages": [
    {
      "id": "aaa23ff3-1dc4-42c7-8e31-5dc9abbed21f",
      "author": { "role": "user" },
      "content": {
        "content_type": "text",
        "parts": [
          "What's the age difference between dua lipa and her boyfriend?"
        ]
      }
    }
  ],
  "parent_message_id": "aaa1f5d0-a18a-4619-95f7-0fc0ecd7b1bf",
  "model": "gpt-4-browsing",
  "timezone_offset_min": -120,
  "history_and_training_disabled": false
}
```
Would that help?

**Comment by acheong08** [comment]
Thanks. That is exactly what I was looking for. Will work on this soon

**Comment by acheong08** [comment]
Can you send the corresponding response?

**Comment by acheong08** [comment]
I have no way of testing it but based on the original issue, the problems seems to be parsing

**Comment by acheong08** [comment]
Even without access to it on the web interface, sending the request got me access (I think)
```json
{"message": {"id": "0826472e-c9e3-498d-93ae-75b9aec7e8ff", "author": {"role": "assistant", "name": null, "metadata": {}}, "create_time": 1684637522.627016, "update_time": null, "content": {"content_type": "text", "parts": ["The latest news about Joe Biden as of May 21, 2023, is mainly centered around the ongoing debt limit negotiations between the White House and House Republicans. Despite the tough talk and intermittent progress, the discussions have yet to yield a definitive solution, which has been a source of concern given the potential consequences of a federal default\u30108\u2020source\u3011\u301010\u2020source\u3011.\n\nBiden attempted to reassure world leaders at a hastily rescheduled meeting of the Quad partnership, which includes the heads of Australia, Japan, and India. He affirmed the United States' intent not to default on its obligations\u30109\u2020source\u3011. Biden also expressed confidence that the U.S. would avoid a catastrophic debt default, describing the talks with congressional Republicans as productive\u301011\u2020source\u3011.\n\nWork requirements for federal aid programs have emerged as a point of contention in these negotiations. Although some in his party have opposed this, Biden has indicated a willingness to consider a possible compromise\u301012\u2020source\u3011. To facilitate the negotiations, Biden and House Speaker Kevin McCarthy have enlisted a select group of negotiators to help forge a deal to increase the nation's borrowing authority and avert potential economic fallout\u301013\u2020source\u3011.\n\nIn order to focus on these critical debt limit discussions, Biden has curtailed his upcoming trip to the Indo-Pacific region, canceling what was to be a historic stop in Papua New Guinea and a visit to Australia for a gathering with fellow Quad leaders\u301014\u2020source\u3011."]}, "status": "finished_successfully", "end_turn": true, "weight": 1.0, "metadata": {"message_type": "next", "model_slug": "gpt-4-browsing", "citations": [{"start_ix": 356, "end_ix": 366, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "Debt limit negotiations between the White House and House Republicans hung over the weekend with tough talk but little action, as President Joe Biden and world leaders kept watch from afar hoping high-stakes discussions would make progress on avoiding a potentially catastrophic federal default", "pub_date": null}}, {"start_ix": 366, "end_ix": 377, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "Debt limit talks between the White House and House Republicans stopped, started and stopped again Friday at the U.S", "pub_date": null}}, {"start_ix": 608, "end_ix": 618, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "President Joe Biden tried to reassure world leaders on Saturday that the United States would not default as he consulted with the heads of Australia, Japan and India in a meeting of the so-called Quad partnership that had been hastily rescheduled because of the debt limit standoff back in Washington", "pub_date": null}}, {"start_ix": 772, "end_ix": 783, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "An optimistic President Joe Biden declared Wednesday he is confident the U.S. will avoid an unprecedented and potentially catastrophic debt default, saying talks with congressional Republicans have been productive", "pub_date": null}}, {"start_ix": 1003, "end_ix": 1014, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "work requirements for federal aid? GOP pushes proposals in debt talksBy MARY CLARE JALONICK May 17, 2023 GMT\n\nWASHINGTON (AP) \u2014 Work requirements for federal aid programs have emerged as a sticking point in ongoing negotiations over raising the nation\u2019s debt ceiling, and President Joe Biden has signaled openness to a possible compromise even as many in his party have balked", "pub_date": null}}, {"start_ix": 1233, "end_ix": 1244, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "President Joe Biden and House Speaker Kevin McCarthy are turning to a select group of negotiators to help work out a deal to increase the nation\u2019s borrowing authority and avoid the economic carnage that could ensue if the U.S", "pub_date": null}}, {"start_ix": 1499, "end_ix": 1510, "metadata": {"title": "apnews.com", "url": "https://apnews.com/hub/joe-biden", "text": "President Joe Biden said Tuesday he's curtailing his upcoming trip to the Indo-Pacific, scrapping what was to be a historic stop in Papua New Guinea as well as a visit to Australia for a gathering with fellow leaders of the so-called Quad partnership so he can focus on debt limit talks in Washington", "pub_date": null}}], "finish_details": {"type": "stop", "stop": "<|diff_marker|>"}}, "recipient": "all"}, "conversation_id": "65453023-2a02-47e0-8cf8-069b06759841", "error": null}
```

**Comment by acheong08** [comment]
Parsing issues come from
```json
{
  "message": {
    "id": "23b01f22-5c70-4e62-b398-0c6f3da28f04",
    "author": {
      "role": "tool",
      "name": "browser",
      "metadata": {}
    },
    "create_time": null,
    "update_time": null,
    "content": {
      "content_type": "tether_browsing_display",
      "result": "",
      "summary": ""
    },
    "status": "finished_successfully",
    "end_turn": null,
    "weight": 0,
    "metadata": {
      "command": "search",
      "status": "running",
      "args": [
        "latest news on Joe Biden"
      ],
      "message_type": "next",
      "model_slug": "gpt-4-browsing"
    },
    "recipient": "all"
  },
  "conversation_id": "65453023-2a02-47e0-8cf8-069b06759841",
  "error": null
}
```

**Comment by acheong08** [comment]
Done
