### ISSUE TITLE
[Bug]:  for V1

### ISSUE THREAD

**Issue by maminiainalaic** [acheong08/ChatGPT#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 660, in __check_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bypass.churchless.tech/conversation

### Steps to reproduce the problem

python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Version: 5.0.0
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You: 
hey

Chatbot: 

### What should have happened?

getting response

### Version where the problem happens

Version: 5.0.3

### What Python version are you running this with?

Python 3.11.2

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 660, in __check_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bypass.churchless.tech/conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1334, in main
    for data in chatbot.post_messages([msg], auto_continue=True):
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 502, in post_messages
    yield from self.__send_request(
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 357, in __send_request
    self.__check_response(response)
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 667, in __check_response
    raise error from ex
revChatGPT.typings.Error: OpenAI: {"error":"Post \"https://chat.openai.com/backend-api/conversation\": socks connect tcp hello.wisnicroyals.academy:19528-\u003echat.openai.com:443: dial tcp 205.185.127.168:19528: connect: connection timed out"} (code: 500)
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1379, in <module>
    main(configure())
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maminiainalaic/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1364, in main
    raise error from exc
revChatGPT.typings.CLIError: command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
```

**Comment by maminiainalaic** [comment]
now i'm getting no response and no error from the chat,
it stays here:
![Screenshot from 2023-05-20 14-45-44](https://github.com/acheong08/ChatGPT/assets/126385570/e12ea043-2e80-4acb-9d42-127d425bf74f)

**Comment by acheong08** [comment]
Temporary downtime perhaps due to bad internet on my server. Test again and it should work
