### ISSUE TITLE
Failed with email/password based authentication.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1452]
The `~/.config/revChatGPT/config.json` is as follows:

```json
{"email": "bgrandstaff9@ramons.site",
"password": "my-passord",
"model": "gpt-3.5-turbo",
"comment":"below are some comments",
"url":"https://platform.openai.com/docs/models/gpt-3-5"
}
```

The error is as follows when calling [V1.py](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V1.py):

```python
werner@X10DAi:~$ revChatGPT 1
/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Version: 5.0.0
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.
Insufficient login details provided!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/__main__.py", line 65, in <module>
    main()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/__main__.py", line 49, in main
    V1.main(V1.configure())
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 1196, in main
    chatbot = Chatbot(
              ^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 177, in __init__
    self.__check_credentials()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 198, in __check_credentials
    self.login()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/revChatGPT/V1.py", line 332, in login
    raise error
revChatGPT.typings.AuthenticationError: Insufficient login details provided!
Please check if your key is correct, maybe it may not be valid
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
```

**Comment by acheong08** [comment]
Looks like the credentials weren't passed in correctly.

My config like this works just fine.

```json
{
	"email":"<my-email>","password":"<my-password>","disable_history":true,"model":"gpt-4"
}
```

**Comment by acheong08** [comment]
> Version: 5.0.0

Your version is very outdated and won't work properly

**Comment by acheong08** [comment]
Please upgrade to at least Version: 6.7.6

**Comment by hongyi-zhao** [comment]
Very good, I can achieve the purpose through the following steps:

The python environment setup:

```python
pyenv shell 3.11.1
pyenv virtualenv ChatGPT
pyenv shell ChatGPT
pip install -U pip
cd ~/Public/repo/github.com/acheong08/ChatGPT.git/
pip install -r requirements.txt
pip install -e .
```

The `~/.config/revChatGPT/config.json`:

```json
{"email":"<my-email>","password":"<my-password>",
"proxy": "socks5h://127.0.0.1:18890",
"disable_history":true,
"model": "gpt-3.5-turbo",
"comment":"below are some comments",
"url":"https://platform.openai.com/docs/models/gpt-3-5",
"issues":"https://github.com/acheong08/ChatGPT/issues/1452#issuecomment-1616702565"
}
```
The testing:

```shell
(ChatGPT) werner@X10DAi:~$ python3 -m revChatGPT --V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Version: 6.7.6
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You: 
Hello.

Chatbot: 
Hello! How can I assist you today?                                                                   

You: 
```

But I still cannot figure out how to find the corresponding to my email as discussed here: 

https://github.com/acheong08/ChatGPT/discussions/1450

**Comment by acheong08** [comment]
Whatever you set your password as. Doesn't work with Google/Microsoft login

**Comment by hongyi-zhao** [comment]
If I'm using Google/Microsoft/Apple login based authentication, then how to set a separate password for the case used here?

![image](https://github.com/acheong08/ChatGPT/assets/11155854/9b239bc8-b38f-4752-8d73-09519610c23b)

**Comment by acheong08** [comment]
You can only use access token in that case. There is no reverse engineered Google/Microsoft/Apple login available
