### ISSUE TITLE
[Bug]: ValueError: PUID is required

### ISSUE THREAD

**Issue by dd4897** [acheong08/ChatGPT#1455]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What happened?

File "D:\python3.10\lib\site-packages\OpenAIAuth.py", line 38, in init
raise ValueError("PUID is required")
ValueError: PUID is required

### Steps to reproduce the problem

https://github.com/logger(is_timed=True)
def login(self) -> None:
"""Login to OpenAI by email and password"""
if not self.config.get("email") and not self.config.get("password"):
log.error("Insufficient login details provided!")
error = t.AuthenticationError("Insufficient login details provided!")
raise error
auth = Authenticator(
email_address=self.config.get("email"),
password=self.config.get("password"),
proxy=self.config.get("proxy"),
)
log.debug("Using authenticator to get access token")
auth.begin()
auth.get_access_token()

    self.set_access_token(auth.access_token)
    
   我改了源码函数的第一行但是我目前会报这个ValueError: PUID is required

### What should have happened?

请问5.0.0版本or 新版本 没有账号密码登录获取access_token的功能了吗？ 我很需要这个功能！

### Version where the problem happens

python 3.10 revGPT 5.0.0 

### What Python version are you running this with?

python3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\yuanlis\Script\test.py", line 61, in <module>
    save_access_token()
  File "E:\yuanlis\Script\test.py", line 25, in save_access_token
    chatbot = Chatbot(
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 177, in __init__
    self.__check_credentials()
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 198, in __check_credentials
    self.login()
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 66, in wrapper
    out = func(*args, **kwargs)
  File "D:\python3.10\lib\site-packages\revChatGPT\V1.py", line 333, in login
    auth = Authenticator(
  File "D:\python3.10\lib\site-packages\OpenAIAuth.py", line 38, in __init__
    raise ValueError("PUID is required")
ValueError: PUID is required

Process finished with exit code 1
```

### Additional information

1

**Comment by acheong08** [comment]
Your version of OpenAIAuth is ancient
