### ISSUE TITLE
[Bug]: access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

### ISSUE THREAD

**Issue by omrahm** [acheong08/ChatGPT#1462]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I use my account's username and password to login from the code, it works fine, but when using another account I made, it gives me this error: 
`access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.`

### Steps to reproduce the problem

```python
from revChatGPT.V1 import Chatbot
chatbot = Chatbot(config={
  "email": "emailhere", "password": "passwordhere" # using my other account's info
})
prompt = "how many beaches does portugal have?"
response = ""
for data in chatbot.ask(
  prompt
):
    response = data["message"]
print(response)
```

### What should have happened?

The response should have been printed

### Version where the problem happens

 6.8.1

### What Python version are you running this with?

3.10.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\aaa.py", line 2, in <module>
    chatbot = Chatbot(config={
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 329, in __init__
    self.__check_credentials()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 378, in __check_credentials
    raise error
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 375, in __check_credentials
    self.login()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 508, in login
    self.set_access_token(auth.get_access_token())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 69, in get_access_token
    return self.__part_two()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 82, in __part_two
    return self.__part_three(code_verifier, url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 97, in __part_three
    return self.__part_four(code_verifier, state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 124, in __part_four
    return self.__part_five(code_verifier, state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 150, in __part_five
    return self.__part_six(code_verifier, location, url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 179, in __part_six
    return self.__get_access_token(code_verifier, resp.headers["Location"])
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth.py", line 221, in __get_access_token
    raise Exception("{}: {}".format(error, error_description))
Exception: access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.
```

**Comment by Kylin93CN** [comment]
i have the same problem with macos, i use access_token instead of account  and the error disapeared

**Comment by masnasri-a** [comment]
same problem

**Comment by hansfzlorenzana** [comment]
Same here.

**Comment by hello2mao** [comment]
See:  https://github.com/pengzhile/pandora/commit/f663d6ecce862e0bd1d8be49893c996ddde521dd

**Comment by gngpp** [comment]
没得救了

**Comment by acheong08** [comment]
> See: [pengzhile/pandora@f663d6e](https://github.com/pengzhile/pandora/commit/f663d6ecce862e0bd1d8be49893c996ddde521dd)

doesn't work

**Comment by acheong08** [comment]
I'll fix when I have time. Got a fever

**Comment by gngpp** [comment]
> I'll fix when I have time. Got a fever

Wishing you good health and a quick bounce back. Get well soon!

**Comment by tmlnv** [comment]
Same with me

**Comment by hello2mao** [comment]
> > See: [pengzhile/pandora@f663d6e](https://github.com/pengzhile/pandora/commit/f663d6ecce862e0bd1d8be49893c996ddde521dd)
> 
> doesn't work

我按照这个修改是生效的。

**Comment by sbrown980** [comment]
Thank you for providing this information. There were some problems I was experiencing with [ChatGPT](https://chatgptdownloads.net/). Since I updated my app, it has been running very smoothly with no issues

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/6.8.2
