### ISSUE TITLE
[Bug]:  https://bypass.churchless.tech/conversation

### ISSUE THREAD

**Issue by digitalboy** [acheong08/ChatGPT#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 870, in __check_response
    response.raise_for_status()
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bypass.churchless.tech/conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 1687, in main
    for data in chatbot.ask(prompt=prompt, auto_continue=True):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 757, in ask
    yield from self.post_messages(
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 710, in post_messages
    yield from self.__send_request(
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 545, in __send_request
    self.__check_response(response)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 877, in __check_response
    raise error from ex
revChatGPT.typings.Error: OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/__main__.py", line 65, in <module>
    main()
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/__main__.py", line 49, in main
    V1.main(V1.configure())
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 1709, in main
    raise error from exc
revChatGPT.typings.CLIError: command line program unknown error

### Steps to reproduce the problem

1. gpt-4
2. type some words to ask GPT
3. bug 

### What should have happened?

conversation should go on

### Version where the problem happens

 Version: 6.8.6

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
Null
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 870, in __check_response
    response.raise_for_status()
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bypass.churchless.tech/conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 1687, in main
    for data in chatbot.ask(prompt=prompt, auto_continue=True):
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 757, in ask
    yield from self.post_messages(
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 710, in post_messages
    yield from self.__send_request(
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 545, in __send_request
    self.__check_response(response)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 877, in __check_response
    raise error from ex
revChatGPT.typings.Error: OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/__main__.py", line 65, in <module>
    main()
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/__main__.py", line 49, in main
    V1.main(V1.configure())
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
  File "/home/ec2-user/beike-autobot/ChatGPTAgent/myenv/lib64/python3.9/site-packages/revChatGPT/V1.py", line 1709, in main
    raise error from exc
revChatGPT.typings.CLIError: command line program unknown error
```

**Comment by yileitu** [comment]
Same here!
