### ISSUE TITLE
[Bug]: Please check that the input is correct, or you can resolve this issue by filing an issue

### ISSUE THREAD

**Issue by Kiyliy** [acheong08/ChatGPT#1489]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

当我请求的时候, 出现了这个错误, 我认为是我的提示词的缘故, 当我将我的提示词换成了简单的"hi" , 工作起来一切正常
当时当我使用一个结构类似于json格式的str, 会出现这个错误
错误日志: (error log:)
""""""""""""""""""""""""""""
Traceback (most recent call last):
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 870, in __check_response    
    response.raise_for_status()
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\requests\models.py", line 1021, in raise_for_status 
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for 
url: https://bypass.churchless.tech/conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\Code_project\Python\reChatGPT\reChatGPT\dev_plugin0.1.py", line 35, in <module>
    for data in chatbot.ask(
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 757, in ask
    yield from self.post_messages(
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 710, in post_messages       
    yield from self.__send_request(
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 545, in __send_request      
    self.__check_response(response)
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 877, in __check_response    
    raise error from ex
revChatGPT.typings.Error: OpenAI: <html>
  <head>
    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;flex-direction:column;gap:2rem;height:100%;justify-content:center;width:100%}@keyframes enlarge-appear{0%{opacity:0;transform:scale(75%) rotate(-90deg)}to{opacity:1;transform:scale(100%) rotate(0deg)}}.logo{color:#8e8ea0}.scale-appear{animation:enlarge-appear .4s ease-out}@media (min-width:768px){.scale-appear{height:48px;width:48px}}.data:empty{display:none}.data{border-radius:5px;color:#8e8ea0;text-align:center}@media (prefers-color-scheme:dark){body{background-color:#343541}.logo{color:#acacbe}}</style>

</head>
  <body>
    <div class="container">
      <div class="logo">
        <svg
          width="41"
          height="41"
          viewBox="0 0 41 41"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          strokeWidth="2"
          class="scale-appear"
        >
          <path
            d="M37.5324 16.8707C37.9808 15.5241 38.1363 14.0974 37.9886 12.6859C37.8409 11.2744 37.3934 9.91076 36.676 8.68622C35.6126 6.83404 33.9882 5.3676 32.0373 4.4985C30.0864 3.62941 
27.9098 3.40259 25.8215 3.85078C24.8796 2.7893 23.7219 1.94125 
22.4257 1.36341C21.1295 0.785575 19.7249 0.491269 18.3058 0.500197C16.1708 0.495044 14.0893 1.16803 12.3614 2.42214C10.6335 3.67624 9.34853 5.44666 8.6917 7.47815C7.30085 7.76286 5.98686 8.3414 4.8377 9.17505C3.68854 10.0087 2.73073 11.0782 2.02839 12.312C0.956464 14.1591 0.498905 16.2988 0.721698 18.4228C0.944492 20.5467 1.83612 22.5449 3.268 24.1293C2.81966 25.4759 2.66413 
26.9026 2.81182 28.3141C2.95951 29.7256 3.40701 31.0892 4.12437 32.3138C5.18791 34.1659 6.8123 35.6322 8.76321 36.5013C10.7141 37.3704 12.8907 37.5973 14.9789 37.1492C15.9208 38.2107 17.0786 39.0587 18.3747 39.6366C19.6709 40.2144 21.0755 40.5087 22.4946 40.4998C24.6307 40.5054 26.7133 39.8321 28.4418 38.5772C30.1704 37.3223 31.4556 35.5506 32.1119 33.5179C33.5027 33.2332 34.8167 32.6547 35.9659 31.821C37.115 30.9874 38.0728 29.9178 38.7752 28.684C39.8458 26.8371 40.3023 24.6979 40.0789 22.5748C39.8556 20.4517 38.9639 18.4544 37.5324 16.8707ZM22.4978 37.8849C20.7443 37.8874 19.0459 37.2733 17.6994 36.1501C17.7601 36.117 17.8666 36.0586 17.936 36.0161L25.9004 31.4156C26.1003 31.3019 26.2663 31.137 26.3813 30.9378C26.4964 30.7386 26.5563 30.5124 26.5549 30.2825V19.0542L29.9213 20.998C29.9389 21.0068 29.9541 21.0198 29.9656 21.0359C29.977 21.052 29.9842 21.0707 29.9867 21.0902V30.3889C29.9842 32.375 29.1946 34.2791 27.7909 35.6841C26.3872 37.0892 24.4838 37.8806 22.4978 37.8849ZM6.39227 31.0064C5.51397 29.4888 5.19742 27.7107 5.49804 25.9832C5.55718 26.0187 
5.66048 26.0818 5.73461 26.1244L13.699 30.7248C13.8975 30.8408 
14.1233 30.902 14.3532 30.902C14.583 30.902 14.8088 30.8408 15.0073 30.7248L24.731 25.1103V28.9979C24.7321 29.0177 24.7283 29.0376 24.7199 29.0556C24.7115 29.0736 24.6988 29.0893 24.6829 29.1012L16.6317 33.7497C14.9096 34.7416 12.8643 35.0097 10.9447 34.4954C9.02506 33.9811 7.38785 32.7263 6.39227 31.0064ZM4.29707 13.6194C5.17156 12.0998 6.55279 10.9364 8.19885 10.3327C8.19885 10.4013 8.19491 10.5228 8.19491 10.6071V19.808C8.19351 20.0378 8.25334 20.2638 8.36823 20.4629C8.48312 20.6619 8.64893 20.8267 8.84863 20.9404L18.5723 26.5542L15.206 28.4979C15.1894 28.5089 15.1703 28.5155 15.1505 28.5173C15.1307 28.5191 15.1107 28.516 15.0924 28.5082L7.04046 23.8557C5.32135 22.8601 4.06716 21.2235 3.55289 19.3046C3.03862 17.3858 3.30624 15.3413 4.29707 13.6194ZM31.955 20.0556L22.2312 14.4411L25.5976 12.4981C25.6142 12.4872 25.6333 12.4805 25.6531 12.4787C25.6729 12.4769 25.6928 12.4801 25.7111 12.4879L33.7631 17.1364C34.9967 17.849 36.0017 18.8982 36.6606 20.1613C37.3194 21.4244 37.6047 22.849 37.4832 24.2684C37.3617 25.6878 36.8382 27.0432 35.9743 28.1759C35.1103 
29.3086 33.9415 30.1717 32.6047 30.6641C32.6047 30.5947 32.6047 30.4733 32.6047 30.3889V21.188C32.6066 20.9586 32.5474 20.7328 32.4332 20.5338C32.319 20.3348 32.154 20.1698 31.955 20.0556ZM35.3055 15.0128C35.2464 14.9765 35.1431 14.9142 35.069 14.8717L27.1045 10.2712C26.906 10.1554 26.6803 10.0943 26.4504 10.0943C26.2206 10.0943 25.9948 10.1554 25.7963 10.2712L16.0726 15.8858V11.9982C16.0715 11.9783 16.0753 11.9585 16.0837 11.9405C16.0921 11.9225 16.1048 11.9068 16.1207 11.8949L24.1719 7.25025C25.4053 6.53903 26.8158 6.19376 28.2383 6.25482C29.6608 6.31589 31.0364 6.78077 32.2044 7.59508C33.3723 8.40939 34.2842 9.53945 34.8334 10.8531C35.3826 12.1667 35.5464 13.6095 35.3055 15.0128ZM14.2424 21.9419L10.8752 19.9981C10.8576 19.9893 10.8423 19.9763 
10.8309 19.9602C10.8195 19.9441 10.8122 19.9254 10.8098 19.9058V10.6071C10.8107 9.18295 11.2173 7.78848 11.9819 6.58696C12.7466 5.38544 13.8377 4.42659 15.1275 3.82264C16.4173 3.21869 17.8524 2.99464 19.2649 3.1767C20.6775 3.35876 22.0089 3.93941 23.1034 4.85067C23.0427 4.88379 22.937 4.94215 22.8668 4.98473L14.9024 9.58517C14.7025 9.69878 14.5366 9.86356 14.4215 10.0626C14.3065 10.2616 14.2466 10.4877 14.2479 10.7175L14.2424 21.9419ZM16.071 17.9991L20.4018 15.4978L24.7325 17.9975V22.9985L20.4018 25.4983L16.071 22.9985V17.9991Z"
            fill="currentColor"
          />
        </svg>
      </div>
      <div class="data"><form id="challenge-form" class="challenge-form"><div id="cf-please-wait"><div id="spinner"><div id="cf-bubbles"><div class="bubbles"></div><div class="bubbles"></div><div class="bubbles"></div></div></div><p id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p><p id="cf-spinner-redirecting" style="display:none">Redirecting...</p></div><noscript id="cf-captcha-bookmark" class="cf-captcha-info"><h1 style="color:#bd2426;">Please turn JavaScript 
on and reload the page.</h1></noscript><div id="no-cookie-warning" class="cookie-warning" style="display:none"><p style="color:#bd2426;">Please enable Cookies and reload the page.</p></div></form><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'chat.openai.com',cType: 'managed',cNounce: '77990',cRay: '7f27e678b9a240a1',cHash: 'f3adea6b44186c2',cUPMDTk: "\/backend-api\/conversation?__cf_chl_tk=Yf9aQ7N3DX6Utn1E1ocH1R2whZPJp2mjqOTkhshavHs-1691331413-0-gaNycGzNE3s",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 1,cTplB: 'cf',cK: "",fa: "/backend-api/conversation?__cf_chl_f_tk=Yf9aQ7N3DX6Utn1E1ocH1R2whZPJp2mjqOTkhshavHs-1691331413-0-gaNycGzNE3s",md: "soM2tUn4Dez5lNoFOIJx.mhv5GGhOAg04JUjt3EoTSo-1691331413-0-ATOajQFcDmpGxD4xmF2FGJJ3K0fCfqEI73zT2U-eZSnenpyyUPF9YZzjRk6voZxGux_km1jcHmMMBGx2g44bbNnR26bk7o9GRr7XB98Mw35zvEkIJZr5e7GYjrOdUgcDI3DrcwzhGxazA0QplXP5wPvx-TWymzTJc3y_Kh3AGhjnK3bOjfhSLLZSDr1YYKVg72QJLRdYbkcoCPdRGc5VF6B675sbk-5snk9gQYy8J1qp1KEs3dJguq2Usq4ShaDwW4jWE0kTW5dMepctpOLivI7C89nog8x1fHeUT3CQ1eHhkGooBH15JKG5Y5xm1AY68iqo1JeagRj9J_ugUQ0DF-1i8SfVkOf1smN2NGmNwJRUIsbuQsJ4UaDDgy13x87xafIbnVP8AbsJkLkreFwmYauCdAUT9_qFV-mBdTMsvA8hY4cKywuslt4YzOEbBOuzd8OkoifKYC5EMGiRDXJ2p1r92I1K4yQfz6PMU4gV1v94h86U9Gg5C6AVFQsAmCsP9dy-YqCy4LM6RjjAgqwvn4O5QehE_EV4vBCTcR6aXmMSwP71iObBxbuRFEeBl9lIn8nsdn5m2JZsT981vagVbpnt1PQEhvCEYOkmCJfO6SKqbiyRFhGWbLI8ccfDc8Uli0hZLZY4VBO3zLScqQSTgVwu6PbnZDyOoP5fV-1bgw5kJcoKGq_fSNLZpAp1sfAX_ejUv_qoQ6hn7rAm6UhLm85wliLvxJ8uRgIKnQ1uc0iLtX-f3blp0ZZfIRfmVmELzMZka09erV0LcEiUde82t_t4748uZTJtOqkLwL9AfBmw_F1whIJuVPj_WRLQVgDTL43OR3sf3K9vMyy2ijxQdsPDJh6uDR198xbHO9Ho3neIoSkGOUxnTUUen-Klkazxm70I3imnauR8TjRpfAF6ucekLTno8HSzswjmAPF0p-Wwher7P23H-LXOcvqP4_29by39Sed8hKZNA7RfsXtoJ0apX0S3ffEx8mvfewU6KgCZtjK9ahJwFhrbo-zmfLAJ2WuFQMnYWoMCciRuhrr5AFgeB5fxZF1eBKCzv0jQy2gsoSZk0KzgUOVr51dzXg2kqr7JhGAhSzjdUyErNcKYnCda7fHjMPOfmfbdW0KksyKifTj_IzEw3IE-pinc2xYxMFjtK-5jYL4uY45xaJeCI-bRwlXmkHqqVsYxOB_MaBOyOZD9D_pjcUSFD4pEnEoTYE9NunLUjcUSHJqPYFsDcK2BohmHMEHhGu6Y-Xdz3Xaaz68Vr1tpZLtTzr5Tde2oBdJ6OXzA1aJaLYyF91HF7B5_-Nd4hT1Ud_byLTb7nzpf_I1BbLMncvGlzi8VmsXC4Fn4Ccwd0VHDyX4U7xUKM4pSRDGMT6tsC5T_JZ06dX5A2-vMV7LU1Q-7ABn_qzxmJ-ZS3iz_n5oDfBL7ZUnS-NMDMP9hClI4B8A4ev-wfvC6pkUJAcW0MfcNuCUGL5OAyiGHv11-n6c6jfaWT7CvQ771brefmdO5LZWKAsoG1GrW7m_NPy9ggKe6dAw_cjOb_J2VKyLIOWdRSSqqRGmtjIghO9CI5Ca4qPZDbUEdBcvPRTEVUDdnmMUq9DJRjRmpm6Uiq00hZHd2_D_uW7r1AC-3cE68J4keeN1lNC8dGP0RAF_OFhVgjkg1bPZna4YKWlUvaKCROzkYVCRljMRCMxLjgpOsIIruts08fLM2orZ0ZGQluin8vjvsvEHrC-qrtUS2oLwf7tCNJItjoX9Sg6RPy7r43lSB8Cjd3IecBW39AsTgAL_FxBpPvCw3yASgir7X-VULRPAayYjbCeboogIW9mYV_2r3YY2YBHk7RLs0vy6N3-lrXYY7KOTi6PXIa8omLHRxFpLAWBGca1dfh0LlHc-xl5qyZBlZw12ea8enjCBde_iDy9j8525wI7Ngy13zWck6LIi3lUnkw5zQ41Udt_SwjyQg8-USMURQw9ZNxlosjKOVrdYf2W_6WyjcMvrFqXCaRT9XMpuasqlPvm5U9xj7p7WiA5zgf_Lq9mGNZCYauu7Vf9Pq5Z98wq_AGotFiyO9LzQf1OQQF4vl2Wpg_HWzXudp6YSGwOMT9OKVtuwqjUviDglaTT0hPoCORf9OJGMt7IfXsG3ENyQWb26EjtsQAyOHE2r-sCEgLTx0_eo_zEPy53utkt4LXHmSqMgjYleMfjiVvDn5dFkH6b7mhGw2uwzD5cFYDaAmH6aDPk0hlBxw7OtYOdpTMQ7tlq5KjwjlAl-U7xY2eUYXadGtM5m7XAfJDL1Fn5T6A86_tb2rBVzBLWINemxaoAc9Zb-oMBuPkes7kNpP4ZMwRaVdJBlF6ljeAPctdu7vYj6OHO3XpR-yIMzUK-p8viNfYCAJscJ2h8PzQO7u3qSkh6hCrKnYfQvp0YxIgerFIDFnHiW5yWpWHaz-YF3mOIYMPf5equmkDFfBQbA1t_p9hwaxTQBZ1X3KXQ4LWvGkzNuYBb2EmidSF84R46lunXr7ggR8dB8MIwujiEHrIgTzDaOKbVUCO2t6zlWWWT_FB2PKneARNVXhopVjNCqfoujlvBSU6dBakycvR4KhuvJr6ly94mdjrqhMaaKAXBXeYr08hM7GBVdZ9wOhqMacIxUcCS5sf84b9tOGa_Fro47e4kfvEwlgnxxebjwAa_jE3MRBOEFVukI4gUU_QxrScEK2hzAxr04m2wHSwv3cr7Ar4yfFk2-jGWvRsVwUuJ_-Pf03VxdgoD4RhYj2I3P0NAL5EEcahKl6cAXbz0zfP4z1Dvi89L4jclZjQTMweTOhxvt9NOAF4AXYGWYxjHz3Fv8xH4IeRJ0m3Ms91nSmOjwlvQIE7SfORZa7UUZ8VPOM_z8SeeY6RkeY-64I8aA5u3F8dKRhgVbHRXA1r1EsVVI-i2HGfJwM0Z5s2n5AEasCUkHJVhWTtbSb1KVhs2_bNDY3ffD52vb7ilOrPxuBHVZlZkTO58uhrN5P5Byv5qQemBexXmtImKMYS3PFmBJiguSRQBgELdGr-67d7a6M2OdZ9Eo38nrblxH6QHe2_DArDxTHPLplKygV05t7NnViydaLgGD1rP7c2RJoNahxDUvt-IhdGrN0MAJqUJv4ev1bEU3NnQ76lrL-tlXDifScRMBg4qK4bVaz2zVuzuq4voT0MCt4LEN3WMCI06JqbuSIkP2vOfq8fn7gu0Z2AR5v6aKI_g-hwtkQOSf8fZZgel6EdgmxkEEIHKmqBmTn_-N4YNAQgolqG1HA1R5Ihs3zPVE6GdCZQF8eR8-pbNwGOhmtKzFAFEfgWvejOhNrb-wgTz1olHixT1J7mxWUDlOOjPlq4ySvkP-epxWK0UFoxabPyUOFku5y92T1QgtwXiKNX20sgFF3Lfg50r-IAvc1lVXuJtO3hHbIzpUvi0y3DKQXaR3564WxeC1YYzvM543V4i1P29ToAzfp-NG1dNs_a50pHrYn6RZXDg2pb4N1Mno5Cq7PzvG767SvQ6idVvEISAjEpOHB2ucHxm01L60rPF_0bLPUXtso2ucAlFTjHwTlA5YIx4wtnjaC3WuY8ie_Z6L9PsKs6dhz0w45IZlboVBar9jsoXZ0uzwVKyqH8zAcr5KQBoJ0X-o9kH6GRRSqQ8Jf6BGVtF1rAt6VuPWuntpzOewLobmwrBiRPfBL0gaX707zXfbLAwu7xcq_PAmQeluzbp9L5dOGAvL4CCsY-98irpDyQx3rO5iMuvotHJHqwBnUqt-kKFafVvRcdnQwq4Mj7N1V_ctNv0LPT84mU0A31jZdLBy2xpYiY4zt_6fvOk3TJqt9xIlKZYiZTqgRtm3rIXx7Jd8LAMGWe5CB7pt_4Itw9jkTDG9u5skIhtqm0VeK5mr-Xtev00uhylxscUBACkWzH7gbvHgXm6M-I6I1z6NYhGmL1cH92MBRvj7nAZVVLFhi9jlZM_K54delY-_JkUCZ48tuukWrfkxYckULFG_83i6q4_1KmeOf_BEFnT9dEOR7IKjex-enlAN19uxLHls52VdE4x79dqngS3an72XMdzyFpAKFksAQqX-LJFqxn9lKIKBIfmnJOfcANVu3NQCOguc69_TzQDuX6zhL8IdUzgVGprqQiRvaQ36lsosB96U3OfVKnnd9S3F1TDZd0ZYC_HlNusPJX0AWPz6iAKdYKYT52xewq2IrdBk9kaa7ZSUksJYWoelAmdWc09N0rQqMkChnkHUvEM7JYEF-KvU0TRStc4QER2tU8xTu9FgK6GVpZQdEUS4KBVFy4ornwdfJbG-ZBhGNRPHi49QJUVALj2HFmJGr_m0MrNF3opxXHIoqVRsx986LFf4xq3ys_bOskym-jVMvU_if96tkp2AxxYTR1hwoazby_r9JEo1zP7be6Lu14x8sPu7Nhx6h0y1yQGOsvGwxTSd74mpWHgzZW9g90OCEYmGwgeknxNuGi7WXlsRWupHXaNoCw_-xxyz0eJF8tuVUmjq6pD1QUzQ6g-T7buRyMLlj56BWDhjUPGDWf8yodZUHD92ctlcymqEPVMeBYHUDgaotpYXi2OnnACtcary1YNIX24DHn_iXeE6rqn2PeB3liY8tIrFWnshvTvvQPbALCojnSMbT_7cURGHt_jBB8-piMW6TUB2MAN-W50Cjfqm8iNxhwdQSumzty4ba_ZSPg-UksTFfsXZ9pbn2xtCGLjDAB5v14YGjUZGeUpaP_M-R8lZxdThndyvZVVF2Esa8ELzh0XsMheMibnjOT3Lk-PUg8Q_Ssx6oRnTskWGxTdfVrH3NpS_KN-dH2soMA3dchb0T7X8D-94Zhi391SrWm9Zp0G6yudMfGHK7uCbG41Eais5fS-7W5i9CHp8IxsEiu14hcI8-DVMtfEABSIcEx95jxuKYA-BbSmesLKVUcB_LDreBBfI_NsOReDrPXXKzUy3CNLdwLQ",cRq: {ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb20vY2hhdC9iYWNrZW5kLXBhaWQvYXBpL2NvbnZlcnNhdGlvbg==',ra: 'TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMTQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMTQuMA==',rm: 'UE9TVA==',d: 'QCoFyl0ROa+3UnE9Vt773ZY7eO8mR3dKb5nzLMbMKIEBWk0lJW5xnKwXxeIMx/6htHUyVv6v3YMpCtg6NOPoNVKtGLv95m6g/lP0PRyG1UsNXE0o07/EtmG89C7M+LR+BS+Kr5ZkhzsqXTQTrhu5EMlxZ/3UT/3BAkFpQHmMdGNq/VdzlvGLY/WR8DnZrEs4EdnJ2BVmjgerMPEOv5vhEbLsHVTtlE+8+8WuHJfN0TmJfgqf9ArJQ9JO9esH4SrxFexC9ST+seD1qq6fAh8MRse9s5ewvQ1ixHK8oXOcEDaeMCBlONLFg93Tb9rv3gxt5XXF2MCHKFvtdIjAoe74MXfZyCtdJ6ecBymf9ZKAjuBIex14EonzpxO2r/Ks/zcDKArQCZHYlQZS/C18e1smFwli3vJkX2FqdSE5noDXHlr8MgvPLl6/NiGPkFOXR/hr0rbnSEUG9dClF6mgKY5odxX6E7t4KJghiM1cbzE4vEx1yhKKlTF/AjaKv1vBo+jxEGzmPYFWUQHYO1kHW6T6wOuaTiADTF1DCrnxQV4of4M=',t: 'MTY5MTMzMTQxMy44NzMwMDA=',cT: Math.floor(Date.now() / 1000),m: 'mGBZpaMyZw00fHQXcpYUBgJ+KCyEs/QzHNzI3gEGsxA=',i1: '6jBCFp9h9q7A5Uf9fBtOxw==',i2: 'MbA8WeRMBcQXiPVHf039mg==',zh: 'iuyN59AGNgeBFFEOPj72EN+xtBfXXvoCyd1dJnIVFAc=',uh: '2bOnWttJE7CWj6VkmurENcdFUnRVOci+2FAZ4DiyLeA=',hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=7f27e678b9a240a1';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/backend-api\/conversation?__cf_chl_rt_tk=Yf9aQ7N3DX6Utn1E1ocH1R2whZPJp2mjqOTkhshavHs-1691331413-0-gaNycGzNE3s" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></div>
    </div>
  <script>!function(){var e=document.createElement("iframe");function t(){var t=e.contentDocument||e.contentWindow.document;if(t){var n=t.createElement("script");n.nonce="",n.innerHTML="window['__CF$cv$params']={r:'79271b319741fa72',m:'sCXwl7Hde_jVE6GIOe0wKz4oMt3Lh8w0Eua1mDgehB0-1675216960-0-AYp1IKwNU5u8yMiuEYyoErcqoHVV4YDI+VMoX7mzAvt9fZ4EOB3++PlEm7wtksX3Xttwni3QWV/tKTeRlCy+/nY6nCAYRHzWlB1zXw1KXyx/+B5lo5mvtnyYfuCVVJEWfwzAUnF4MwJWDszLxIwECgs=',s:[0xb58b3307a5,0x39915b3715],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);",t.getElementsByTagName("head")[0].appendChild(n)}}if(e.height=1,e.width=1,e.style.position="absolute",e.style.top=0,e.style.left=0,e.style.border="none",e.style.visibility="hidden",document.body.appendChild(e),"loading"!==document.readyState)t();else if(window.addEventListener)document.addEventListener("DOMContentLoaded",t);else{var n=document.onreadystatechange||function(){};document.onreadystatechange=function(e){n(e),"loading"!==document.readyState&&(document.onreadystatechange=n,t())}}}();</script></body>
</html>
 (code: 403)
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT

### Steps to reproduce the problem

1.运行这个代码便会出现这个错误
2. 将请求切换到 prompt_test= "hi" 一切正常, 说明是我的提示词的缘故
"""
from revChatGPT.V1 import Chatbot

def echo(str):
    return str

chatbot = Chatbot(config={
  "access_token": "<YOUR_ACCESS_TOKEN>"
})

print("Chatbot: ")
prev_text = ""
User_question = input("User: ")
prompt_test ="hi"
prompt = r"""{
    {"role": "system","content":"You are a function_selector engine,
 you can only selecte one function from the following functions,and cannot interpret or explain user questions:
    ```json
    1.{{webfun.WebSearch(search=YOUR_SEARCH)}}
    2.{{webfun.ReadWeb(IsProxy=bool,url=URL)}}
    3.{{echo(str)}}
    4.{{Translation(text=TEXT)}}
    5.{{AiDrawPrompt()}}
    6.{{QuestionAnswer()}}(default function)
    7.{{CodeInterpret()}}}","""+"""{{"role": "user","content": "select function to assistant user,
please do not explain anything,user question:{0}, select function like {{exampleFunction()}}"}},""".format(User_question)
print(prompt)
print("type(prompt)=",type(prompt))
print("type(prompt_test)=",type(prompt_test))

for data in chatbot.ask(
    prompt_test,
):

    message = data["message"][len(prev_text):]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
print("message=",message)
print("prev_text=",prev_text)
print("data=",data)

    


### What should have happened?

得到ChatGPT的回复

### Version where the problem happens


"""""""""""""
Name: revChatGPT
Version: 6.8.6
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: E:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages
Requires: httpx, openai, OpenAIAuth, prompt-toolkit, requests, rich, tiktoken
Required-by
""""""""""""""

### What Python version are you running this with?

Python : 3.11.4

### What is your operating system ?

_No response_

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Chatbot: 
User: hi
{
    {"role": "system","content":"You are a function_selector engine,
 you can only selecte one function from the following functions,and cannot interpret or explain user questions:
    
    1.{{webfun.WebSearch(search=YOUR_SEARCH)}}
    2.{{webfun.ReadWeb(IsProxy=bool,url=URL)}}
    3.{{echo(str)}}
    4.{{Translation(text=TEXT)}}
    5.{{AiDrawPrompt()}}
    6.{{QuestionAnswer()}}(default function)
    7.{{CodeInterpret()}}}",{"role": "user","content": "select 
function to assistant user,
please do not explain anything,user question:hi, select function like {exampleFunction()}"},
type(prompt)= <class 'str'>
type(prompt_test)= <class 'str'>
Traceback (most recent call last):
  File "e:\Code_project\Python\reChatGPT\venv_reChatGPT\Lib\site-packages\revChatGPT\V1.py", line 870, in __check_response    
    response.raise_for_status()
```

**Comment by Kiyliy** [comment]
我修改了我的User_question, 于是出现了使用英文提问可以, 使用中文提问不行的情况
User_question = input("User: ")
prompt = r"""{
    {"role": "system","content":"You are a function_selector engine,
 you can only selecte one function from the following functions,and cannot interpret or explain user questions:
    ```json
    1.{{webfun.WebSearch(search=YOUR_SEARCH)}}
    2.{{webfun.ReadWeb(IsProxy=bool,url=URL)}}
    3.{{echo(str)}}
    4.{{Translation(text=TEXT)}}
    5.{{AiDrawPrompt()}}
    6.{{QuestionAnswer()}}(default function)
    7.{{CodeInterpret()}}}",{{"role": "user","content": "select function to assistant user,
please do not explain anything,user question:"""+f"{{{{\"{User_question}\"}}}}"+""" select function like {{exampleFunction()}}"}}"""

**Comment by Kiyliy** [comment]
我又做了更多的测试, 并略微修改了一下提示词, 我确信这是一个bug:
你们可以尝试下面的代码, 会发现无论如何都会报错, 但是当我在提示词的末尾, """}}select function, 添加一个空格, 变成""" }}select function, 这个代码就会变成下面的情况
1. "英文" : 正常, 示例: "hi"
2. "中文: error ,示例: "你好"
3. 中文+英文 ,正常 , 示例: 你好 hi
4. 英文+ 中文, error, 示例, hi 你好
"""""""""""""


from revChatGPT.V1 import Chatbot

def echo(str):
    return str

chatbot = Chatbot(config={
  "access_token": "token"
})

print("Chatbot: ")
prev_text = ""
User_question = input("User: ")
prompt_test ="hi"
prompt = r"""{
    {"role": "system","content":"You are a function_selector engine,
 you can only selecte one function from the following functions,and cannot interpret or explain user questions:
    ```json
    1.{{webfun.WebSearch(search=YOUR_SEARCH)}}
    2.{{webfun.ReadWeb(IsProxy=bool,url=URL)}}
    3.{{echo(str)}}
    4.{{Translation(text=TEXT)}}
    5.{{AiDrawPrompt()}}
    6.{{QuestionAnswer()}}(default function)
    7.{{CodeInterpret()}}}",{{"role": "user","content": "select function to assistant user,
please do not explain anything,user question:{{"""+f"{User_question}"+"""}}select function like {{exampleFunction()}}"}}"""
print(prompt)
print("type(prompt)=",type(prompt))
print("type(prompt_test)=",type(prompt_test))

for data in chatbot.ask(
    prompt,
):

    message = data["message"][len(prev_text):]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
print("message=",message)
print("prev_text=",prev_text)
print("data=",data)
""""""""""""
