### ISSUE TITLE
[BUG] Exception 'Not a JSON response' occured when creating with 'conversation_id' parameter 

### ISSUE THREAD

**Issue by Paulkm2006** [acheong08/ChatGPT#177]
**Describe the bug**
When you pass the non-empty 'conversation_id' to create a chatbot, it won't work when sending a request.

**To Reproduce**
```
>>> from revChatGPT.revChatGPT import Chatbot
>>> chatbot = Chatbot({"session_token":gpt_token}, conversation_id=None)
>>> chatbot.get_chat_response("hello",output="text")
{'message': 'Hello! How can I help you today?', 'conversation_id': 'e7e5e751-****-****-****-00cb6dd*****', 'parent_id': '7962b8b4-****-****-****-3acfec1*****'}
```
Above is how I got a conversation id.
Next, when I tried to re-use the id, the following error occured:
```
>>> chatbot = Chatbot({"session_token":gpt_token}, conversation_id='e7e5e751-****-****-****-00cb6dd*****') 
>>> chatbot.get_chat_response("hello",output="text")
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 164, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 171, in get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\uer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 221, in get_chat_response
    return self.get_chat_text(data)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 180, in get_chat_text
    raise Exception("Not a JSON response") from exc2
Exception: Not a JSON response
```
I've tried multiple times, but eventually they came back the same.

**Expected behavior**
To work just like not passing conversation_id

**Environment (please complete the following information):**

Already up to date
 - OS: Windows 11
 - Python version: 3.10.9
 - ChatGPT Version: 0.0.33.4
 - OpenAI Version: 0.0.4

**Comment by acheong08** [comment]
Conversation ID doesn't work without a valid parent ID from the same conversation.

**Comment by acheong08** [comment]
We need better documentation

**Comment by Harry-Jing** [comment]
I think many people met this problem before, including me

**Comment by Harry-Jing** [comment]
I made I new pull request that allow you can init with both parent_id and conversation_id. #179

**Comment by misaka-20002** [comment]
btw how to init with both parent_id and conversation_id?
Just like chatbot = Chatbot(config, conversation_id=cvid,parent_id=pid)
or did I do it wrong

**Comment by acheong08** [comment]
yes

**Comment by misaka-20002** [comment]
kinda hard to integrate into my bot :(

**Comment by acheong08** [comment]
You can set the parent_id afterwards by doing `chatbot.parent_id = new_parent_id`

**Comment by acheong08** [comment]
Same for the conversation id

**Comment by Paulkm2006** [comment]
Too many requests?? I only queried once to get a conversation_id then the second time it showed up like this

```
>>> chatbot = Chatbot({"session_token":gpt_token}, conversation_id='8d342e3a-****-****-****-3043129*****', debug=True)
Debugger enabled on OpenAIAuth
>>> chatbot.get_chat_response("hi",output="text")
Incorrect response from OpenAI API
{'detail': 'Too many requests, please slow down'}
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 164, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 171, in get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 221, in get_chat_response
    return self.get_chat_text(data)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10\LocalCache\local-packages\Python310\site-packages\revChatGPT\revChatGPT.py", line 180, in get_chat_text
    raise Exception("Not a JSON response") from exc2
Exception: Not a JSON response
```

I tried to add parameter 'parent_id', but it didn't work at the very beginning.

```
>>> chatbot = Chatbot({"session_token":gpt_token}, conversation_id='8d342e3a-****-****-****-3043129*****', parent_id='bae81eec-****-****-****-509f5a9*****', debug=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Chatbot.__init__() got an unexpected keyword argument 'parent_id'
```

**Comment by acheong08** [comment]
You might need to update. Parent ID changes were only added in the last few hours

**Comment by acheong08** [comment]
> Too many requests?? I only queried once to get a conversation_id then the second time it showed up like this

OpenAI is being very finicky today

**Comment by Paulkm2006** [comment]
Oh it succeded after I defined parent_id later
```
Exception: Not a JSON response
>>> chatbot.parent_id = 'bae81eec-****-****-****-509f5a9*****'
>>> chatbot.get_chat_response("hello",output="text")
{'message': "Hi there! Is there anything specific you would like to talk about or ask me? I'm here to help with any questions you might have. Just let me know how I can help.", 'conversation_id': '8d342e3a-****-****-****-3043129*****', 'parent_id': 'c4eafa53-****-****-****-9ff2ac6*****'}
```
