### ISSUE TITLE
[BUG] wrong response code 403

### ISSUE THREAD

**Issue by pardeike** [acheong08/ChatGPT#260]
**Describe the bug**
I am using a project that has a dependency on this repo. The bot works fine but just an hour ago I started to get the following error:

```
% python3 main.py
Traceback (most recent call last):
  File "/Users/ap/Projects/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/Users/ap/Projects/chatGPT-discord-bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/Users/ap/Projects/chatGPT-discord-bot/src/responses.py", line 36, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 89, in __init__
    self.refresh_session()
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 285, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```
Seems like it's related to revChatGPT but I am not sure. I did make sure that my session token was fresh.

**To Reproduce**
1. Clone https://github.com/cevr/chatgpt-discord and follow the instructions
2. Starting the program will fail with the error mentioned.

**Output**
In the correct directory, run `python3 -m revChatGPT --debug`:
```
% python3 -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Invalid status code: 403
Something went wrong! Please run with --debug to see the error.
Wrong response code
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: Python 3.10.8
 - ChatGPT Version: 0.0.38.6
 - OpenAI Version: 0.0.6

**Comment by michelleyin96** [comment]
same

**Comment by greengeckowizard** [comment]
I'm also having same issue

**Comment by acheong08** [comment]
Closing in favor of https://github.com/acheong08/ChatGPT/issues/261
