### ISSUE TITLE
Why is the socks proxy not supported?

### ISSUE THREAD

**Issue by zer0days404** [acheong08/ChatGPT#268]

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/261

**Comment by LNoving** [comment]
> #261

I met this issue, too. I was using an Ubuntu desktop. This occurs after successfully logging in. 
`Traceback (most recent call last):
  File "/root/Desktop/chatgpt-mirai-qq-bot/bot.py", line 18, in <module>
    import chatbot
  File "/root/Desktop/chatgpt-mirai-qq-bot/chatbot.py", line 15, in <module>
    bot = AsyncChatbot({}, conversation_id=None)
  File "/root/miniconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 110, in __init__
    self.refresh_session()
  File "/root/miniconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 285, in refresh_session
    s = httpx.Client()
  File "/root/miniconda3/lib/python3.9/site-packages/httpx/_client.py", line 677, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/root/miniconda3/lib/python3.9/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
  File "/root/miniconda3/lib/python3.9/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/root/miniconda3/lib/python3.9/site-packages/httpx/_config.py", line 330, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:8686/')
`
