### ISSUE TITLE
[BUG] json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)

### ISSUE THREAD

**Issue by yfq512** [acheong08/ChatGPT#270]
**Environment :**

 - OS: Linux
 - Python version: python -V 3.7.11
 - ChatGPT Version: revChatGPT==0.0.38.7
 - OpenAI Version: OpenAIAuth==0.0.6

**python code: **
```
from revChatGPT.revChatGPT import Chatbot

config = {
    # "email": "<YOUR_EMAIL>",
    # "password": "<YOUR_PASSWORD>"#,
    "Authorization": "***……"
    # "session_token": "", # Deprecated. Use only if you encounter captcha with email/password
    # "proxy": "<HTTP/HTTPS_PROXY>"
}

chatbot = Chatbot(config, conversation_id=None)
print('chatbot init success!')

response = chatbot.get_chat_response("how are you", output="text")
print(response) 
```
**output: **
```
chatbot init success!
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    response = chatbot.get_chat_response("how are you", output="text")
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 547, in get_chat_response
    return asyncio.run(coroutine_object)
  File "/opt/conda/envs/py37/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/py37/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 255, in get_chat_response
    return await self.__get_chat_text(data)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 211, in __get_chat_text
    response = json.loads(response)
  File "/opt/conda/envs/py37/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/py37/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/py37/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

plese help me!

**Comment by ITerydh** [comment]
me too

**Comment by yfq512** [comment]
> me too

你用的是 session_token 还是 accessToken？我上周五用的 session_token 可以跑通，现在用 session_token 不能初始化成功，用accessToken 能初始化成功，但是代码执行就会报错

**Comment by ITerydh** [comment]
> 



> > me too
> 
> 你用的是 session_token 还是 accessToken？我上周五用的 session_token 可以跑通，现在用 session_token 不能初始化成功，用accessToken 能初始化成功，但是代码执行就会报错
> 
> 用 CLI use 的方式，仍就失败

用的session_token，别上周，这个代码一天一个变化QAQ，应该是昨天晚上就寄了，昨天晚上新代码就不管用了，今天早上就家里cf_clearance

**Comment by acheong08** [comment]
Closed in favor of https://github.com/acheong08/ChatGPT/issues/261
