### ISSUE TITLE
[BUG] Failed to refresh session

### ISSUE THREAD

**Issue by jackielics** [acheong08/ChatGPT#302]
```
Traceback (most recent call last):
  File "g:\Browser\speech_realtime_api-master\python-realtime-asr\chatGPT.py", line 12, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "C:\Users\Jackie r9k7\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\revChatGPT.py", line 100, in __init__
    self.refresh_session()
  File "C:\Users\Jackie r9k7\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\revChatGPT.py", line 311, in refresh_session
    self.refresh_session()
  File "C:\Users\Jackie r9k7\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\revChatGPT.py", line 342, in refresh_session
    raise Exception("Failed to refresh session")
Exception: Failed to refresh session
```

---------------------------------------------------------------------------------
I've repeated many times for a while.Is it because chatGPT server's capacity?

**Comment by emilekm2142** [comment]
i got the same error on 0.0.42.1

**Comment by jackielics** [comment]
我已收到，谢谢

**Comment by jackielics** [comment]
> i got the same error on 0.0.42.1

After a few hours ,it went well eventually.
It just happens time to time and really disturbing.
Hope someone work for it.
By the way ,`my config contains "session_token" only`
Is it because of it?

**Comment by acheong08** [comment]
Update to https://github.com/acheong08/ChatGPT/releases/tag/0.0.43 and delete your `config.json`
