### ISSUE TITLE
[BUG] TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by njfm0001** [acheong08/ChatGPT#303]
I have just installed the latest version. Using the code from the wikis and after inserting the session token, I get this error _TypeError: argument of type 'NoneType' is not iterable_ in:

`chatbot = Chatbot(config, conversation_id=None)`

**Comment by ccemoji** [comment]
Give me complete error information, and then maybe I can help you solve your problem. I also encountered the same error

**Comment by yestinl** [comment]
Spawning browser...
Traceback (most recent call last):
  File "d:\project\chatGPT\ChatGPT\src\revChatGPT\demo.py", line 7, in <module>
    }, conversation_id=1, parent_id=1) # You can start a custom conversation
  File "D:\Anaconda3\lib\site-packages\revchatgpt-1.2.2-py3.7.egg\revChatGPT\Unofficial.py", line 72, in __init__
    self.__email_login()
  File "D:\Anaconda3\lib\site-packages\revchatgpt-1.2.2-py3.7.egg\revChatGPT\Unofficial.py", line 473, in __email_login
    browser_executable_path=self.config.get("browser_exec_path"),
  File "D:\Anaconda3\lib\site-packages\undetected_chromedriver-3.4.6-py3.7.egg\undetected_chromedriver\__init__.py", line 426, in __init__
    close_fds=IS_POSIX,
  File "D:\Anaconda3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 1100, in _execute_child
    args = list2cmdline(args)
  File "D:\Anaconda3\lib\subprocess.py", line 511, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
@njfm0001 @ccemoji Did you fix it? I also encountered the same error.
