### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by RizkyNugroho666** [acheong08/ChatGPT#316]
i tried to run it on Replit and this happens

future: <Task finished name='Task-2' coro=<Connection.run() done, defined at /home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:240> exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 247, in run
    await self._transport.connect()
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_transport.py", line 132, in connect
    raise exc
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/driver/playwright.sh'
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import bot
  File "/home/runner/chatgpt1ntrovert/bot.py", line 2, in <module>
    import responses
  File "/home/runner/chatgpt1ntrovert/responses.py", line 8, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 110, in __init__
    self.refresh_session()
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 283, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 357, in get_cf_cookies
    async with async_playwright() as p:
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/async_api/_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 247, in run
    await self._transport.connect()
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_transport.py", line 132, in connect
    raise exc
  File "/home/runner/chatgpt1ntrovert/venv/lib/python3.8/site-packages/playwright/_impl/_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/runner/chatgpt1ntrovert/venv/lib

**Comment by Harry-Jing** [comment]
make sure you have desktop environment,
if not you can use` Xvfb` to emulate a desktop environment on linux.
