### ISSUE TITLE
[BUG] list index out of range

### ISSUE THREAD

**Issue by emilekm2142** [acheong08/ChatGPT#319]
After login in with session token and calling 
```.get_chat_response("hello there", output="text")```
 I get
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 211, in __get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/user/Documents/languageAssist/untitled/main.py", line 42, in chat
    response = chatbots[0][data["id"]].get_chat_response(data["message"], output="text")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 541, in get_chat_response
    return asyncio.run(coroutine_object)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 261, in get_chat_response
    return await self.__get_chat_text(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 215, in __get_chat_text
    raise Exception("Incorrect response from OpenAI API") from exc
Exception: Incorrect response from OpenAI API

```

**Comment by emilekm2142** [comment]
chatGPT is not down rn

**Comment by emilekm2142** [comment]
nvm, just dont provide conversation_id as an optional argument
