### ISSUE TITLE
[BUG]can't login 

### ISSUE THREAD

**Issue by cingtiye** [acheong08/ChatGPT#335]
i run the response_test.py,but the page stopped at the login page and it didn't move on any more.

**Comment by acheong08** [comment]
You need to log in manually

**Comment by cingtiye** [comment]
how can i force the program open chrome instead of other search engines?

**Comment by cingtiye** [comment]
chromium

**Comment by acheong08** [comment]
> chromium

Oh. I use Chromium as my default rather than Chrome so I thought they were the same. I'm not sure how to switch the default browser. I will look into the code later

**Comment by cingtiye** [comment]
The window suddenly flashes back, and the following error occurs:

```
D:\Anaconda\python.exe C:/Users/xx/Desktop/xxx/tests/response_test.py
Debugger enabled on OpenAIAuth
LtdAnfmgiiBy0rs1MMlt1b6OI.tGH4WXOcRqQkuqqBE-1671008011-0-1-3622e120.40c8e26f.6123bec0-250
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Error: [Errno 0] Error
Traceback (most recent call last):
  File "C:/Users/cingti/Desktop/xxx/tests/response_test.py", line 17, in test_response
    bot = Chatbot(config=config, debug=True)
  File "D:\Anaconda\lib\site-packages\revChatGPT\revChatGPT.py", line 116, in __init__
    self.refresh_session()
  File "D:\Anaconda\lib\site-packages\revChatGPT\revChatGPT.py", line 314, in refresh_session
    response = s.get(
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 755, in get
    return self.request(
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 600, in request
    return self.send(
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "D:\Anaconda\lib\site-packages\httpx\_client.py", line 714, in send_single_request
    ) = transport.request(
  File "D:\Anaconda\lib\site-packages\httpcore\_sync\http_proxy.py", line 110, in request
    return self._tunnel_request(
  File "D:\Anaconda\lib\site-packages\httpcore\_sync\http_proxy.py", line 191, in _tunnel_request
    proxy_response = proxy_connection.request(
  File "D:\Anaconda\lib\site-packages\httpcore\_sync\connection.py", line 65, in request
    self.socket = self._open_socket(timeout)
  File "D:\Anaconda\lib\site-packages\httpcore\_sync\connection.py", line 85, in _open_socket
    return self.backend.open_tcp_stream(
  File "D:\Anaconda\lib\site-packages\httpcore\_backends\sync.py", line 139, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "D:\Anaconda\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Anaconda\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ConnectError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/xx/Desktop/huangziyi7/tests/response_test.py", line 34, in <module>
    test_response()
  File "C:/Users/xx/Desktop/huangziyi7/tests/response_test.py", line 32, in test_response
    assert False
AssertionError
```

**Comment by acheong08** [comment]
> Anaconda

Virtual environments are known to cause issues
