### ISSUE TITLE
AttributeError: module 'attr' has no attribute 'frozen'

### ISSUE THREAD

**Issue by ZRHann** [acheong08/ChatGPT#344]
Why did the simple code run normally on windows (python39), but encounter an error on ubuntu (python38)? It seems that there is a problem when importing AsyncChatbot.

**Here is the code**
```python
from revChatGPT.revChatGPT import AsyncChatbot as Chatbot
import asyncio
config = {
            # "email": (my email),
            # "password": (my password),
            # Deprecated. Use only if you encounter captcha with email/password
            # "proxy": "<HTTP/HTTPS_PROXY>"
            "session_token": "",
            # "cf_clearance": "",
            # "user_agent": "",
        }
with open("session_token.txt", "r") as f:
    config["session_token"] = f.read()

print(config)
chatbot = Chatbot(config)
print("connected")


async def f1(msg):
    res = await chatbot.get_chat_response(msg, output="stream")
    async for r in res:
        print(r["message"])


async def main():
    while True:
        msg = input()
        await f1(msg)

asyncio.run(main())
```

**and the error** 
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from revChatGPT.revChatGPT import AsyncChatbot as Chatbot
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 14, in <module>
    from playwright.async_api import async_playwright
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 24, in <module>
    from pyee import EventEmitter
  File "/usr/local/lib/python3.8/dist-packages/pyee/__init__.py", line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "/usr/local/lib/python3.8/dist-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/usr/local/lib/python3.8/dist-packages/trio/__init__.py", line 76, in <module>
    from ._dtls import DTLSEndpoint, DTLSChannel
  File "/usr/local/lib/python3.8/dist-packages/trio/_dtls.py", line 136, in <module>
    @attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'
```

**Comment by acheong08** [comment]
The repo currently only supports 3.10 officially. Any other version is out of scope.
