### ISSUE TITLE
 list index out of range --- in second response

### ISSUE THREAD

**Issue by hbchen121** [acheong08/ChatGPT#359]
My robot is init like this
```
class GPT_Robot(object):
    def __init__(self, name='ChatGPT', conversation_id=None):
        self.chatbot = Chatbot(config, conversation_id=conversation_id)
        self.chatbot.reset_chat()  # Forgets conversation
        self.chatbot.refresh_session()  # Uses the session_token to get a new bearer token
        self.first_interact = True
        self.name = name
```
When I first run `resp = self.chatbot.get_chat_response(prompt)`, it success.

But I second run it, then 
```
Traceback (most recent call last):                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 211, in __get_chat_text                            
    response = response.text.splitlines()[-4]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bots/chatGPT/gpt_robot.py", line 75, in <module>
    robot.interactive()
  File "bots/chatGPT/gpt_robot.py", line 55, in interactive
    rep = self.send(action)
  File "bots/chatGPT/gpt_robot.py", line 40, in send
    resp = self.chatbot.get_chat_response(prompt)  # Sends a request to the API and returns the response by OpenAI
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 553, in get_chat_response
    return asyncio.run(coroutine_object)
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/usr/local/lib/python3.8/dist-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step 
    result = coro.send(None)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 265, in get_chat_response
File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 215, in __get_chat_text
    raise Exception("Incorrect response from OpenAI API") from exc
Exception: Incorrect response from OpenAI API
```

Can someone can help me?

**Comment by acheong08** [comment]
The same error is happening on their website. It's a universal cloudflare issue

**Comment by hbchen121** [comment]
> 

Can this problem be solved now?

**Comment by acheong08** [comment]
No. Got to wait for OpenAI to fix it

**Comment by hbchen121** [comment]
I got it, thanks for your answer.
