### ISSUE TITLE
Complementing the answer with each iteration

### ISSUE THREAD

**Issue by Bainky** [acheong08/ChatGPT#371]
How about making the output of the ChatGPT response "dynamic" so that the ask function can be placed in a for in loop and output the augmented ChatGPT response on each iteration. I suppose, I think this can be done through yield with sending get requests indicating message_id

**Comment by acheong08** [comment]
Could you give more details? I don't really understand what you're proposing.

As for streaming responses, I will need to modify the tls_client to support it

**Comment by Bainky** [comment]
That's what I mean
https://user-images.githubusercontent.com/61879874/209655208-ec73eb70-afd7-4b15-9974-f29de8d33233.mp4

**Comment by acheong08** [comment]
Ah. That was possible with the old library. I am still working to bring streaming support to tls_client

**Comment by Bainky** [comment]
Thanks for your work, I'll be waiting

**Comment by Liu-Angelo** [comment]
Spawning browser...
Traceback (most recent call last):
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 404, in get_cf_cookies
    browser_executable_path=self.config.get("browser_exec_path")
  File "/usr/local/lib/python3.6/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_cdp_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatgpt_app.py", line 10, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 416, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by Liu-Angelo** [comment]
Spawning browser...
Traceback (most recent call last):
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 404, in get_cf_cookies
    browser_executable_path=self.config.get("browser_exec_path")
  File "/usr/local/lib/python3.6/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_cdp_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatgpt_app.py", line 10, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/data/chatgpt/bin/revChatGPT/ChatGPT.py", line 416, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
run error ...

**Comment by acheong08** [comment]
@Liu-Angelo Open a new issue.

**Comment by luckcul** [comment]
The streaming-mode in the old library is very useful ! And I look forward to the mode in this library~

**Comment by acheong08** [comment]
Might not be possible. Too much work to rewrite the requests library

**Comment by alramalho** [comment]
This would be really interesting. Did you consider using `fastAPI` instead of `flask`? It has built in HTTP streaming support

**Comment by acheong08** [comment]
It won't work either way because the base library (tls_client) doesn't support streaming
