### ISSUE TITLE
[BUG]Clearance refreshing

### ISSUE THREAD

**Issue by belkahorry** [acheong08/ChatGPT#374]
**Describe the bug**
Clearance refreshing...

**To Reproduce**
Log in chatgpt and manually copy session token, following wiki Setup

**Expected behavior**

**Output**
```
Traceback (most recent call last):
  File "D:\tools\gpttools\chatgptapidemo.py", line 12, in <module>
    chatbot = Chatbot(
  File "D:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\revChatGPT\ChatGPT.py", line 35, in __init__
    self.refresh_session()
  File "D:\ProgramData\Anaconda3\envs\chatgpt\lib\site-packages\revChatGPT\ChatGPT.py", line 99, in refresh_session
    raise Exception("Clearance refreshing...")
Exception: Clearance refreshing...
```

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: Win10
 - Python version: 3.10.8
 - ChatGPT Version: 0.0.47.1
 - OpenAI Version: not required

**Additional context**
System proxy

**Comment by acheong08** [comment]
I forgot to add the loop in init. Fixing that now

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/0.0.47.2
