### ISSUE TITLE
Proxy not applied to browser

### ISSUE THREAD

**Issue by vegaviazhang** [acheong08/ChatGPT#377]
**Describe the bug**
I run the `python -m revChatGPT`, the chrome repeated opening and closing. And the command line show the following log

```log
(vega) E:\b_individial\a_github\b_chatgpt_api\ChatGPT>pip list |find "revChatGPT"
WARNING: Ignoring invalid distribution -ip (d:\a_software_dev\e_anaconda3\envs\vega\lib\site-packages)
revChatGPT                0.0.46
WARNING: Ignoring invalid distribution -ip (d:\a_software_dev\e_anaconda3\envs\vega\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\a_software_dev\e_anaconda3\envs\vega\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\a_software_dev\e_anaconda3\envs\vega\lib\site-packages)

(vega) E:\b_individial\a_github\b_chatgpt_api\ChatGPT>python -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Browser spawned.
Waiting for cookies...
Found cookie: cf_clearance=7yPMIcwOQMbeyLomlmx0q6EoLQ2.tUSICs6gV2FiMSk-1672193148-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
Browser spawned.
Waiting for cookies...
Found cookie: cf_clearance=Tuyb9zE3Skh_W9eV93mu9ABPVZuI0O39V2adxOr7uvk-1672193157-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
Browser spawned.
Waiting for cookies...
Found cookie: cf_clearance=rWu_sDhWk9j6xqg0u6tOUT9rGZFtIZE4LBH3VfgtyKU-1672193168-0-1-7b1c7250.701e828d.93b2cead-160;
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE533E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/210348d2d3289defac02a757c4d9d1b1/se/log
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE4D1430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/210348d2d3289defac02a757c4d9d1b1/se/log
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
Spawning browser...
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
Found cookie: cf_clearance=Tm84oe4g7lGccxrjpkWfjviI_pzsibpYr012FCyQWZs-1672193187-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
Found cookie: cf_clearance=QO3kiCZq5yHyBRyQ6e4K74FbeQO9J0_rQ_4YZaw41.s-1672193196-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
Found cookie: cf_clearance=iFpQlNtlzQAOci8iSxNVHwg23o7mSCdWfbiFl1gXTew-1672193207-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE53DA90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/aaa0a6c2db0a67acdd54d80735466e6e/se/log
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE55F5E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/aaa0a6c2db0a67acdd54d80735466e6e/se/log
Found cookie: cf_clearance=H3e6wsc3gWB3v8Rt_zUB4MMMOIQA9hJVZjpJg.IIL48-1672193220-0-1-7b1c7250.701e828d.93b2cead-160;
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE55D670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/aaa0a6c2db0a67acdd54d80735466e6e/se/log
Spawning browser...
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE55F6D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9b420b5f7370f391ab418acae87e0d6/se/log
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE55D910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9b420b5f7370f391ab418acae87e0d6/se/log
Found cookie: cf_clearance=YJv71ZLkY7jn6lGsIuPkZjqQxQ_1kGOmIdVKEhZ4nhs-1672193233-0-1-7b1c7250.701e828d.93b2cead-160;
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE564D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9b420b5f7370f391ab418acae87e0d6/se/log
Spawning browser...
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE559460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7f8d4f2e74b041a8a364769a9919956/se/log
Browser spawned.
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE782070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7f8d4f2e74b041a8a364769a9919956/se/log
Found cookie: cf_clearance=4kpIeqvaBstGkPQqB2BXWZHVBrvjoiUeHixHV650uMo-1672193243-0-1-7b1c7250.701e828d.93b2cead-160;
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE78E340>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7f8d4f2e74b041a8a364769a9919956/se/log
Spawning browser...
Browser spawned.
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE782610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fbdada49557587179ed5daf07052caf4/se/log
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE79F3D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fbdada49557587179ed5daf07052caf4/se/log
Found cookie: cf_clearance=K8g6gjTo7aU.tQefkHOruQApOd8hSYq7Zet5egDhD6M-1672193255-0-1-7b1c7250.701e828d.93b2cead-160;
Spawning browser...
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE78E070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fbdada49557587179ed5daf07052caf4/se/log
Browser spawned.
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE78ED30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/6c1b2f210b78d47e49b5c27ae7c1d7a9/se/log
Waiting for cookies...
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000266AE7B47F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/6c1b2f210b78d47e49b5c27ae7c1d7a9/se/log
Found cookie: cf_clearance=oWj3rvCT4THci8j2oeaWjRjWWePJxDlp.iTp5ls5314-1672193265-0-1-7b1c7250.701e828d.93b2cead-160;
```

**Comment by DiamondDemon669** [comment]
Try asking chatGPT

**Comment by acheong08** [comment]
haha.

One issue: You might want to update. I suppressed useless warnings and improved cookie logic

**Comment by acheong08** [comment]
Also note that most virtual environments prevent the driver from connecting to Chrome properly. Make sure you run it without conda or venv

**Comment by vegaviazhang** [comment]
> Also note that most virtual environments prevent the driver from connecting to Chrome properly. Make sure you run it without conda or venv

OK, thanks，I will try it later when I come home.

**Comment by ishaan-jaff** [comment]
Are you able to connect to ChatGPT through your Chrome browser? - [Clerkie] (https://clerkie.co/)

**Comment by acheong08** [comment]
Remember to update. There has been numerous improvements by @skippyyy around the browser

**Comment by vegaviazhang** [comment]
> Are you able to connect to ChatGPT through your Chrome browser? - [Clerkie](https://clerkie.co/)

Connect to ChatGPT use the chrome brower opened by python program or opened by myself.

The route use the chrome opened by mysql is OK, and I can connect to ChatGPT

**Comment by acheong08** [comment]
It might be an issue in the previous version where the cf_clearance isn't stored properly. Try updating `pip3 install --upgrade revChatGPT`. If it still doesn't work with session tokens, email/password & Microsoft login is now supported.

**Comment by vegaviazhang** [comment]
OK, I have a try now.

**Comment by Freshball** [comment]
Same Chrome problem by using 0.0.45 & 0.0.47.2, running with windows 11.

**Comment by acheong08** [comment]
Refactoring for browser was done in https://github.com/acheong08/ChatGPT/releases/tag/0.0.48

**Comment by skippyyy** [comment]
Do you have a VPN enabled, system proxy or kill-switch of any sort?

**Comment by vegaviazhang** [comment]
> Refactoring for browser was done in https://github.com/acheong08/ChatGPT/releases/tag/0.0.48
> 
> If that doesn't work, I will need to spin up a VM and test it there


1.I don't use conda and update package to 0.0.48.
2.Using the method by `session_token`.

Doesn't work. 0.0

```log
E:\b_individial\a_github\b_chatgpt_api\ChatGPT>pip list |find "revChatGPT"
revChatGPT              0.0.48

E:\b_individial\a_github\b_chatgpt_api\ChatGPT>

E:\b_individial\a_github\b_chatgpt_api\ChatGPT>python -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Traceback (most recent call last):
  File "D:\a_software_dev\python_3_8_10\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\a_software_dev\python_3_8_10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\__main__.py", line 114, in <module>
    main()
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\__main__.py", line 110, in main
    chatGPT_main(configure())
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\__main__.py", line 45, in chatGPT_main
    chatbot = Chatbot(config)
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\ChatGPT.py", line 83, in __init__
    self.refresh_session()
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\ChatGPT.py", line 145, in refresh_session
    self.get_cf_cookies()
  File "D:\a_software_dev\python_3_8_10\lib\site-packages\revChatGPT\ChatGPT.py", line 403, in get_cf_cookies
    sleep(5)
KeyboardInterrupt
```

**Comment by vegaviazhang** [comment]
Prepare to use method by `Email/Password Login Authentication:`,
But I don't know the meaning of the `captcha"`

**Comment by acheong08** [comment]
> Prepare to use method by `Email/Password Login Authentication:`, But I don't know the meaning of the `captcha"`

Captcha is 2captcha token, You can either pay for a token or find a leaked one online (unethical)

**Comment by skippyyy** [comment]
I think the issue is that you're getting a 403 on refresh_session() and thus recursively calling get_cf_cookies() since it's inside a while loop. As to why this is happening i'm not sure exactly. 

Can you try git cloning or forking the repo locally and adding print statements for debugging purposes? Like  add a print(self.session.headers) on line 145 in ChatGPT.py, could give us a hint as to why this is occuring.

**Comment by vegaviazhang** [comment]
> 

<font color=red size=12>**Success**</font>
The previous problem doesn't appear,  the reason probably as follows.
1.I remove the `proxy` config in config.json.
2.add a `Global VPN`.

So the output comes.

**Comment by acheong08** [comment]
Seems to be a bug with proxies. The issue seems to be that proxies aren't applied to the browser. I will fix that

**Comment by vegaviazhang** [comment]
Thanks  for your project. and thanks to all the people who helped me to solve this.
