### ISSUE TITLE
Solved: MacOS chromedriver issues

### ISSUE THREAD

**Issue by sinneo2022** [acheong08/ChatGPT#380]
**Describe the bug**
I use the access_token authentication method, but get this error

**To Reproduce**
1. python3 -m revChatGPT 

**Output**

```
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 401, in get_cf_cookies
    driver = uc.Chrome(
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 242, in __init__
    patcher.auto()
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 114, in <module>
    main()
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 110, in main
    chatGPT_main(configure())
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 45, in chatGPT_main
    chatbot = Chatbot(config)
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/Users/user54/Projects/python-chatGPT/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 416, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: MacOS
 - Python version: Python 3.9.5
 - ChatGPT Version: 0.0.48.1
 - OpenAI Version: `pip3 show OpenAIAuth`

**Comment by acheong08** [comment]
You are using a proxy that doesn't support HTTPS.

**Comment by acheong08** [comment]
A global VPN works best: https://vpn.fail/

**Comment by sinneo2022** [comment]
No proxy or VPN is being used

**Comment by acheong08** [comment]
Ok. I'll check it out

**Comment by acheong08** [comment]
```
This error message indicates that there was a problem verifying the SSL certificate of the server that you are trying to connect to. SSL (Secure Sockets Layer) is a protocol that is used to establish secure communication channels between client and server. When you make a request to a server using SSL, the server presents a certificate to the client to prove its identity. The client then verifies the certificate to ensure that it is valid and issued by a trusted certificate authority (CA).

If the certificate cannot be verified, it is possible that the certificate has expired, or that it was issued by an untrusted CA. In either case, the client will raise an URLError with the message "certificate verify failed" to indicate that the SSL connection cannot be established.

To fix this error, you will need to determine the root cause of the certificate verification failure. Here are a few potential solutions:

Check the system date and time on your machine to ensure that it is accurate. If the system date and time are incorrect, it can cause certificate verification to fail.

Check the certificate chain for the server to ensure that it is valid and complete. If the certificate chain is incomplete or contains invalid certificates, it will cause the verification to fail.
```

**Comment by acheong08** [comment]
Try again a few times and make sure you can get to the website normally via the browser.

**Comment by acheong08** [comment]
Your system administrator or country could have blocked the chat.openai.com website

**Comment by sinneo2022** [comment]
I have both Brave and Chrome browsers installed on my computer. How do I know which one is used?

**Comment by acheong08** [comment]
Chrome is used by default. You can set which one is used manually via the config: https://github.com/acheong08/ChatGPT/wiki/Setup#config-options-optional

**Comment by acheong08** [comment]
Another possible issue is that your browser disallows the driver from controlling it.

**Comment by sinneo2022** [comment]
Yes, the issue was with the driver. 

So, I have installed the driver with` brew install --cask chromedriver`
The driver has been installed to the `/usr/local/bin/chromedriver`
Then I manually opened the driver with Finder and accepted the exception 

In the config.json I set up the driver path

```json
{
  "session_token": ".....",
    "driver_exec_path": "/usr/local/bin/chromedriver"
}
```

python3 -m revChatGPT --debug
Success!

**Comment by acheong08** [comment]
I will add `brew install --cask chromedriver` and `"driver_exec_path": "/usr/local/bin/chromedriver"` to the docs

**Comment by sinneo2022** [comment]
Is it possible to pass the optional driver's path to the constructor in the code?

```python
from revChatGPT.ChatGPT import Chatbot

chatbot = Chatbot({
  "session_token": "<YOUR_TOKEN>"
}, conversation_id=None, parent_id=None) # You can start a custom conversation
```

**Comment by acheong08** [comment]
Yes.

```python
from revChatGPT.ChatGPT import Chatbot

chatbot = Chatbot({
  "session_token": "<YOUR_TOKEN>",
  "driver_exec_path": "/usr/local/bin/chromedriver"
}) 
```

**Comment by sinneo2022** [comment]
Thanks!

**Comment by acheong08** [comment]
The config and dict are exactly the same. Options work both ways

**Comment by PeggyFan** [comment]
I upgraded to version 109 for my Chrome browser, but I'm still seeing the same error. I also pip installed the latest version. I can't find the `config.json` file that everyone's referencing to- it's not in the repo?

**Comment by acheong08** [comment]
@PeggyFan You need to make your own config. Make sure your token is up to date and that you aren't using a http proxy.

**Comment by spcoughlin** [comment]
I am getting this error using m1 mac, chrome 109 and chromedriver 109, after following all of the mac specific steps:

```
(venv) seancoughlin@Seans-MacBook-Air-2 ChatGPT2Midi % python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Traceback (most recent call last):
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 269, in microsoft_login
    driver = uc.Chrome(
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /opt/homebrew/bin/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 114, in <module>
    main()
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 110, in main
    chatGPT_main(configure())
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/__main__.py", line 45, in chatGPT_main
    chatbot = Chatbot(config)
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 64, in __init__
    self.microsoft_login()
  File "/Users/seancoughlin/PycharmProject/ChatGPT2Midi/venv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 334, in microsoft_login
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by RamishRasool14** [comment]
how did you get browser exec path in chrome in m1? @sinneo2022

**Comment by sjoon2455** [comment]
> how did you get browser exec path in chrome in m1? @sinneo2022

If you installed using homebrew, you would find in /opt/homebrew/bin/chromedriver
