### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JunMagic88** [acheong08/ChatGPT#407]
**Describe the bug**

Traceback (most recent call last):
  File "/Users/raywjtang/Documents/Hax0r/UsefulPython/03.GetSummaries.py", line 12, in <module>
    chatbot = Chatbot({
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/ChatGPT.py", line 416, in get_cf_cookies
    driver.quit()
    ^^^^^^
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
**To Reproduce**

Just running the script will produce this error. It was working fine until today

**Expected behavior**
Opens chrome and captures Cloudflare cookie

**Comment by acheong08** [comment]
Same issue as https://github.com/acheong08/ChatGPT/issues/381
