### ISSUE TITLE
[BUG] cannot load 'tls-client-x86.dylib'

### ISSUE THREAD

**Issue by zhayujie** [acheong08/ChatGPT#427]
**Describe the bug**

I get an os error when I run `python3 -m revChatGPT` in macOS, it shows `cannot load 'tls-client-x86.dylib'`.

**To Reproduce**

python3 -m revChatGPT  (i tried python3.8, 3.9 and 3.10).

**Expected behavior**

Run successfully.

**Output**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/__main__.py", line 5, in <module>
    from revChatGPT.ChatGPT import Chatbot
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 4, in <module>
    import tls_client_for_chatGPT as tls_client
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/sessions.py", line 1, in <module>
    from .cffi import request
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/dependencies/tls-client-x86.dylib, 6): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/dependencies/tls-client-x86.dylib: cannot load 'tls-client-x86.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client_for_chatGPT/dependencies/tls-client-x86.dylib: cannot load 'tls-client-x86.dylib' (load command 0x80000034 is unknown)
```

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade revChatGPT`
 - OS: MacOS, High Sierra (10.13.4)
 - Python version:  3.8.10, 3.9.5, 3.10.5
 - ChatGPT Version:  0.0.48.3

**Additional context**

**Comment by jackyzyaq** [comment]
os:13.0.1 (22A400)
python:3.8.7
chromedriver:108.0.5359.71
我用上面的版本能正常跑起来，不过一直出现 
Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.

可能还是没绕过Cloudflare...
![image](https://user-images.githubusercontent.com/26595866/211152774-8112e567-3290-4abe-8c4d-2f5cd778ae5b.png)

**Comment by acheong08** [comment]
> OS: MacOS, High Sierra (10.13.4)

Only supports Big Sur and above.

**Comment by acheong08** [comment]
@jackyzyaq Open another issue for that
