### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 109, but i'm using chrome 109

### ISSUE THREAD

**Issue by nithinreddyy** [acheong08/ChatGPT#454]
Below is the code i'm using

```
from revChatGPT.ChatGPT import Chatbot

chatbot = Chatbot({
  "session_token": "<%7B%22distinct_id%22%3A%20%22user-RlDMW2MYFxZFcUpbomPmZ09q%22%2C%22%24device_id%22%3A%20%22180b1be6fdd58f-00600a7c261ff9-17333273-144000-180b1be6fdeac6%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24search_engine%22%3A%20%22google%22%2C%22%24user_id%22%3A%20%22user-RlDMW2MYFxZFcUpbomPmZ09q%22%7D>"
}, conversation_id=None, parent_id=None) # You can start a custom conversation

response = chatbot.ask("Hello", conversation_id=None, parent_id=None)

# You can specify custom conversation and
# parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)

print(response)
```

It's returning the error as below

```
Spawning browser...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\revChatGPT\ChatGPT.py", line 479, in get_cf_cookies
    driver = uc.Chrome(
  File "C:\ProgramData\Anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 693, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:63837
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 108.0.5359.125
Stacktrace:
Backtrace:
	(No symbol) [0x00456643]
	(No symbol) [0x003EBE21]
	(No symbol) [0x002EDA9D]
	(No symbol) [0x00312911]
	(No symbol) [0x0030A9D4]
	(No symbol) [0x0030A7B1]
	(No symbol) [0x00346917]
	(No symbol) [0x0034655C]
	(No symbol) [0x0033FB76]
	(No symbol) [0x003149C1]
	(No symbol) [0x00315E5D]
	GetHandleVerifier [0x006CA142+2497106]
	GetHandleVerifier [0x006F85D3+2686691]
	GetHandleVerifier [0x006FBB9C+2700460]
	GetHandleVerifier [0x00503B10+635936]
	(No symbol) [0x003F4A1F]
	(No symbol) [0x003FA418]
	(No symbol) [0x003FA505]
	(No symbol) [0x0040508B]
	BaseThreadInitThunk [0x7644FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77DE7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77DE7A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/NITHIN/Downloads/New/ChatGPT/main.py", line 3, in <module>
    chatbot = Chatbot({
  File "C:\ProgramData\Anaconda3\lib\site-packages\revChatGPT\ChatGPT.py", line 81, in __init__
    self.get_cf_cookies()
  File "C:\ProgramData\Anaconda3\lib\site-packages\revChatGPT\ChatGPT.py", line 494, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

Process finished with exit code 1
```

But i'm using chrome 109 version itself, python 3.8.5 version and revChatGPT 0.1.1 version

![image](https://user-images.githubusercontent.com/56256685/211760509-518c8798-9b76-40a2-a69f-7c0aea43a761.png)

Can anyone please help me with this

**Comment by MirrorCY** [comment]
same issue here.

**Comment by acheong08** [comment]
It uses 108 by default. You might need to downgrade your chromedriver

**Comment by MirrorCY** [comment]
> It uses 108 by default. You might need to downgrade your chromedriver

chrome version is `版本 108.0.5359.125（正式版本） （64 位）`

**Comment by acheong08** [comment]
Chrome and chromedriver has to be the same version. Check what version each of them are at.
(especially the chromedriver)

**Comment by MirrorCY** [comment]
logs
```
Waiting for captcha to be solved...
Captcha solved successfully!
Spawning browser...
Traceback (most recent call last):
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\ChatGPT.py", line 376, in email_login
    driver = uc.Chrome(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 431, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__       
    super().__init__(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__    
    super().__init__(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__      
    self.start_session(capabilities, browser_profile)
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 693, in start_session    
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session 
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute       
    self.error_handler.check_response(response)
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50516
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 108.0.5359.125
Stacktrace:
Backtrace:
        (No symbol) [0x00C96643]
        (No symbol) [0x00C2BE21]
        (No symbol) [0x00B2DA9D]
        (No symbol) [0x00B52911]
        (No symbol) [0x00B4A9D4]
        (No symbol) [0x00B4A7B1]
        (No symbol) [0x00B86917]
        (No symbol) [0x00B8655C]
        (No symbol) [0x00B7FB76]
        (No symbol) [0x00B549C1]
        (No symbol) [0x00B55E5D]
        GetHandleVerifier [0x00F0A142+2497106]
        GetHandleVerifier [0x00F385D3+2686691]
        GetHandleVerifier [0x00F3BB9C+2700460]
        GetHandleVerifier [0x00D43B10+635936]
        (No symbol) [0x00C34A1F]
        (No symbol) [0x00C3A418]
        (No symbol) [0x00C3A505]
        (No symbol) [0x00C4508B]
        BaseThreadInitThunk [0x772900F9+25]
        RtlGetAppContainerNamedObjectPath [0x77547BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77547B8E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\42\Desktop\111\8002.py", line 8, in <module>
    chatbot = Chatbot(
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\ChatGPT.py", line 69, in __init__
    self.email_login(self.solve_captcha())
  File "C:\Users\42\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\ChatGPT.py", line 450, in email_login
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by MirrorCY** [comment]
> Chrome and chromedriver has to be the same version. Check what version each of them are at.

oh i see it

**Comment by zx2592** [comment]
same issue here，chrome and Chromedriver are both 109

**Comment by acheong08** [comment]
Downgrade to 108

**Comment by nicermak** [comment]
update your revchatgpt or selenium, and try it.
