### ISSUE TITLE
[BUG]selenium.common.exceptions.TimeoutException

### ISSUE THREAD

**Issue by hhhaaaa** [acheong08/ChatGPT#494]
**Description**                                                          
D:\wechat-bot\RevChatApi>python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...
Waiting for captcha to be solved...
[92mCaptcha solved successfully![0m
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\__main__.py", line 120, in <m
odule>
    main()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\__main__.py", line 116, in ma
in
    chatGPT_main(configure())
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\__main__.py", line 51, in cha
tGPT_main
    chatbot = Chatbot(config)
              ^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\ChatGPT.py", line 66, in __in
it__
    self.email_login(self.solve_captcha())
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\ChatGPT.py", line 406, in ema
il_login
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", lin
e 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x00E86643]
        (No symbol) [0x00E1BE21]
        (No symbol) [0x00D1DA9D]
        (No symbol) [0x00D51342]
        (No symbol) [0x00D5147B]
        (No symbol) [0x00D88DC2]
        (No symbol) [0x00D6FDC4]
        (No symbol) [0x00D86B09]
        (No symbol) [0x00D6FB76]
        (No symbol) [0x00D449C1]
        (No symbol) [0x00D45E5D]
        GetHandleVerifier [0x010FA142+2497106]
        GetHandleVerifier [0x011285D3+2686691]
        GetHandleVerifier [0x0112BB9C+2700460]
        GetHandleVerifier [0x00F33B10+635936]
        (No symbol) [0x00E24A1F]
        (No symbol) [0x00E2A418]
        (No symbol) [0x00E2A505]
        (No symbol) [0x00E3508B]
        BaseThreadInitThunk [0x75C9FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x772F7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x772F7B8E+238]

**Expected behavior**                                 

**Output**                                                                 
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**                                                                                         
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: python -V
 - ChatGPT Version: pip3 show revChatGPT

**Additional context**

**Comment by hhhaaaa** [comment]
Environment
Python 3.11.1
ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172})
Chrome版本 109.0.5414.120（正式版本） （64 位）
