### ISSUE TITLE
[BUG] Fail to install revChatGPT with error "No module named aiohttp"

### ISSUE THREAD

**Issue by unique94** [acheong08/ChatGPT#507]
ubuntu 22.04.1 LTS
python 3.10.6
pip 22.0.2

Exceptions below.
=====================
chatgpt@chatGPT:~$ pip3 install --upgrade revChatGPT
Defaulting to user installation because normal site-packages is not writeable
Collecting revChatGPT
  Using cached revChatGPT-1.0.10-py3-none-any.whl (21 kB)
Collecting tiktoken
  Using cached tiktoken-0.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting openai
  Using cached openai-0.26.4.tar.gz (55 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 804, in parse_config_files
          parse_configuration(
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 158, in parse_configuration
          meta.parse()
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 498, in parse
          section_parser_method(section_options)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 469, in parse_section
          self[name] = value
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 222, in __setitem__
          value = parser(value)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 599, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "/usr/lib/python3/dist-packages/setuptools/config.py", line 422, in _parse_attr
          module = importlib.import_module(module_name)
        File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/__init__.py", line 9, in <module>
          from openai.api_resources import (
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/__init__.py", line 1, in <module>
          from openai.api_resources.completion import Completion  # noqa: F401
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/completion.py", line 4, in <module>
          from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/abstract/__init__.py", line 3, in <module>
          from openai.api_resources.abstract.api_resource import APIResource
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_resources/abstract/api_resource.py", line 4, in <module>
          from openai import api_requestor, error, util
        File "/tmp/pip-install-os9w2pel/openai_1a4aaa1e7916424bb0f95ed72fc3eb8b/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

=====================

While the aiohttp is installed.
chatgpt@chatGPT:~$ pip3 show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /home/chatgpt/.local/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:

**Comment by acheong08** [comment]
I have the exact same configurations and versions as you. No idea why this is happening

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by acheong08** [comment]
https://github.com/aio-libs/aiohttp/issues/843
https://stackoverflow.com/questions/45093047/aiohttp-module-import-error

**Comment by unique94** [comment]
It seems something wrong when installing pip. It works when using `python3.10 -m pip install xxx'

**Comment by ioneliabuzatu** [comment]
encountering the same problem. I agree with @Mrpichan

**Comment by acheong08** [comment]
> It seems something wrong when installing pip. It works when using `python3.10 -m pip install xxx'

^ This seems to be the solution. Make sure your version of python is well defined

**Comment by wengchaoxi** [comment]
I have also encountered such problems, which may be caused by the pip not being upgraded to the latest.

`pip3 install --upgrade pip`
`pip3 install revChatGPT`

Successfully installed.

**Comment by acheong08** [comment]
I also got this issue on a VPS. Using `venv` solved it
