### ISSUE TITLE
The required dependencies of the project

### ISSUE THREAD

**Issue by QiuZiXian** [acheong08/ChatGPT#516]
I try to run the project（1.0.11） on the enviroment (win10+python3.9)
but it missing some required dependencies (like tls-client,undetected-chromedriver, twocaptcha)
can generate all required dependencies of the project to requirement.txt? thanks!

**Comment by acheong08** [comment]
It's stated in the new README. 
To install unofficial API: `pip3 install --upgrade revChatGPT[unofficial]`

**Comment by Manamama** [comment]
Even after doing this (or installing these dependencies by hand, in a "dirty" Ubuntu), I am getting: 

`python3 -m revChatGPT`
:
```
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press enter twice to submit your question.

No config file found.
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/codespace/.python/current/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/__main__.py", line 122, in <module>
    main()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/__main__.py", line 118, in main
    chatGPT_main(configure())
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/__main__.py", line 44, in configure
    raise Exception("No config file found.")
Exception: No config file found.
```

OfficialChatGPT works fine from the start. 

While we are at it: 
```
Spawning browser...
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 626, in get_cf_cookies
    driver = uc.Chrome(
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 411, in __init__
    browser = subprocess.Popen(
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/python/3.10.4/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/codespaces-blank/Downloads/talkrev.py", line 3, in <module>
    chatbot = Chatbot({
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 91, in __init__
    self.get_cf_cookies()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 646, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

in a virgin Github codespace, but I can live with that.

**Comment by acheong08** [comment]
> Exception: No config file found.

If you're using the unofficial version, you need to create the config as specified in https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by acheong08** [comment]
> TypeError: expected str, bytes or os.PathLike object, not NoneType

You have a bad configuration. Please remove any keys that aren't defined or not necessary

**Comment by acheong08** [comment]
Please use the official version though

**Comment by Manamama** [comment]
I think I got [it](https://github.com/acheong08/ChatGPT/wiki/Setup), especially after reading [this](https://github.com/acheong08/ChatGPT/issues/531). 
Still, it would be too involved on e.g. a virgin Github codespace: one would need to install the GUI, chrome etc. , if I get it right. 

(BTW, kudos and thanks for accepting my LI invite ;)

**Comment by acheong08** [comment]
> Still, it would be too involved on e.g. a virgin Github codespace: one would need to install the GUI, chrome etc. , if I get it right.

Yes. This is why I recommend the Official API. No browsers and also free. Simultaneous requests also allowed

**Comment by Manamama** [comment]
Thanks, all clear now: the official OfficialChatGPT has been working fine both on local notebook and virgin boxes: 
```
gh codespace ssh
gcloud cloud-shell ssh
```
etc.
