### ISSUE TITLE
KeyError: 'Authorization'

### ISSUE THREAD

**Issue by LucaJaich** [acheong08/ChatGPT#52]
I was trying a simple example:

```python
from revChatGPT.revChatGPT import Chatbot
config = {
    "email": "...",
    "password": "..."
}

chatbot = Chatbot(config, conversation_id=None)
chatbot.reset_chat()
chatbot.refresh_session()
resp = chatbot.get_chat_response("hey", output="text")
print(resp)
```

and got

```
Traceback (most recent call last):
  File "C:\Users\Luca\Documents\garbage\test_chatgpt_api.py", line 9, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "C:\Users\Luca\Documents\garbage\ChatGPT\src\revChatGPT\revChatGPT.py", line 18, in __init__
    self.refresh_headers()
  File "C:\Users\Luca\Documents\garbage\ChatGPT\src\revChatGPT\revChatGPT.py", line 26, in refresh_headers
    if self.config['Authorization'] == None:
KeyError: 'Authorization'
```

I cloned the repo and changed [this](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py#L25) line to fix it:
```python
if self.config.get('Authorization') == None
```

I can create a PR if it helps.

Thanks for everything and for this amazing repo :)

**Comment by acheong08** [comment]
Thanks. I am fixing it. Should be pushed within a minute

**Comment by acheong08** [comment]
Fixed. Should be fine with `pip3 install revChatGPT --upgrade`
