### ISSUE TITLE
Is there any sample code for asynchronous calls?

### ISSUE THREAD

**Issue by nowindnowave** [acheong08/ChatGPT#558]
I always have problems implementing：
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

System: centos
python: 3.10
Version: Official API (Browserless)
Response length: Response length is in range
Streaming: no
revChatGPT: 1.1.4

Code: Copied example code referenced by
     async_chatbot = AsyncChatbot(api_key="xxx")
     loop = asyncio. get_event_loop()
     tasks = [
             async_chatbot.ask("xxx1?"),
             async_chatbot.ask("xxx2?"),
             ]
     loop.run_until_complete(asyncio.wait(tasks))

**Comment by nowindnowave** [comment]
Just learning asynchronous, not yet familiar with

**Comment by acheong08** [comment]
> SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

This is a network issue. Are you in an area that spoofs DNS or bans certain domains?

**Comment by acheong08** [comment]
```python
from revChatGPT.Official import AsyncChatbot
import asyncio

async def main():
    bot = AsyncChatbot(api_key="sk-...")
    return await bot.ask("Hello World")

if __name__ == "__main__":
    print(asyncio.run(main()))
```

**Comment by nowindnowave** [comment]
I use the synchronous chatbot.ask to reply normally, and I just tried the example you gave and the same report:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1097, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1127, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 588, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/test.py", line 13, in <module>
    print(asyncio.run(main()))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/test.py", line 10, in main
    return await bot.ask("Hello World")
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 215, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Official.py", line 196, in _get_completion
    return await openai.Completion.acreate(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 301, in arequest
    result = await self.arequest_raw(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 605, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by acheong08** [comment]
OpenAI is blocked on your network. Are you in China?

**Comment by nowindnowave** [comment]
I can reply normally with chatbot.ask. I just switched regions and can use it synchronously, but the same error is reported asynchronously.

**Comment by nowindnowave** [comment]
India and the United States can be used synchronously, but the same error is reported asynchronously

**Comment by acheong08** [comment]
That is interesting. Might be a bug with `aiohttp`. I don't have a fix because I can't replicate

**Comment by nowindnowave** [comment]
I have upgraded OpenSSL 1.1.1d when using python3.10. I don’t know if it has anything to do with this

**Comment by nowindnowave** [comment]
I have solved it, the local certificate does not exist, re-download a cert.pem and put it in the SSL directory

**Comment by zjrwtx** [comment]
> Most basic example (I don't know async):
> 
> ```python
> from revChatGPT.Official import AsyncChatbot
> import asyncio
> 
> async def main():
>     bot = AsyncChatbot(api_key="sk-...")
>     return await bot.ask("Hello World")
> 
> if __name__ == "__main__":
>     print(asyncio.run(main()))
> ```
your origin code has error:loof is running,after i ask chatgpt,it gives me these code,but it seems that no respond,please help me
![image](https://user-images.githubusercontent.com/86822589/216825259-3301454d-ed02-4445-9359-588e6a64edd1.png)
