### ISSUE TITLE
Why does this happen? Is it because the server is too packed? 

### ISSUE THREAD

**Issue by TryMee3** [acheong08/ChatGPT#612]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 123, in <module>
    main()
  File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 111, in main
    response = chatbot.ask(prompt, temperature=args.temperature)
  File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 139, in ask
    completion = self._get_completion(
  File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 64, in _get_completion
    return openai.Completion.create(
  File "/home/kali/.local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

**Comment by QiuZiXian** [comment]
> Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/**main**.py", line 123, in main() File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/**main**.py", line 111, in main response = chatbot.ask(prompt, temperature=args.temperature) File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 139, in ask completion = self._get_completion( File "/home/kali/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 64, in _get_completion return openai.Completion.create( File "/home/kali/.local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create return super().create(*args, **kwargs) File "/home/kali/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 227, in request resp, got_stream = self._interpret_response(result, stream) File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response self._interpret_response_line( File "/home/kali/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line raise self.handle_error_response( openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

the same for me now
