### ISSUE TITLE
[BUG] After running python src/revChatGPT/Unofficial.py I am getting this message.

### ISSUE THREAD

**Issue by rarhs** [acheong08/ChatGPT#617]
Logging in...
Spawning browser...
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/ChatGPT/src/revChatGPT/Unofficial.py", line 817, in <module>
    main()
  File "/workspaces/codespaces-blank/ChatGPT/src/revChatGPT/Unofficial.py", line 813, in main
    chatGPT_main(configure())
  File "/workspaces/codespaces-blank/ChatGPT/src/revChatGPT/Unofficial.py", line 745, in chatGPT_main
    chatbot = Chatbot(config)
  File "/workspaces/codespaces-blank/ChatGPT/src/revChatGPT/Unofficial.py", line 72, in __init__
    self.__email_login()
  File "/workspaces/codespaces-blank/ChatGPT/src/revChatGPT/Unofficial.py", line 469, in __email_login
    driver = uc.Chrome(
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 421, in __init__
    browser = subprocess.Popen(
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.4/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/python/3.10.4/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

why I am getting this?

**Comment by suyunkai** [comment]
same

**Comment by jliuliu** [comment]
same

**Comment by takiholadi** [comment]
same

**Comment by Elijahxx** [comment]
Actually I don't know how to run---

**Comment by liuling1314** [comment]
same

**Comment by lizekui** [comment]
same


```
:~$ pip list 
Package                 Version
----------------------- ---------------
2captcha-python         1.1.3
aiohttp                 3.8.3
aiosignal               1.3.1
async-generator         1.10
async-timeout           4.0.2
attrs                   21.2.0
Automat                 20.2.0
Babel                   2.8.0
bcrypt                  3.2.0
blinker                 1.4
blobfile                2.0.1
certifi                 2022.12.7
chardet                 4.0.0
charset-normalizer      2.1.1
click                   8.0.3
cloud-init              22.4.2
colorama                0.4.4
command-not-found       0.3
configobj               5.0.6
constantly              15.1.0
cryptography            3.4.8
dbus-python             1.2.18
distro                  1.7.0
distro-info             1.1build1
exceptiongroup          1.1.0
filelock                3.9.0
frozenlist              1.3.3
h11                     0.14.0
httplib2                0.20.2
hyperlink               21.0.0
idna                    3.3
importlib-metadata      4.6.4
incremental             21.3.0
jeepney                 0.7.1
Jinja2                  3.0.3
jsonpatch               1.32
jsonpointer             2.0
jsonschema              3.2.0
keyring                 23.5.0
launchpadlib            1.10.16
lazr.restfulclient      0.14.4
lazr.uri                1.0.6
lxml                    4.9.2
MarkupSafe              2.0.1
more-itertools          8.10.0
multidict               6.0.4
netifaces               0.11.0
oauthlib                3.2.0
openai                  0.26.5
outcome                 1.2.0
pexpect                 4.8.0
pip                     23.0
ptyprocess              0.7.0
pyasn1                  0.4.8
pyasn1-modules          0.2.1
pycryptodomex           3.17
PyGObject               3.42.1
PyHamcrest              2.0.2
PyJWT                   2.3.0
pyOpenSSL               21.0.0
pyparsing               2.4.7
pyparted                3.11.7
pyrsistent              0.18.1
pyserial                3.5
PySocks                 1.7.1
python-apt              2.3.0+ubuntu2.1
python-debian           0.1.43ubuntu1
python-magic            0.4.24
pytz                    2022.1
PyYAML                  5.4.1
regex                   2022.10.31
requests                2.28.2
revChatGPT              1.2.1
SecretStorage           3.3.1
selenium                4.8.0
service-identity        18.1.0
setuptools              59.6.0
six                     1.16.0
sniffio                 1.3.0
sortedcontainers        2.4.0
sos                     4.4
ssh-import-id           5.11
systemd-python          234
tiktoken                0.2.0
tls-client              0.1.8
tqdm                    4.64.1
trio                    0.22.0
trio-websocket          0.9.2
Twisted                 22.1.0
ubuntu-advantage-tools  27.12
ufw                     0.36.1
unattended-upgrades     0.1
undetected-chromedriver 3.4.5
urllib3                 1.26.5
wadllib                 1.3.6
WALinuxAgent            2.2.46
websockets              10.4
wheel                   0.38.4
wsproto                 1.2.0
yarl                    1.8.2
zipp                    1.0.0
zope.interface          5.4.0

```

**Comment by HaodiFan** [comment]
It seems like you didnt provide the executable path in the config file. You need to provide the executable path inside the config file.

**Comment by acheong08** [comment]
Or possibly defined but blank. That also breaks things

**Comment by rarhs** [comment]
Are you talking about $HOME/.config/revChatGPT/config.json?

**Comment by acheong08** [comment]
yes

**Comment by rarhs** [comment]
{
  "executable_path": "/workspaces/codespaces-blank/ChatGPT",
  "email": "<somename@gmail.com>",
  "password": "somerandompassword"
}

still getting the same error message.

**Comment by acheong08** [comment]
The executable path is supposed to point to your Chrome executable

**Comment by Vaiterius** [comment]
```
{
  "executable_path": "C:/Program Files (x86)/Google/Application/chrome.exe",
  "email": "...",
  "password": "...",
}
```

I still get the same error message even after adding this

**Comment by acheong08** [comment]
This issue is stale because it has been open for 30 days with no activity.
