### ISSUE TITLE
[BUG] openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by liuyan731** [acheong08/ChatGPT#620]
When I run the command: python3 -m revChatGPT.Official --api_key API_KEY --stream
the following error :  openai.error.InvalidRequestError: That model does not exist

revChatGPT=1.2.1
ENGINE=text-chat-davinci-002-20221122

**Comment by jordandadams** [comment]
Yeah, looks like they've changed model name again.

**Comment by rudireg** [comment]
`ChatGPT: 
Traceback (most recent call last):
  File "/home/rudi/.local/bin/OfficialChatGPT", line 8, in <module>
    sys.exit(main())
  File "/home/rudi/.local/lib/python3.8/site-packages/revChatGPT/Official.py", line 478, in main
    for response in chatbot.ask_stream(prompt, temperature=args.temperature):
  File "/home/rudi/.local/lib/python3.8/site-packages/revChatGPT/Official.py", line 143, in ask_stream
    completion=self._get_completion(prompt, temperature, stream=True),
  File "/home/rudi/.local/lib/python3.8/site-packages/revChatGPT/Official.py", line 48, in _get_completion
    return openai.Completion.create(
  File "/home/rudi/.local/lib/python3.8/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/rudi/.local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/rudi/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/rudi/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/home/rudi/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
`

**Comment by jordandadams** [comment]
@acheong08 Is there any luck with browserless at this point?

**Comment by F33RNI** [comment]
I have tested all models from text-chat-davinci-001-20220101 to text-chat-davinci-004-20230430 and none exist 😔
It looks like now the name format is different than text-chat-davinci-00X-YYYYMMDD

**Comment by F33RNI** [comment]
Models still working: `text-davinci-003`, `text-davinci-002`
But they are much simpler than text-chat-davinci-00X-YYYYMMDD

**Comment by acheong08** [comment]
I have been brute forcing a ton of different permutations. No luck

**Comment by SEQOU** [comment]
> 

Have you tried adding the codename the new bing ai uses? Sydney was it? on davinci-003... never know..

**Comment by acheong08** [comment]
Yes. @transitive-bullshit brute forced it with 500 errors. It exists but they patched the permissions system

**Comment by kWAYTV** [comment]
Any working fix atm?

**Comment by acheong08** [comment]
Use V1. That still works for most people

**Comment by acheong08** [comment]
If you have access to the new Bing, you can also try out https://github.com/acheong08/EdgeGPT

**Comment by kWAYTV** [comment]
> Use V1. That still works for most people. Check readme

Thanks mate, is there any kind of Discord community for this? For support and discussion?

**Comment by acheong08** [comment]
https://discord.gg/WMNtbDUjUv

**Comment by jordandadams** [comment]
> Use V1. That still works for most people. Check readme

What is the V1 model? I can't seem to find it.

**Comment by acheong08** [comment]
Version 1 uses browser to fetch cookies

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.0
