### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#629]
**Description**

**Steps to Reproduce**
5. 
**Expected behavior**

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: Linux
 - Python version: Python 3.10.4
 - ChatGPT Version: Name: revChatGPT
                                   Version: 1.2.1
                                   Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
                                  Home-page: https://github.com/acheong08/ChatGPT
                                  Location: /usr/local/lib/python3.10/site-packages
                                  Requires: openai, tiktoken

**Additional context**
- error：
            ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...
Spawning browser...

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 817, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 813, in main
    chatGPT_main(configure())
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 745, in chatGPT_main
    chatbot = Chatbot(config)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 72, in __init__
    self.__email_login()
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 469, in __email_login
    driver = uc.Chrome(
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:39064
from chrome not reachable
Stacktrace:
#0 0x562650814d93 <unknown>
#1 0x5626505e315d <unknown>
#2 0x5626505d1a2b <unknown>
#3 0x56265060fc63 <unknown>
#4 0x5626506072fc <unknown>
#5 0x56265064c4f4 <unknown>
#6 0x562650643353 <unknown>
#7 0x562650612e40 <unknown>
#8 0x562650614038 <unknown>
#9 0x5626508688be <unknown>
#10 0x56265086c8f0 <unknown>
#11 0x56265084cf90 <unknown>
#12 0x56265086db7d <unknown>
#13 0x56265083e578 <unknown>
#14 0x562650892348 <unknown>
#15 0x5626508924d6 <unknown>
#16 0x5626508ac341 <unknown>
#17 0x7f5c10c94ea5 start_thread

**Comment by Liu-Angelo** [comment]
> **Description** A clear and concise description of what the bug is.
> 
> **Steps to Reproduce**
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ```
>     ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
>     Repo: github.com/acheong08/ChatGPT
> ```
> 
> Type '!help' to show a full list of commands Press enter twice to submit your question.
> 
> Logging in... Spawning browser...
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 817, in main() File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 813, in main chatGPT_main(configure()) File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 745, in chatGPT_main chatbot = Chatbot(config) File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 72, in **init** self.__email_login() File "/usr/local/lib/python3.10/site-packages/revChatGPT/Unofficial.py", line 469, in __email_login driver = uc.Chrome( File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/**init**.py", line 441, in **init** super(Chrome, self).**init**( File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in **init** super().**init**( File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in **init** super().**init**( File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in **init** self.start_session(capabilities, browser_profile) File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/**init**.py", line 704, in start_session super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session( File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute self.error_handler.check_response(response) File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:39064 from chrome not reachable Stacktrace: #0 0x562650814d93 #1 0x5626505e315d #2 0x5626505d1a2b #3 0x56265060fc63 #4 0x5626506072fc #5 0x56265064c4f4 #6 0x562650643353 #7 0x562650612e40 #8 0x562650614038 #9 0x5626508688be #10 0x56265086c8f0 #11 0x56265084cf90 #12 0x56265086db7d #13 0x56265083e578 #14 0x562650892348 #15 0x5626508924d6 #16 0x5626508ac341 #17 0x7f5c10c94ea5 start_thread **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Output** In the correct directory, run the following command: `python3 -m revChatGPT --debug`
> 
> **Environment** Please update your packages before reporting the issue: `pip3 install --upgrade revChatGPT`
> 
> * OS: [e.g. Linux, MacOS, Windows]
> * Python version: python -V
> * ChatGPT Version: pip3 show revChatGPT
> 
> **Additional context** Add any other context about the problem here.
