### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by JerryWn12** [acheong08/ChatGPT#630]
```
➜ ~  ✗ pip3 install revChatGPT
Collecting revChatGPT
  Using cached revChatGPT-1.2.2-py3-none-any.whl (25 kB)
Collecting tls-client>=0.1.7
  Using cached tls_client-0.1.8-py3-none-any.whl (34.9 MB)
Collecting undetected-chromedriver>=3.1.7
  Using cached undetected-chromedriver-3.4.5.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Collecting selenium>=4.7.2
  Using cached selenium-4.8.0-py3-none-any.whl (6.3 MB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\jerrywn\appdata\local\programs\msys2\mingw64\lib\python3.10\site-packages (from selenium>=4.7.2->revChatGPT) (2022.12.7)
Collecting trio~=0.17
  Using cached trio-0.22.0-py3-none-any.whl (384 kB)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\jerrywn\appdata\local\programs\msys2\mingw64\lib\python3.10\site-packages (from selenium>=4.7.2->revChatGPT) (1.26.14)
Collecting trio-websocket~=0.9
  Using cached trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Requirement already satisfied: requests in c:\users\jerrywn\appdata\local\programs\msys2\mingw64\lib\python3.10\site-packages (from undetected-chromedriver>=3.1.7->revChatGPT) (2.28.2)
Requirement already satisfied: websockets in c:\users\jerrywn\appdata\local\programs\msys2\mingw64\lib\python3.10\site-packages (from undetected-chromedriver>=3.1.7->revChatGPT) (10.4)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting exceptiongroup>=1.0.0rc9
  Using cached exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting cffi>=1.14
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JerryWn\AppData\Local\Temp\pip-install-apolg27i\cffi_adb359497a564580871e6fd68b49f314\setup.py", line 126, in <module>
          if sys.platform == "win32" and uses_msvc():
        File "C:\Users\JerryWn\AppData\Local\Temp\pip-install-apolg27i\cffi_adb359497a564580871e6fd68b49f314\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Users\JerryWn\AppData\Local\Programs\msys2\mingw64\lib\python3.10\site-packages\setuptools\_distutils\command\config.py", line 224, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\JerryWn\AppData\Local\Programs\msys2\mingw64\lib\python3.10\site-packages\setuptools\_distutils\command\config.py", line 129, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\JerryWn\AppData\Local\Programs\msys2\mingw64\lib\python3.10\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
          self.initialize()
        File "C:\Users\JerryWn\AppData\Local\Programs\msys2\mingw64\lib\python3.10\site-packages\setuptools\_distutils\_msvccompiler.py", line 246, in initialize
          raise DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by JerryWn12** [comment]
use `python -m pip install revChatGPT` solves the problem
