### ISSUE TITLE
[BUG] model doesnt exist 

### ISSUE THREAD

**Issue by RLBOT1v1Replayproprogrammer** [acheong08/ChatGPT#635]
ChatGPT:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 502, in <module>
    main()
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 495, in main
    for response in chatbot.ask_stream(prompt, temperature=args.temperature):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 160, in ask_stream
    completion=self._get_completion(prompt, temperature, stream=True),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 64, in _get_completion
    return openai.Completion.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mayma\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist

**Comment by jabontz09** [comment]
![image](https://user-images.githubusercontent.com/27756050/218243464-ed15b277-1ed5-463c-9ff4-65f4cde3fa83.png)
same error

**Comment by txtspam** [comment]
patched again ?

**Comment by ashinnotfound** [comment]
same😢 it seems that the model just temporarily appeared and has been removed again...

**Comment by JerryWn12** [comment]
same
```
➜ chatgpt  & C:/Users/JerryWn/AppData/Local/Programs/Python/Python311/python.exe c:/Users/JerryWn/WorkSpace/chatgpt/main.py
Traceback (most recent call last):
  File "c:\Users\JerryWn\WorkSpace\chatgpt\main.py", line 5, in <module>
    response = bot.ask("who are you", temperature=0.6)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 139, in ask
    completion = self._get_completion(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\Official.py", line 64, in _get_completion
    return openai.Completion.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request    
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\JerryWn\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
➜ chatgpt  ✗ pip list 
Package                 Version
----------------------- ----------
aiohttp                 3.8.3
aiosignal               1.3.1
async-generator         1.10
async-timeout           4.0.2
attrs                   22.2.0
autopep8                2.0.1
blobfile                2.0.1
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      2.1.1
colorama                0.4.6
filelock                3.9.0
frozenlist              1.3.3
h11                     0.14.0
idna                    3.4
lxml                    4.9.2
multidict               6.0.4
openai                  0.26.5
outcome                 1.2.0
pip                     23.0
pycodestyle             2.10.0
pycparser               2.21
pycryptodomex           3.17
PySocks                 1.7.1
regex                   2022.10.31
requests                2.28.2
revChatGPT              2.0.0
selenium                4.8.0
setuptools              65.5.0
sniffio                 1.3.0
sortedcontainers        2.4.0
tiktoken                0.2.0
tls-client              0.1.8
tqdm                    4.64.1
trio                    0.22.0
trio-websocket          0.9.2
undetected-chromedriver 3.4.6
urllib3                 1.26.14
websockets              10.4
wsproto                 1.2.0
yarl                    1.8.2
➜ chatgpt
```

**Comment by xjd-ziyu** [comment]
openai.error.InvalidRequestError: That model does not exist

**Comment by xsa-dev** [comment]
openai.error.InvalidRequestError: That model does not exist

**Comment by acheong08** [comment]
Yeah it's gone

**Comment by acheong08** [comment]
We've got a spy haha. They took it down immediately after we updated

**Comment by ashinnotfound** [comment]
> We've got a spy haha. They took it down immediately after we updated

sad😢

**Comment by RLBOT1v1Replayproprogrammer** [comment]
> We've got a spy haha. They took it down immediately after we updated

dang, thanks for all your hardwork. its inspirational
 brother

**Comment by Liu-Angelo** [comment]
> 我们有一个间谍哈哈。我们更新后他们立即将其删除
Thanks for the exploration

**Comment by getxd-dev** [comment]
it was a fun 30 minutes experience. 😅

**Comment by FoxGames01** [comment]
> We've got a spy haha. They took it down immediately after we updated

you've tried finding a new model with "text-chat-davinci-002-sh-alpha-XXXXXXXXXXXXX"?

**Comment by siyuyuan** [comment]
> We've got a spy haha. They took it down immediately after we updated

:( Too bad

**Comment by yb-cs** [comment]
I think chatgpt plus support is better as they are already rolling it out in many countries
