### ISSUE TITLE
V1.1 Proxy API

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#640]
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: Linux
 - Python version: 3.10
 - ChatGPT Version: Version: 2.0.1

**Additional context**
The V1.1 Proxy API is stuck without output

**Comment by acheong08** [comment]
Somebody is ddosing it

**Comment by Liu-Angelo** [comment]
> 有人正在服用它

When is the V1.1 Proxy API available

**Comment by acheong08** [comment]
It currently works for me. Might need to try a few times because speed is slow

**Comment by acheong08** [comment]
It's getting DDOsed to hell

**Comment by Liu-Angelo** [comment]
> 它越来越被 DDOs 搞砸了

Thank you for using the automatic login version of the browser for the time being. proxied will be verified after normal use

**Comment by ydamni** [comment]
Do you mean the IP inside this file are getting DDOSed ? : https://github.com/acheong08/ChatGPT-Proxy/blob/main/proxy.py

**Comment by acheong08** [comment]
Yes

**Comment by ydamni** [comment]
Maybe some people used it for their own purposes so it feels like it is being DDOSed.

I guess the best solution is to use another proxy for RevChatGPT, and put a var $PROXY_IP inside ChatGPT-Proxy/proxy.py so people could insert their own proxies in the future.

**Comment by acheong08** [comment]
> I guess the best solution is to use another proxy for RevChatGPT, and put a var $PROXY_IP inside ChatGPT-Proxy/proxy.py so people could insert their own proxies in the future.

Cloudflare is IP based. It wouldn't work

**Comment by acheong08** [comment]
> Maybe some people used it for their own purposes so it feels like it is being DDOSed.

I can see the requests and it's just a for loop to get pointless endpoints. Most of it are GET requests rather than POST

**Comment by ydamni** [comment]
> I can see the requests and it's just a for loop to get pointless endpoints. Most of it are GET requests rather than POST

Feels bad...

**Comment by thechen130** [comment]
It is recommended to log in based on the mailbox password. Can you refer to this：https://github.com/fuergaosi233/wechat-chatgpt

**Comment by Liu-Angelo** [comment]
Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-reverse/bin/chatgpt_proxied_app.py", line 98, in chat
    message = chat_with_chatgpt(msg)
  File "/data/chatgpt/chatgpt-reverse/bin/chatgpt_proxied_app.py", line 136, in chat_with_chatgpt
    response = chatbot.ask(prompt, conversation_id=conversation_id, parent_id=parent_id, gen_title=False)
  File "/data/chatgpt/chatgpt-reverse/bin/revChatGPT/Proxied.py", line 127, in ask
    raise Exception(
Exception: Wrong response code: 504! Refreshing session...

**Comment by bios000** [comment]
> Somebody is ddosing it



I suggest you use cloudflare to prevent ddos attacks

**Comment by acheong08** [comment]
This issue is stale because it has been open for 30 days with no activity.
