### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message:  Stacktrace:

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#643]
Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-reverse/./bin/chatgpt_browser_app.py", line 97, in chat
    message = chat_with_chatgpt(msg)
  File "/data/chatgpt/chatgpt-reverse/./bin/chatgpt_browser_app.py", line 131, in chat_with_chatgpt
    chatbot = Chatbot({
  File "/data/chatgpt/chatgpt-reverse/bin/revChatGPT/Unofficial.py", line 72, in __init__
    self.__email_login()
  File "/data/chatgpt/chatgpt-reverse/bin/revChatGPT/Unofficial.py", line 503, in __email_login
    WebDriverWait(driver, 120).until(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cef06bd93 (/root/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x66cd92)
#1 0x560ceee3a2d7 (/root/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x43b2d6)
#2 0x560ceee76caa (/root/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x477ca9)
#3 0x560ceee76db1 (/root/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x477db0)

**Comment by acheong08** [comment]
This issue is stale because it has been open for 30 days with no activity.
