### ISSUE TITLE
[BUG]tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": EOF

### ISSUE THREAD

**Issue by Altman-conquer** [acheong08/ChatGPT#653]
**Description**
已更新至**V2**版本，通过cmd运行报错，通过pycharm运行(https://github.com/acheong08/ChatGPT#developers) 处提供的示例代码后也会出现（已使用正确账号密码）

**Steps to Reproduce**
1. 使用CMD输入python -m revChatGPT.V2 -e my_email@qq.ocm -p my_password

**Additional context**
报错信息如下：

```
Logging in...
Traceback (most recent call last):
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V2.py", line 277, in <module>
    asyncio.run(main())
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V2.py", line 225, in main
    chatbot = Chatbot(args.email, args.password)
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V2.py", line 120, in __init__
    self.login(email, password)
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V2.py", line 172, in login
    auth.begin()
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 77, in begin
    response = self.session.get(
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "C:\Users\24761\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": EOF
```

**Comment by ForgetThatNight** [comment]
这个问题我也遇到了，你解决了吗
