### ISSUE TITLE
2.1.4版本加入proxy后可以取得access_token,但后面还有报错

### ISSUE THREAD

**Issue by nieziqi123** [acheong08/ChatGPT#670]
Traceback (most recent call last):
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/home/Desktop/setup.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/home/Desktop/setup.py", line 6, in main
    async for line in chatbot.ask("Hello"):
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\V2.py", line 143, in ask
    async with httpx.AsyncClient().stream(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1576, in stream
    response = await self.send(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

Process finished with exit code 1

**Comment by acheong08** [comment]
What does your proxy look like?

Correct format: `socks5://IP:PORT`

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/218320003-d492f347-2cb6-44cb-834c-d8982c288914.png)

**Comment by nieziqi123** [comment]
C:\Users\home>python -m revChatGPT.V2 -e "**" -p "**" --proxy "socks5://127.0.0.1:7890"

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
你好

ChatGPT:
Traceback (most recent call last):
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\cAke\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1131)
