### ISSUE TITLE
[BUG]运行报错

### ISSUE THREAD

**Issue by lp123sun** [acheong08/ChatGPT#674]
ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.

You:
哈哈哈

ChatGPT:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/i/.local/lib/python3.10/site-packages/revChatGPT/V2.py", line 318, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/i/.local/lib/python3.10/site-packages/revChatGPT/V2.py", line 309, in main
    print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
TypeError: string indices must be integers
i@i:~/.local/lib/python3.10/site-packages/revChatGPT$ 

每次都是我发一句话后，等待ChatGPT回复，提示以上错误

**Comment by acheong08** [comment]
yeah fixed
