### ISSUE TITLE
TODO: Better login error messages

### ISSUE THREAD

**Issue by verazuo** [acheong08/ChatGPT#681]
**Description**

Seems the OpenAI auth process failed.

**Output**

```
(py39) root: python3 -m revChatGPT.V2 -e xxxx -p xxxxxx

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Traceback (most recent call last):
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 325, in <module>
    asyncio.run(main())
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 272, in main
    chatbot = Chatbot(args.email, args.password, paid=args.paid, proxy=args.proxy)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 132, in __init__
    self.login(email, password, proxy, insecure)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 196, in login
    auth.begin()
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 81, in begin
    self.__part_two()
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in __part_two
    self.__part_three(token=csrf_token)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 154, in __part_three
    self.__part_four(url=url)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 202, in __part_four
    raise Exception("Unknown error")
Exception: Unknown error
(py39) vera@verasTypeWriter ~ % 
    self.__part_three(token=csrf_token)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 154, in __part_three
    self.__part_four(url=url)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 202, in __part_four
    raise Exception("Unknown error")
Exception: Unknown error
```

**Comment by acheong08** [comment]
Wrong email/password or using Google/Microsoft

**Comment by verazuo** [comment]
I believe the email/password is correct.
Cause I wrote a loop to run the same command with questions. And suddenly, it raises this error message to me.
Could it be caused by DDoS on the server?

**Comment by acheong08** [comment]
It's working just fine for me

**Comment by acheong08** [comment]
Another possibility is that anaconda is messing stuff up

**Comment by verazuo** [comment]
Figured it out... It's caused by `429 You are being rate limited. ` 😭

**Comment by acheong08** [comment]
Need to add more error handlers

**Comment by acheong08** [comment]
I'll add some code later

**Comment by verazuo** [comment]
Cool! Feel free to ask me if you need any more details.

**Comment by verazuo** [comment]
BTW, even if I changed the IP and the process just works with a normal account.
Once I use a paid account
```
chatbot = Chatbot(email="xxx", password="xxx", paid=True)
```

I will face another bug `Wrong status code`...

I post this bug here, but if you need to open it to another issue, I can also do it quickly :D

Many thx for your effort on this project! Really appreciate it!

**Comment by verazuo** [comment]
Many thx for your effort on this project! Really appreciate it!

**Comment by acheong08** [comment]
> BTW, even if I changed the IP and the process just works with a normal account.

Rate limits are 30 requests per minute tracked per account

**Comment by acheong08** [comment]
> I will face another bug Wrong status code...

That is a login issue. Are you using Google or Microsoft account?

**Comment by Zeus-Athena** [comment]
hi,
Can the Google account be successfully authorized?
thanks 

@acheong08

**Comment by verazuo** [comment]
> > BTW, even if I changed the IP and the process just works with a normal account.
> 
> Rate limits are 30 requests per minute tracked per account

Weird... I only send 10 requests to the API per minute per account. 
But luckily, OpenAI will release my IP several hours later (not sure about the exact waiting time)
