### ISSUE TITLE
[BUG] Exception: OpenAI error!

### ISSUE THREAD

**Issue by Zeus-Athena** [acheong08/ChatGPT#689]
**Description**
auth success with google account, but response wrong  

**Output**

python3 -m revChatGPT.V2 -e xxxx@gmail.com -p xxxxx

You:
hi

ChatGPT:
error: OpenAI error!
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/revChatGPT/V2.py", line 334, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/revChatGPT/V2.py", line 323, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/revChatGPT/V2.py", line 164, in ask
    raise Exception("OpenAI error!")
Exception: OpenAI error!

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: MacOS
 - Python version: Python 3.9.6
 - ChatGPT Version: Version: 2.1.10

**Comment by ZZY-26-26-25** [comment]
same as me. waiting for solutions

**Comment by msg-bq** [comment]
can you access openai/chatgpt by browser?

**Comment by acheong08** [comment]
Are you using plus account without using `--paid`?

**Comment by Zeus-Athena** [comment]
> Are you using plus account without using `--paid`?

not plus account

**Comment by Zeus-Athena** [comment]
> can you access openai/chatgpt by browser(not this repo)?

use browser is OK.

**Comment by ljhmily** [comment]
the same problem

**Comment by Zeus-Athena** [comment]
> > > can you access openai/chatgpt by browser(not this repo)?
> > 
> > 
> > use browser is OK.
> 
> The two times I encountered "OpenAI error" or "Unknown error", they were both due to the proxy setting error.
> 
> It is recommended to use an American proxy, turn on global mode, and pass proxy information into "proxy" parameters or write to environment variables

I am use an American proxy software  and   turn on global mode, now  . the same error .

how to pass proxy information into "proxy" parameters ?  
python3 -m revChatGPT.V2 -e xxxxx@gmail.com -p xxxxx  --proxy ?
thanks !
