### ISSUE TITLE
[BUG]string indices must be integers

### ISSUE THREAD

**Issue by hfyydd** [acheong08/ChatGPT#691]
V2版本 
<img width="279" alt="截屏2023-02-13 13 13 04" src="https://user-images.githubusercontent.com/65524252/218376182-9df94054-08c8-494f-a414-1194905dd4bc.png">

**Comment by acheong08** [comment]
Are you using plus account without specifying `--paid`?

**Comment by boxiyang** [comment]
I encountered the same error even though I am not using the paid version.
Os:windows server 2019 
python ver:3.8.10

**Comment by acheong08** [comment]
more debug info please

**Comment by skyyaman** [comment]
我也是一样的错误
Traceback (most recent call last):
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 325, in <module>
    asyncio.run(main())
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\V2.py", line 315, in main
    result = line["choices"][0]["text"].replace("<|im_end|>", "")
TypeError: string indices must be integers
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000260ACF8C280>
Traceback (most recent call last):
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\龙\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by boxiyang** [comment]
python -m revChatGPT.V2 -e xxxxx -p xxxxxxx

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
hi

ChatGPT:
Traceback (most recent call last):
  File "E:\dev\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\dev\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\dev\python\lib\site-packages\revChatGPT\V2.py", line 325, in <module>
    asyncio.run(main())
  File "E:\dev\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\dev\python\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\dev\python\lib\site-packages\revChatGPT\V2.py", line 315, in main
    result = line["choices"][0]["text"].replace("<|im_end|>", "")
TypeError: string indices must be integers
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000262A6A13790>
Traceback (most recent call last):
  File "E:\dev\python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\dev\python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\dev\python\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "E:\dev\python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by hfyydd** [comment]
I am not a plus account

**Comment by hfyydd** [comment]
I use insecure=True and It is ok now!

**Comment by dawhdb** [comment]
> > 我使用 insecure=True 现在可以了！
> 
> 你能展示更多细节吗？关于要更改的代码

I have the same problem. Do you have a solution

**Comment by hfyydd** [comment]
chatbot = Chatbot(email="", password="", **_insecure=True_**)

**Comment by dawhdb** [comment]
> chatbot = Chatbot(email="", password="", **_insecure=True_**)

I'll try. Thank you for your reply

**Comment by dawhdb** [comment]
> chatbot = Chatbot(email="", password="", **_insecure=True_** )

![image](https://user-images.githubusercontent.com/125231265/218630518-0c9e1522-8a1a-4a47-9a45-a5842161e340.png)
 I added insecure=True, so I replaced this error
