### ISSUE TITLE
[BUG]httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

### ISSUE THREAD

**Issue by ZZY-26-26-25** [acheong08/ChatGPT#693]
**Description**
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.

You:
hello, everything ok?

ChatGPT:
error: Unknown error
Traceback (most recent call last):
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 334, in <module>
    asyncio.run(main())
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 323, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 167, in ask
    print(response.text)
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/httpx/_models.py", line 574, in text
    content = self.content
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/httpx/_models.py", line 568, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`
No module named revChatGPT.__main__; 'revChatGPT' is a package and cannot be directly executed

**Environment**
M1Pro Mac

 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: python 3.9 
 - ChatGPT Version: 2.1.11

**Comment by helloxz** [comment]
+1

**Comment by albertwy** [comment]
same here

**Comment by acheong08** [comment]
Removed buggy code in latest release
