### ISSUE TITLE
Error in __part_seven

### ISSUE THREAD

**Issue by ttytu2** [acheong08/ChatGPT#696]
`Connected to pydev debugger (build 211.7628.24)
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/lishuai/PycharmProjects/ChatGPT/src/revChatGPT/V2.py", line 304, in main
    chatbot = Chatbot(
  File "/Users/lishuai/PycharmProjects/ChatGPT/src/revChatGPT/V2.py", line 138, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/Users/lishuai/PycharmProjects/ChatGPT/src/revChatGPT/V2.py", line 218, in login
    auth.begin()
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 82, in begin
    self.__part_two()
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 113, in __part_two
    self.__part_three(token=csrf_token)
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 155, in __part_three
    self.__part_four(url=url)
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 188, in __part_four
    self.__part_five(state=state)
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 222, in __part_five
    self.__part_six(state=state)
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 262, in __part_six
    self.__part_seven(state=state)
  File "/Users/lishuai/PycharmProjects/ChatGPT/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 317, in __part_seven
    raise Exception("Wrong status code")
Exception: Wrong status code`

I am using in China, I tried both using a proxy and not using a proxy, but neither worked.

config.json:
{
  "email": "xxx",
  "password": "xxx",
  "proxy": "socks5://xxxx:1082"
}

**Comment by ttytu2** [comment]
and I am using the latest version

**Comment by gnohgnailoug** [comment]
same problem

**Comment by ttytu2** [comment]
> same problem

It's probably a problem with the network proxy. When I deploy the code to a foreign server (in the US), it works without any issues.

**Comment by toughhou** [comment]
same problem
