### ISSUE TITLE
[Bug]: py2app 打包该库时出现“Unknown encoding gpt2”

### ISSUE THREAD

**Issue by Ryan-the-hito** [acheong08/ChatGPT#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

在使用 py2app 打包软件的时候，将 revChatGPT 打包，但是出现以下报错，似乎是编解码问题？
```
File "/Applications/MyApp.app/Contents/Resources/lib/python3.9/revChatGPT/V2.py", line 14, in <module>
    ENCODER = tiktoken.get_encoding("gpt2")
  File "tiktoken/registry.pyc", line 60, in get_encoding
ValueError: Unknown encoding gpt2
```

### Steps to reproduce the problem

1. 自己写的 .py 想打包起来用，使用的是 py2app，setup.py 里面加入了 revChatGPT。（`'packages': ['revChatGPT’],`）
2. `python3 setup.py MyApp.py`打包后运行发现无法启动
3. 在`MyApp.app/Contents/MacOS/MyApp`路径下使用 Terminal 方式打开，于是出现报错```File "/Applications/MyApp.app/Contents/Resources/lib/python3.9/revChatGPT/V2.py", line 14, in <module>
    ENCODER = tiktoken.get_encoding("gpt2")
  File "tiktoken/registry.pyc", line 60, in get_encoding
ValueError: Unknown encoding gpt2```

### What should have happened?

不知道是库的问题还是环境问题？我写的 py 文件是在 utf-8 的编解码环境中运行，但这不应该冲突吧？

### Commit where the problem happens

2.2.0

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
% /Applications/MyApp.app/Contents/MacOS/MyApp ; exit;
Traceback (most recent call last):
  File "/Applications/MyApp.app/Contents/Resources/__boot__.py", line 221, in <module>
    _run()
  File "/Applications/MyApp.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/MyApp.app/Contents/Resources/MyApp.py", line 19, in <module>
    from revChatGPT.V2 import Chatbot
  File "/Applications/MyApp.app/Contents/Resources/lib/python3.9/revChatGPT/V2.py", line 14, in <module>
    ENCODER = tiktoken.get_encoding("gpt2")
  File "tiktoken/registry.pyc", line 60, in get_encoding
ValueError: Unknown encoding gpt2
2023-02-14 00:32:56.204 MyApp[77222:3562906] Launch error
2023-02-14 00:32:56.204 MyApp[77222:3562906] Launch error
See the py2app website for debugging launch issues

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
```


### Additional information

_No response_

**Comment by acheong08** [comment]
PyApp archives do not allow tiktoken to download the required pre-trained models. Support not planned

**Comment by Ryan-the-hito** [comment]
Thanks~
