### ISSUE TITLE
[Bug]:  python3 -m revChatGPT.V2   unreachable

### ISSUE THREAD

**Issue by XZhang97666** [acheong08/ChatGPT#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I got a error after I login with  python3 -m revChatGPT.V2 -e "****" -p "****"

Exception: Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.

### Steps to reproduce the problem

ype '!help' to show a full list of commands
Press enter twice to submit your question.

You:
Hi              

ChatGPT:
error: Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.
Traceback (most recent call last):
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 367, in <module>
    asyncio.run(main())
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 356, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 166, in ask
    raise Exception("Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.")
Exception: Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.

### What should have happened?

na

### Commit where the problem happens

na

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
ype '!help' to show a full list of commands
Press enter twice to submit your question.


You:
Hi              

ChatGPT:
error: Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.
Traceback (most recent call last):
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 367, in <module>
    asyncio.run(main())
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 356, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/home/xinlu/anaconda3/envs/py38/lib/python3.8/site-packages/revChatGPT/V2.py", line 166, in ask
    raise Exception("Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.")
Exception: Origin is unreachable. Ensure that you are authenticated and are using the correct pricing model.
```

### Console logs

```Shell
na
```

**Comment by anenn** [comment]
You must either define --paid in command line or paid=True in code if you have a plus subscription.

**Comment by wbbw007** [comment]
I have the same situation and I am not a plus user ，`response.status_code == 523`

**Comment by acheong08** [comment]
Server DDOSed. It's back up
