### ISSUE TITLE
[Bug]:  connect: connection timed out (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 364, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 304, in main
    chatbot = Chatbot(
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 215, in login
    auth.begin()
  File "/usr/local/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 76, in begin
    response = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": socks connect tcp 127.0.0.1:16710->explorer.api.openai.com:443: dial tcp 127.0.0.1:16710: connect: connection timed out (Client.Timeout exceeded while awaiting headers)

### Steps to reproduce the problem

Singapore Amazon Agency

ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 364, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 304, in main
    chatbot = Chatbot(
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 215, in login
    auth.begin()
  File "/usr/local/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 76, in begin
    response = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": socks connect tcp 127.0.0.1:16710->explorer.api.openai.com:443: dial tcp 127.0.0.1:16710: connect: connection timed out (Client.Timeout exceeded while awaiting headers)

### What should have happened?

ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 364, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 304, in main
    chatbot = Chatbot(
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 215, in login
    auth.begin()
  File "/usr/local/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 76, in begin
    response = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": socks connect tcp 127.0.0.1:16710->explorer.api.openai.com:443: dial tcp 127.0.0.1:16710: connect: connection timed out (Client.Timeout exceeded while awaiting headers)

### Version where the problem happens

Name: revChatGPT
Version: 2.2.0
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0

### What Python version are you running this with?

Python 3.10.4

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
python3 -m revChatGPT.V2 -e "******.com" -p "******" --proxy "socks5://127.0.0.1:16710" --paid
```

### Console logs

```Shell
ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 364, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 304, in main
    chatbot = Chatbot(
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V2.py", line 215, in login
    auth.begin()
  File "/usr/local/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 76, in begin
    response = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tls_client/sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": socks connect tcp 127.0.0.1:16710->explorer.api.openai.com:443: dial tcp 127.0.0.1:16710: connect: connection timed out (Client.Timeout exceeded while awaiting headers)
```

**Comment by acheong08** [comment]
V2 broken use V1
