### ISSUE TITLE
BUG:Exception: Wrong status code

### ISSUE THREAD

**Issue by shenziqian** [acheong08/ChatGPT#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

raceback (most recent call last):
  File "d:\Mosss\WechatBot\chat.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "d:\Mosss\WechatBot\chat.py", line 4, in main
    chatbot = Chatbot(insecure=False,email="shenziqian666@163.com", password="*********")
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 218, in login
    auth.begin()
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 81, in begin
    self.__part_two()
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 112, in __part_two
    self.__part_three(token=csrf_token)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 154, in __part_three
    self.__part_four(url=url)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 187, in __part_four
    self.__part_five(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 221, in __part_five
    self.__part_six(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 261, in __part_six
    self.__part_seven(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 316, in __part_seven
    raise Exception("Wrong status code")
Exception: Wrong status code

### Steps to reproduce the problem

from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(insecure=False,email="shenziqian666@163.com", password="**********")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush = True)
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

### What should have happened?

Chatbot：Hello！

### Version where the problem happens

Name: revChatGPT
Version: 2.2.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: c:\python310\lib\site-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken
Required-by:

### What Python version are you running this with?

Python 3.10.5

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
C:\Users\Administrator>C:/Python310/python.exe d:/Mosss/WechatBot/chat.py
Traceback (most recent call last):
  File "d:\Mosss\WechatBot\chat.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "d:\Mosss\WechatBot\chat.py", line 4, in main
    chatbot = Chatbot(insecure=False,email="shenziqian666@163.com", password="*********")
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 218, in login
    auth.begin()
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 81, in begin
    self.__part_two()
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 112, in __part_two
    self.__part_three(token=csrf_token)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 154, in __part_three
    self.__part_four(url=url)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 187, in __part_four
    self.__part_five(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 221, in __part_five
    self.__part_six(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 261, in __part_six
    self.__part_seven(state=state)
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 316, in __part_seven
    raise Exception("Wrong status code")
Exception: Wrong status code
```

### Additional information

如果使用insecure=True的话会报错requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='chat.duti.tech', port=443): Read timed out. (read timeout=10)

**Comment by shenziqian** [comment]
Status code: 400Status code: 400

**Comment by shenziqian** [comment]
加入session_token后报错Traceback (most recent call last):
  File "d:\Mosss\WechatBot\chat.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "d:\Mosss\WechatBot\chat.py", line 7, in main
    async for line in chatbot.ask("Hello"):
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 172, in ask
    raise Exception("Unknown error")
Status code 404

**Comment by lss233** [comment]
I'm afaid you didn't read recent issues.  

V2 server is currently shutdown for maintance: https://github.com/acheong08/ChatGPT/issues/724#issue-1583523315  

insecure also temporary closed: https://github.com/acheong08/ChatGPT/issues/721#issuecomment-1429112273_

**Comment by shenziqian** [comment]
谢谢！
