### ISSUE TITLE
[Bug]: Unknown error

### ISSUE THREAD

**Issue by verazuo** [acheong08/ChatGPT#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Unknown error occurs
```
(py39) vera@verasTypeWriter crawler % python3 -m revChatGPT.V2 -e xxxx -p xxxx

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
hello

ChatGPT:
error: Unknown error
Traceback (most recent call last):
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 372, in <module>
    asyncio.run(main())
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 361, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages/revChatGPT/V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```

### Steps to reproduce the problem

1. run `python3 -m revChatGPT.V2 -e xxxx -p xxxx`
2. The developer code also fails

### What should have happened?

chatgpt respond

### Version where the problem happens

Name: revChatGPT
Version: 2.2.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /Users/vera/opt/miniconda3/envs/py39/lib/python3.9/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken
Required-by: 

### What Python version are you running this with?

Python 3.9.12

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
see above
```

**Comment by acheong08** [comment]
V2 No longer working. Use V1. OpenAI patched our bypass method

**Comment by AlasKuNull** [comment]
大佬, 感谢写个这么好的库!  我是小白,  V2不能用了, V1怎么处理返回的数据呀? 求教
