### ISSUE TITLE
[Bug]: When running it raises an unknown error.

### ISSUE THREAD

**Issue by SlickTorpedo** [acheong08/ChatGPT#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I ran the following code:

from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="myEmail", password="myPassword")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush = True)
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

And it gave an unknown error on trying to the chatbot.ask

error: Unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V2.py", line 372, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V2.py", line 361, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error

I know this is probably something just got patched and it's very recent but I thought i would report it incase!

### Steps to reproduce the problem

Paste in the code from the readme and run it. (With a valid email & password ofc)

### What should have happened?

Talked to Chat GPT

### Version where the problem happens

Name: revChatGPT
Version: 2.2.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken
Required-by: 

### What Python version are you running this with?

Python 3.10.6

### What is your operating system ?

Linux, Other/Cloud

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
root@ip-172-31-30-103:/home/ubuntu/test/Chat# python3 chat1
error: Unknown error
Traceback (most recent call last):
  File "/home/ubuntu/cosmos/Chat/chat1", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/cosmos/Chat/chat1", line 5, in main
    async for line in chatbot.ask("Hello"):
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```

### Additional information

I just updated the addon before opening this error.

I am running a cloud server on AWS and it was working as of 12 hours ago this is recent.

**Comment by SlickTorpedo** [comment]
I was not sure if https://github.com/acheong08/ChatGPT/issues/729#issuecomment-1429616540 relates to it, if so I apologize. 

But they were getting 502 I was just getting unknown error.

**Comment by SlickTorpedo** [comment]
Alright unfortunate. I will use V1. Thanks for your help.
