### ISSUE TITLE
[BUG]Execute  python -m revChatGPT report an error on my computer

### ISSUE THREAD

**Issue by silvermooooon** [acheong08/ChatGPT#74]
**Describe the bug**
`python -m revChatGPT` 
report an error on my computer
```
Traceback (most recent call last):
  File "E:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\python\lib\site-packages\revChatGPT\__main__.py", line 1, in <module>
    from revChatGPT.revChatGPT import Chatbot
  File "E:\python\lib\site-packages\revChatGPT\revChatGPT.py", line 4, in <module>
    import tls_client
  File "E:\python\lib\site-packages\tls_client\__init__.py", line 15, in <module>
    from .sessions import Session
  File "E:\python\lib\site-packages\tls_client\sessions.py", line 1, in <module>
    from .cffi import request
  File "E:\python\lib\site-packages\tls_client\cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "E:\python\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "E:\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 Is not a valid Win32 application.
```
I'm not familiar with python, so I can't find out the specific problems
I hope to get help

**Environmen:**
 - OS: Windows 10
 - Python version: `Python 3.10.4`
 - Version: 
 ```
Name: revChatGPT
Version: 0.0.26.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: e:\python\lib\site-packages
Requires: bs4, lxml, requests, tls-client
Required-by:
```

**Comment by acheong08** [comment]
Make sure you are using python3

**Comment by silvermooooon** [comment]
yes,
![image](https://user-images.githubusercontent.com/119033606/205882143-5052fff5-7f30-4ae8-bc5c-cdf1f5bee7c0.png)

**Comment by silvermooooon** [comment]
Thanks,I will try it on Linux

**Comment by acheong08** [comment]
@rawandahmad698 @FlorianREGAZ Any idea what is going on here?

**Comment by arldeng** [comment]
> 

this is because  your  python is 32bit ver and tls_client.dll is 64bit ver  , need to confirm these two are same version

**Comment by acheong08** [comment]
> this is because your python is 32bit ver and tls_client.dll is 64bit ver , need to confirm these two are same version

Might want to support both versions. Delegating to upstream
