### ISSUE TITLE
[Bug]: V2.py errors out with `Unknown error`.

### ISSUE THREAD

**Issue by dreirund** [acheong08/ChatGPT#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I have started `python ./V2.py -e <email> -p <password>` (with proper login credentials).

First, the output looks nice:

```

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
```

I type some text to the prompt:

```
Hallo!
Test.

```

Then it errors out:

```
ChatGPT:
error: Unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 372, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 361, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```

Regards!

### Steps to reproduce the problem

1. Run `python ./V2.py -e <email> -p <password>` (with proper login credentials).
2. Type something at the prompt.
3. Instead of an answer, crash (see above).

### What should have happened?

A response from ChatGPT.

### Version where the problem happens

`python3 -m pip show revChatGPT`:

```
Name: revChatGPT
Version: 2.2.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/lib/python3.10/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken
Required-by: 
```

### What Python version are you running this with?

`Python 3.10.9`

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
-e <email> -p <password>` (with proper login credentials).
```

### Console logs

```Shell
ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
Hello!

ChatGPT:
error: Unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 372, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 361, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/usr/lib/python3.10/site-packages/revChatGPT/./V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```
```


### Additional information

_No response_

**Comment by AdjointOperator** [comment]
Most likely, the default proxy server is down. The error code is 404.
Would be interested in hosting one... if the source becomes available at some point again.

**Comment by lss233** [comment]
V2 is no longer working. https://github.com/acheong08/ChatGPT/issues/737#issuecomment-1429942858

**Comment by acheong08** [comment]
> Most likely, the default proxy server is down. The error code is 404. Would be interested in hosting one... if the source becomes available at some point again.

The whole method is unavailable due to OpenAI
