### ISSUE TITLE
[Bug]: 502 Bad Gateway in V2.2.1

### ISSUE THREAD

**Issue by vegaviazhang** [acheong08/ChatGPT#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

the 502 error appear

### 1.`pip list`
```shell
(vega_gpt_chatbot) zhangx@pve-gpu:~/a_project/ChatGPT_2023/chatgpt_acheong08_ChatGPT$ pip list
Package            Version
------------------ ----------
aiohttp            3.8.3
aiosignal          1.3.1
anyio              3.6.2
async-timeout      4.0.2
asyncio            3.4.3
attrs              22.2.0
blobfile           2.0.1
certifi            2022.12.7
charset-normalizer 2.1.1
filelock           3.9.0
frozenlist         1.3.3
h11                0.14.0
httpcore           0.16.3
httpx              0.23.3
idna               3.4
lxml               4.9.2
multidict          6.0.4
openai             0.26.0
OpenAIAuth         0.2.0
pip                22.3.1
psutil             5.8.0
pyapollos          0.1.5
pycryptodomex      3.17
regex              2022.10.31
requests           2.28.1
revChatGPT         2.2.1
rfc3986            1.5.0
setuptools         65.5.0
sniffio            1.3.0
socksio            1.0.0
tiktoken           0.2.0
tls-client         0.1.8
tornado            6.0.4
tqdm               4.64.1
urllib3            1.26.13
wheel              0.37.1
yarl               1.8.2

```
### 2.config the config. `mkdir -p $HOME/.config/revChatGPT/ && vim $HOME/.config/revChatGPT/config.json`
```shell
(vega_gpt_chatbot) zhangx@pve-gpu:~/a_project/ChatGPT_2023/chatgpt_acheong08_ChatGPT$ vim $HOME/.config/revChatGPT/config.json
```

### 3.`python3 -m revChatGPT.V1`
```shell
(vega_gpt_chatbot) zhangx@pve-gpu:~/a_project/ChatGPT_2023/chatgpt_acheong08_ChatGPT$ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
如何训练自己的chatgpt

Chatbot:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

Traceback (most recent call last):
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/site-packages/revChatGPT/V1.py", line 395, in <module>
    main(configure())
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/site-packages/revChatGPT/V1.py", line 375, in main
    for data in chatbot.ask(
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/site-packages/revChatGPT/V1.py", line 142, in ask
    self.__check_response(response)
  File "/home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/site-packages/revChatGPT/V1.py", line 192, in __check_response
    raise error
__main__.Error
```

### What should have happened?

the response is the answer in normal.

### Version where the problem happens

```shell
(vega_gpt_chatbot) zhangx@pve-gpu:~/a_project/ChatGPT_2023/chatgpt_acheong08_ChatGPT$ python3 -m pip show revChatGPT
Name: revChatGPT
Version: 2.2.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/zhangx/anaconda3/envs/vega_gpt_chatbot/lib/python3.9/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken
Required-by:
```

### What Python version are you running this with?

Python 3.9.15

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
the log is in the step, thanks.
```

**Comment by lss233** [comment]
Use latest version.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.2.3

**Comment by vegaviazhang** [comment]
> ok，thanks, I have a try.

it works.
