### ISSUE TITLE
[Bug]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 84, in <module>
    asyncio.run(main(prompt, username))
  File "/usr/local/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 56, in main
    for data in response:
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1.py", line 154, in ask
    response = self.session.post(
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Steps to reproduce the problem

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 84, in <module>
    asyncio.run(main(prompt, username))
  File "/usr/local/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 56, in main
    for data in response:
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1.py", line 154, in ask
    response = self.session.post(
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### What should have happened?

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 84, in <module>
    asyncio.run(main(prompt, username))
  File "/usr/local/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 56, in main
    for data in response:
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1.py", line 154, in ask
    response = self.session.post(
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Version where the problem happens

2.2.4

### What Python version are you running this with?

3.10.4

### Command Line Arguments

```Shell
python3 -m revChatGPT.V1
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 84, in <module>
    asyncio.run(main(prompt, username))
  File "/usr/local/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_v3.py", line 56, in main
    for data in response:
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1.py", line 154, in ask
    response = self.session.post(
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by Metal-joker** [comment]
This occurs to me too, seems like the proxy server is down

**Comment by acheong08** [comment]
Proxy server is blocked in China

**Comment by vpegasus** [comment]
The same issue I occurred, but a bit of difference:
when I run `python3 -m revChatGPT.V1`, everything run normally. However,  when I write codes in `ipython` something goes wrong:  ` from revChatGPT.V1 import Chatbot` and `chatbot = Chatbot(config=cfg) # cfg: the same configure as $HOME/.config/revChatGPT/config.json` .

**Comment by vpegasus** [comment]
> The same issue I occurred, but a bit of difference: (I ran) (My server was located in Singapore) `python3 -m revChatGPT.V1`, everything ran normally. However, when I write codes in `ipython` something went wrong: ` from revChatGPT.V1 import Chatbot` and `chatbot = Chatbot(config=cfg) # cfg: the same configure as $HOME/.config/revChatGPT/config.json` . ran properly. when ran:
> 
> ```python
> print("Chatbot: ")
> prev_text = ""
> for data in chatbot.ask(
>     "Hello world",
> ):
>     message = data["message"][len(prev_text) :]
>     print(message, end="", flush=True)
>     prev_text = data["message"]
> print()
> ```
> 
> got error:
> 
> ```python
> print("Chatbot: ")
>    ...: prev_text = ""
>    ...: for data in chatbot.ask(
>    ...:     "Hello world",
>    ...: ):
>    ...:     message = data["message"][len(prev_text) :]
>    ...:     print(message, end="", flush=True)
>    ...:     prev_text = data["message"]
>    ...: print()
> Chatbot: 
> 
> ---------------------------------------------------------------------------
> RemoteDisconnected                        Traceback (most recent call last)
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     702 # Make the request on the httplib connection object.
> --> 703 httplib_response = self._make_request(
>     704     conn,
>     705     method,
>     706     url,
>     707     timeout=timeout_obj,
>     708     body=body,
>     709     headers=headers,
>     710     chunked=chunked,
>     711 )
>     713 # If we're going to release the connection in ``finally:``, then
>     714 # the response doesn't need to know about the connection. Otherwise
>     715 # it will also try to release it and we'll have a double-release
>     716 # mess.
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:449, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     445         except BaseException as e:
>     446             # Remove the TypeError from the exception chain in
>     447             # Python 3 (including for exceptions like SystemExit).
>     448             # Otherwise it looks like a bug in the code.
> --> 449             six.raise_from(e, None)
>     450 except (SocketTimeout, BaseSSLError, SocketError) as e:
> 
> File <string>:3, in raise_from(value, from_value)
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:444, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     443 try:
> --> 444     httplib_response = conn.getresponse()
>     445 except BaseException as e:
>     446     # Remove the TypeError from the exception chain in
>     447     # Python 3 (including for exceptions like SystemExit).
>     448     # Otherwise it looks like a bug in the code.
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:1348, in HTTPConnection.getresponse(self)
>    1347 try:
> -> 1348     response.begin()
>    1349 except ConnectionError:
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:316, in HTTPResponse.begin(self)
>     315 while True:
> --> 316     version, status, reason = self._read_status()
>     317     if status != CONTINUE:
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:285, in HTTPResponse._read_status(self)
>     282 if not line:
>     283     # Presumably, the server closed the connection before
>     284     # sending a valid response.
> --> 285     raise RemoteDisconnected("Remote end closed connection without"
>     286                              " response")
>     287 try:
> 
> RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> ProtocolError                             Traceback (most recent call last)
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/requests/adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
>     488 if not chunked:
> --> 489     resp = conn.urlopen(
>     490         method=request.method,
>     491         url=url,
>     492         body=request.body,
>     493         headers=request.headers,
>     494         redirect=False,
>     495         assert_same_host=False,
>     496         preload_content=False,
>     497         decode_content=False,
>     498         retries=self.max_retries,
>     499         timeout=timeout,
>     500     )
>     502 # Send the request.
>     503 else:
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:787, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     785     e = ProtocolError("Connection aborted.", e)
> --> 787 retries = retries.increment(
>     788     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>     789 )
>     790 retries.sleep()
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py:550, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
>     549 if read is False or not self._is_method_retryable(method):
> --> 550     raise six.reraise(type(error), error, _stacktrace)
>     551 elif read is not None:
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py:769, in reraise(tp, value, tb)
>     768 if value.__traceback__ is not tb:
> --> 769     raise value.with_traceback(tb)
>     770 raise value
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     702 # Make the request on the httplib connection object.
> --> 703 httplib_response = self._make_request(
>     704     conn,
>     705     method,
>     706     url,
>     707     timeout=timeout_obj,
>     708     body=body,
>     709     headers=headers,
>     710     chunked=chunked,
>     711 )
>     713 # If we're going to release the connection in ``finally:``, then
>     714 # the response doesn't need to know about the connection. Otherwise
>     715 # it will also try to release it and we'll have a double-release
>     716 # mess.
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:449, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     445         except BaseException as e:
>     446             # Remove the TypeError from the exception chain in
>     447             # Python 3 (including for exceptions like SystemExit).
>     448             # Otherwise it looks like a bug in the code.
> --> 449             six.raise_from(e, None)
>     450 except (SocketTimeout, BaseSSLError, SocketError) as e:
> 
> File <string>:3, in raise_from(value, from_value)
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py:444, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     443 try:
> --> 444     httplib_response = conn.getresponse()
>     445 except BaseException as e:
>     446     # Remove the TypeError from the exception chain in
>     447     # Python 3 (including for exceptions like SystemExit).
>     448     # Otherwise it looks like a bug in the code.
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:1348, in HTTPConnection.getresponse(self)
>    1347 try:
> -> 1348     response.begin()
>    1349 except ConnectionError:
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:316, in HTTPResponse.begin(self)
>     315 while True:
> --> 316     version, status, reason = self._read_status()
>     317     if status != CONTINUE:
> 
> File /data/data/soft/miniconda3/lib/python3.8/http/client.py:285, in HTTPResponse._read_status(self)
>     282 if not line:
>     283     # Presumably, the server closed the connection before
>     284     # sending a valid response.
> --> 285     raise RemoteDisconnected("Remote end closed connection without"
>     286                              " response")
>     287 try:
> 
> ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> ConnectionError                           Traceback (most recent call last)
> Cell In[5], line 3
>       1 print("Chatbot: ")
>       2 prev_text = ""
> ----> 3 for data in chatbot.ask(
>       4     "Hello world",
>       5 ):
>       6     message = data["message"][len(prev_text) :]
>       7     print(message, end="", flush=True)
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/revChatGPT/V1.py:157, in Chatbot.ask(self, prompt, conversation_id, parent_id)
>     153 self.conversation_id_prev_queue.append(
>     154     data["conversation_id"],
>     155 )  # for rollback
>     156 self.parent_id_prev_queue.append(data["parent_message_id"])
> --> 157 response = self.session.post(
>     158     url=BASE_URL + "api/conversation",
>     159     data=json.dumps(data),
>     160     timeout=360,
>     161     stream=True,
>     162 )
>     163 self.__check_response(response)
>     164 for line in response.iter_lines():
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/requests/sessions.py:635, in Session.post(self, url, data, json, **kwargs)
>     624 def post(self, url, data=None, json=None, **kwargs):
>     625     r"""Sends a POST request. Returns :class:`Response` object.
>     626 
>     627     :param url: URL for the new :class:`Request` object.
>    (...)
>     632     :rtype: requests.Response
>     633     """
> --> 635     return self.request("POST", url, data=data, json=json, **kwargs)
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/requests/sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     582 send_kwargs = {
>     583     "timeout": timeout,
>     584     "allow_redirects": allow_redirects,
>     585 }
>     586 send_kwargs.update(settings)
> --> 587 resp = self.send(prep, **send_kwargs)
>     589 return resp
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/requests/sessions.py:701, in Session.send(self, request, **kwargs)
>     698 start = preferred_clock()
>     700 # Send the request
> --> 701 r = adapter.send(request, **kwargs)
>     703 # Total elapsed time of the request (approximately)
>     704 elapsed = preferred_clock() - start
> 
> File /data/data/soft/miniconda3/lib/python3.8/site-packages/requests/adapters.py:547, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
>     544             raise
>     546 except (ProtocolError, OSError) as err:
> --> 547     raise ConnectionError(err, request=request)
>     549 except MaxRetryError as e:
>     550     if isinstance(e.reason, ConnectTimeoutError):
>     551         # TODO: Remove this in 3.0.0: see #2811
> 
> ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> ```

I didn't nothing, but it's OK now.  confusing...

**Comment by KLED-dj** [comment]
我在美国的服务器也出现了这种情况

**Comment by Metal-joker** [comment]
@vpegasus maybe you should collapse your error stack trace, I can bearly find your words now.

BTW, im still facing this error, and it have worked several times 2 hours ago.

**Comment by KyleZhang0536** [comment]
https://chatgpt-proxy2.fly.dev/ works

**Comment by Metal-joker** [comment]
> https://chatgpt-proxy2.fly.dev/ works modify V1.py , line 19

this works for me, thx

**Comment by CodeSPA** [comment]
> > https://chatgpt-proxy2.fly.dev/ works modify V1.py , line 19
> 
> this works for me, thx

it still doesn't work for me

**Comment by zxj1009587922** [comment]
仅有用一会，第二次就又报错了

**Comment by acheong08** [comment]
Fixed

**Comment by acheong08** [comment]
Please update https://github.com/acheong08/ChatGPT/releases/tag/2.2.7

**Comment by skarl-api** [comment]
@acheong08 BASE_URL 这个后端服务的源码方便发布一下吗？想看一下背后的逻辑，自己尝试过很多次 直接模拟GPT发消息接口但始终都是403

**Comment by acheong08** [comment]
> @acheong08 BASE_URL 这个后端服务的源码方便发布一下吗？想看一下背后的逻辑，自己尝试过很多次 直接模拟GPT发消息接口但始终都是403

https://github.com/acheong08/ChatGPT-Proxy-V1

`config.json`不再：阻止OpenAI把方式给🔓

**Comment by skarl-api** [comment]
> > @acheong08 BASE_URL 这个后端服务的源码方便发布一下吗？想看一下背后的逻辑，自己尝试过很多次 直接模拟GPT发消息接口但始终都是403
> 
> https://github.com/acheong08/ChatGPT-Proxy-V1
> 
> `config.json`不再：阻止OpenAI把方式给🔓


牛B，兄弟
