### ISSUE TITLE
revChatGPT.V1.Error 、 version: revChatGPT - 2.3.0 

### ISSUE THREAD

**Issue by yuzyf** [acheong08/ChatGPT#799]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./main.py", line 28, in chatGpt
    for data in chatbot.ask(questions.msg):
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 161, in ask
    self.__check_response(response)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 213, in __check_response
    raise error
revChatGPT.V1.Error

这个应该如何操作呢

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by woltium** [comment]
同样的问题 希望作者能开放捐赠渠道 愿意支持作者把项目维护地更稳定一些

**Comment by yuzyf** [comment]
> 同样的问题 希望作者能开放捐赠渠道 愿意支持作者把项目维护地更稳定一些

支持

**Comment by dawhdb** [comment]
Hello, some sentences that are too long will get truncated in the middle, no request is returned, and is there a place to set the max_tokens parameter

**Comment by acheong08** [comment]
Server got overloaded again. Will add even more droplets to the pool

**Comment by acheong08** [comment]
> 同样的问题 希望作者能开放捐赠渠道 愿意支持作者把项目维护地更稳定一些

GitHub sponsorships are blocked in Malaysia for now. I'll try to get a donation channel via Patreon or something for running the servers after my exams next week. If this V1 method keeps working I might actually just publish the code properly and assume OpenAI won't notice

**Comment by acheong08** [comment]
Fixed
