### ISSUE TITLE
[Bug]: 32bit issue?

### ISSUE THREAD

**Issue by Worrah** [acheong08/ChatGPT#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Tried to run this on 32bit raspberry pi and got this error:

```
Traceback (most recent call last):
  File "/home/wolh/lupus/chatgpt.py", line 1, in <module>
    from revChatGPT.V1 import Chatbot
  File "/home/wolh/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 11, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth
  File "/home/wolh/.local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 5, in <module>
    import tls_client
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/cffi.py", line 20, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/wolh/.local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```
 any hint?

### Steps to reproduce the problem

run the code on 32bit system

### What should have happened?

All works on 64bit

### Version where the problem happens

 revchatgpt-2.3.0

### What Python version are you running this with?

3.9.2

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell

Building wheels for collected packages: tiktoken
  Building wheel for tiktoken (pyproject.toml) ... done
  Created wheel for tiktoken: filename=tiktoken-0.2.0-cp39-cp39-linux_armv7l.whl size=1558627 sha256=738f73ccc0045fe1d6651d997557c6812ceb0bcacd34e204b2097f2b14b4f5da
  Stored in directory: /home/wolh/.cache/pip/wheels/3e/ea/d3/31709318664ae93f27151c4067b0cb5018e39c1475ae856e3a
Successfully built tiktoken
Installing collected packages: tls-client, rfc3986, asyncio, socksio, sniffio, regex, pycryptodomex, OpenAIAuth, lxml, h11, filelock, blobfile, anyio, tiktoken, httpcore, httpx, revchatgpt
Successfully installed OpenAIAuth-0.2.0 anyio-3.6.2 asyncio-3.4.3 blobfile-2.0.1 filelock-3.9.0 h11-0.14.0 httpcore-0.16.3 httpx-0.23.3 lxml-4.9.2 pycryptodomex-3.17 regex-2022.10.31 revchatgpt-2.3.0 rfc3986-1.5.0 sniffio-1.3.0 socksio-1.0.0 tiktoken-0.2.0 tls-client-0.1.8

$ python chatgpt.py

Traceback (most recent call last):
  File "/home/wolh/lupus/chatgpt.py", line 1, in <module>
    from revChatGPT.V1 import Chatbot
  File "/home/wolh/.local/lib/python3.9/site-packages/revChatGPT/V1.py", line 11, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth
  File "/home/wolh/.local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 5, in <module>
    import tls_client
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/home/wolh/.local/lib/python3.9/site-packages/tls_client/cffi.py", line 20, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/wolh/.local/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```

**Comment by acheong08** [comment]
32-bit not supported by OpenAIAuth. If you must, you need to remove the authentication code and use only access tokens

**Comment by Worrah** [comment]
> 32-bit not supported by OpenAIAuth. If you must, you need to remove the authentication code and use only access tokens

but i am using the access token with the code like this:

```
from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "access_token":  TOKEN
})

prompt = "how many beaches does portugal have?"
response = ""

for data in chatbot.ask(
  prompt
):
    response = data["message"]

print(response)
```

**Comment by acheong08** [comment]
Need to remove the authentication code from the library completely

**Comment by Worrah** [comment]
> Need to remove the authentication code from the library completely

oh. now it works fine, thank you

**Comment by acheong08** [comment]
32 bit now supported on the latest release.

**Comment by acheong08** [comment]
I rewrote https://github.com/acheong08/OpenAIAuth just to fix this issue lol
