### ISSUE TITLE
[Bug]: V2 doesn't work

### ISSUE THREAD

**Issue by Beniamiiin** [acheong08/ChatGPT#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm trying to use Chatbot V2:

```python
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(
        email="...",
        password="...",
        paid=True
    )
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush=True)
    print()


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

But I get an error:
```
Traceback (most recent call last):
  File ".../app.py", line 1, in <module>
    from revChatGPT.V2 import Chatbot
  File ".../.venv/lib/python3.11/site-packages/revChatGPT/V2.py", line 12, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth
ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package
```

I tried to replace: `from OpenAIAuth.OpenAIAuth import OpenAIAuth`
with this: `from OpenAIAuth import Authenticator`
and this: `OpenAIAuth(email_address=email, password=password, proxy=proxy)`
with this: `Authenticator(email_address=email, password=password, proxy=proxy)`
then I get an error:
```
error: Unknown error
Traceback (most recent call last):
  File "/Users/be.sarkisyan/Projects/story_generator/app.py", line 18, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".../story_generator/app.py", line 10, in main
    async for line in chatbot.ask("Hello"):
  File ".../.venv/lib/python3.11/site-packages/revChatGPT/V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```

### Version where the problem happens

Name: revChatGPT
Version: 2.3.3
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: .../.venv/lib/python3.11/site-packages
Requires: OpenAIAuth, requests
Required-by:

### What Python version are you running this with?

Python 3.11.2

### What is your operating system ?

MacOS

**Comment by stevensyp** [comment]
The V2 is currently down/under maintenance (see [README#V2](https://github.com/acheong08/ChatGPT#under-maintenance)), you can use V1 instead.

**Comment by Beniamiiin** [comment]
Oh, my mistake, thank you.
