### ISSUE TITLE
OpenAIAuth.Error

### ISSUE THREAD

**Issue by tuangtalk** [acheong08/ChatGPT#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "email": "myemail",
  "password": "mypasswoed",
  "proxy": "http://127.0.0.1:20235"
})

prompt = "hi"
response = ""

for data in chatbot.ask(
  prompt
):response = data["message"]
    

print(response) 

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

get response

### Version where the problem happens

revChatGPT-2.3.4
OpenAIAuth==0.3.2

### What Python version are you running this with?

python3.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/config/workspace/chagpttest/test.py", line 3, in <module>
    chatbot = Chatbot(config={
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 68, in __init__
    raise error
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 66, in __init__
    self.__login()
  File "/usr/local/lib/python3.10/dist-packages/revChatGPT/V1.py", line 102, in __login
    auth.begin()
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/usr/local/lib/python3.10/dist-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error
```

**Comment by yubuyuabc** [comment]
me too

**Comment by davideuler** [comment]
Also got this error.

**Comment by tuangtalk** [comment]
chatgpt 官方网站挂了，等恢复吧
