### ISSUE TITLE
[Bug]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Read timed out. (read timeout=360)

### ISSUE THREAD

**Issue by QAQLemon233** [acheong08/ChatGPT#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

直接使用提供的Basic example (single result)代码出现如下错误。
此外，在出现该错误之前，该代码成功运行过一次并给出了正确的结果，但仅此这一次正常。

Traceback (most recent call last):
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl      
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    response = self.session.post(
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\SweetLemon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Read timed out. (read timeout=360)

### Steps to reproduce the problem

正常运行实例代码

### What should have happened?

像第一次一样正常运行

### Version where the problem happens

2.3.4

### What Python version are you running this with?

3.10.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Read timed out. (read timeout=360)
```

**Comment by acheong08** [comment]
OpenAI was down. It's back up
