### ISSUE TITLE
[Bug]:  OpenAIAuth.Error

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_2.3.4.py", line 41, in <module>
    chatbot = Chatbot(config={
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 68, in __init__
    raise error
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 66, in __init__
    self.__login()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 102, in __login
    auth.begin()
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error

### Steps to reproduce the problem

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_2.3.4.py", line 41, in <module>
    chatbot = Chatbot(config={
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 68, in __init__
    raise error
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 66, in __init__
    self.__login()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 102, in __login
    auth.begin()
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error

### What should have happened?

Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_2.3.4.py", line 41, in <module>
    chatbot = Chatbot(config={
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 68, in __init__
    raise error
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 66, in __init__
    self.__login()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 102, in __login
    auth.begin()
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error

### Version where the problem happens

Name: revChatGPT
Version: 2.3.4
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/python3/lib/python3.10/site-packages
Requires: OpenAIAuth, requests

### What Python version are you running this with?

Python 3.10.5

### Command Line Arguments

```Shell
chatbot = Chatbot(config={
    "email": "{}".format('1234@163.com'),
    "password": "{}".format('123456'),
    "paid": "{}".format(True)
})
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/data/chatgpt/chatgpt-asyncio/bin/chatgpt_asyncio_2.3.4.py", line 41, in <module>
    chatbot = Chatbot(config={
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 68, in __init__
    raise error
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 66, in __init__
    self.__login()
  File "/data/chatgpt/chatgpt-asyncio/bin/revChatGPT/V1_234.py", line 102, in __login
    auth.begin()
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/usr/local/python3/lib/python3.10/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error
```

**Comment by acheong08** [comment]
Getting same. I will reverse engineer again tomorrow

**Comment by acheong08** [comment]
For now use access token or session tokens

**Comment by acheong08** [comment]
Unified thread: https://github.com/acheong08/ChatGPT/issues/846

**Comment by kof4467** [comment]
Who knows how long the session_token is valid for?

**Comment by acheong08** [comment]
session_token validity is a variable. access_token is known to be 2 weeks

**Comment by kof4467** [comment]
> session_token validity is a variable. access_token is known to be 2 weeks

Thanks

**Comment by Kunlun-Zhu** [comment]
> For now use access token or session tokens
may I ask how to use access token or session tokens?
