### ISSUE TITLE
Authentication bugs

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#846]
Tracking here
- https://github.com/acheong08/ChatGPT/issues/838
- https://github.com/acheong08/ChatGPT/issues/839
- https://github.com/acheong08/ChatGPT/issues/795
- https://github.com/acheong08/ChatGPT/issues/835

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/issues/845

**Comment by SnapdragonLee** [comment]
I found that if I delete access_tokens key in config, then I can use it normally.

**Comment by acheong08** [comment]
Yes. They are mutually exclusive. You can't put both access_token and email/password at the same time

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by AlexandreLrz** [comment]
I have the same issue using console or developer API.

This one when using access_token :

`NoneType: None
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    for data in chatbot.ask(prompt):
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 277, in ask
    raise Error(source="ask", message="Field missing", code=1)
revChatGPT.V1.Error`

And this one using password/email : 

`Traceback (most recent call last):
  File "test.py", line 3, in <module>
    chatbot = Chatbot(config={
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 42, in wrapper
    out = func(*args, **kwargs)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 110, in __init__
    self.__check_credentials()
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 42, in wrapper
    out = func(*args, **kwargs)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 124, in __check_credentials
    self.__login()
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 42, in wrapper
    out = func(*args, **kwargs)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/revChatGPT/V1.py", line 165, in __login
    auth.begin()
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 298, in __part_seven
    self.get_access_token()
  File "/Users/alexlrz/opt/anaconda3/lib/python3.8/site-packages/OpenAIAuth.py", line 318, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'`

**Comment by andybenichou** [comment]
Hi, is there a fix? I have the same error

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by acheong08** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.

**Comment by Adefey** [comment]
Hello, I get the same error:
 OpenAI: {"detail":{"message":"Unauthorized - Invalid access token"}} (code: 401)
I have double checked my token, it is in correct format (no < > around it and it starts with sk-)

**Comment by acheong08** [comment]
Please read the wiki. If you're trying to use API keys, use V3

**Comment by Adefey** [comment]
Yes, sorry, I used the wrong token
