### ISSUE TITLE
[Feature Request]: Implementation for WebChatGPT

### ISSUE THREAD

**Issue by LuckyHead11** [acheong08/ChatGPT#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have just come across the GitHub page: https://github.com/qunash/chatgpt-advanced ChatGPT-Advanced or WebChatGPT.
The title is self-explanatory and gives ChatGPT access to the web similar to what BingGPT does through a Chrome Extension. I would like to know if you can implement something like it.
This is what it does:
1. Searches google and looks for relevant info.
2. Changes the user's prompt to something like this: With the prompt being **_What is the ChatGPT Github page by acheong all about?_**
![Screenshot 2023-02-21 171235](https://user-images.githubusercontent.com/93405290/220480793-659eadd7-76d3-47a0-a1fc-e50457e49e74.png)
![Screenshot 2023-02-21 171814](https://user-images.githubusercontent.com/93405290/220480808-f92c14cb-f6fa-477d-a991-e4130527fc28.png)

You can ask directly to @qunash if you can implement or share code.
Or you can copy the idea and make a similar feature to the API.

### Proposed workflow

When you initialize the ChatBot in python you would simply add a "**web**" parameter. Which could be equal to **True** or **False**.

**Comment by acheong08** [comment]
It'll take some time. I'll try to implement this next week when my mock exams are over

**Comment by acheong08** [comment]
@f1nniboy has something similar to this as well. I'll ask him to share source code.

**Comment by LuckyHead11** [comment]
Alright thank you for considering!

**Comment by wlc002** [comment]
good idea!

**Comment by LuckyHead11** [comment]
Thanks! I didn't really come up with the idea for WebChatGPT at first. I just thought it would be cool to see it here.

**Comment by boxiyang** [comment]
pynecone has something similar to the request, with local users and questions/answers management. You can take it as a reference. 
https://github.com/pynecone-io/pynecone-examples/tree/main/gpt

**Comment by noseon** [comment]
I just reverse engineered the plugin and switched to python below. you can put it in code with a simple function.
https://github.com/noseon/WebChatGPT-/blob/main/WebChatGPT%20.py

**Comment by LuckyHead11** [comment]
@noseon that is very impressing!

**Comment by NymdaFromSalad** [comment]
Haha, i also reverse-engineered it for my project. Should've looked into issues earlier, could've been first :)

**Comment by LuckyHead11** [comment]
@NymdaFromSalad is it on a GitHub repo?

**Comment by acheong08** [comment]
> I just reverse engineered the plugin and switched to python below. you can put it in code with a simple function. [noseon/WebChatGPT-@`main`/WebChatGPT%20.py](https://github.com/noseon/WebChatGPT-/blob/main/WebChatGPT%20.py?rgh-link-date=2023-02-25T18%3A04%3A19Z)

I would rather not use a third party API. I wrote my own DuckDuckGo scraper API today in Go: https://github.com/acheong08/DuckDuckGo-API

**Comment by acheong08** [comment]
As a side note, this will probably be a separate repository rather than part of this one.

I feel that an API would be most suitable for this rather than a Python library

**Comment by LuckyHead11** [comment]
Sounds great!

**Comment by NymdaFromSalad** [comment]
@LuckyHead11 No. It's here :) :
```Python
import requests, time

def apiSearch(query: str, numResults: int, timePeriod: str='', region: str=''):

    searchParams = ''
    searchParams += f'q={query}'
    searchParams += f'&max_results={numResults}'
    if timePeriod:
        searchParams += f'&time={timePeriod}'
    if region:
        searchParams += f'&region={region}'

    url = f'https://ddg-webapp-aagd.vercel.app/search?{searchParams}'

    response = requests.get(url)

    results = response.json()

    return results

def prepare_results(results):
    i=1
    res = ""
    for result in results:
        res+=f'[{i}] "{result["body"]}"\nURL: {result["href"]}\n\n'
        i+=1
    return res

def headers(results):
    res = []
    for result in results:
        #res.append({'text':f'[{i}] {result["title"]}', 'link':result["href"]})
        res.append(result["href"])
    return res

def compile_prompt(prompt, results, reply_in = 'language of the query'):
    return f'''Web search results:

{prepare_results(results)}
Current date: {time.strftime("%d.%m.%Y")}

Instructions: Using the provided web search results, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided search results refer to multiple subjects with the same name, write separate answers for each subject.
Query: {prompt}
Reply in {reply_in}'''

def Webify(text:str, query: str, numResults: int, timePeriod: str='', region: str='', reply_in: str='undefined'):
    searchResults = apiSearch(query, numResults, timePeriod, region)
    return compile_prompt(text, searchResults, reply_in), headers(searchResults)

if __name__ == '__main__':
    print(Webify('Testing', 3))
```
text and query are separate, 'cause i also wanted to do other filters, which can add instructions

**Comment by LuckyHead11** [comment]
Awesome! @NymdaFromSalad
@acheong08 with the code provided by Nymda implementing the Web/ChatGPT mix should be easy. Unless you would like to create your own way of using the web with ChatGPT ;)

**Comment by noseon** [comment]
> @LuckyHead11Não. Está aqui :) :
> 
> ```python
> import requests, time
> 
> def apiSearch(query: str, numResults: int, timePeriod: str='', region: str=''):
> 
>     searchParams = ''
>     searchParams += f'q={query}'
>     searchParams += f'&max_results={numResults}'
>     if timePeriod:
>         searchParams += f'&time={timePeriod}'
>     if region:
>         searchParams += f'&region={region}'
> 
>     url = f'https://ddg-webapp-aagd.vercel.app/search?{searchParams}'
> 
>     response = requests.get(url)
> 
>     results = response.json()
> 
>     return results
> 
> def prepare_results(results):
>     i=1
>     res = ""
>     for result in results:
>         res+=f'[{i}] "{result["body"]}"\nURL: {result["href"]}\n\n'
>         i+=1
>     return res
> 
> def headers(results):
>     res = []
>     for result in results:
>         #res.append({'text':f'[{i}] {result["title"]}', 'link':result["href"]})
>         res.append(result["href"])
>     return res
> 
> def compile_prompt(prompt, results, reply_in = 'language of the query'):
>     return f'''Web search results:
> 
> {prepare_results(results)}
> Current date: {time.strftime("%d.%m.%Y")}
> 
> Instructions: Using the provided web search results, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided search results refer to multiple subjects with the same name, write separate answers for each subject.
> Query: {prompt}
> Reply in {reply_in}'''
> 
> def Webify(text:str, query: str, numResults: int, timePeriod: str='', region: str='', reply_in: str='undefined'):
>     searchResults = apiSearch(query, numResults, timePeriod, region)
>     return compile_prompt(text, searchResults, reply_in), headers(searchResults)
> 
> if __name__ == '__main__':
>     print(Webify('Testing', 3))
> ```
> 
> texto e consulta são separados, porque eu também queria fazer outros filtros, que podem adicionar instruções
> 
> Além disso, se você está vagando, por que a função é chamada de cabeçalhos, é porque no meu idioma nativo, manchetes, títulos e cabeçalhos significam o mesmo

and that's how it works

**Comment by acheong08** [comment]
Also need a mechanism for it to detect whether to search or not and convert natural language to a search query

**Comment by NymdaFromSalad** [comment]
> Also need a mechanism for it to detect whether to search or not and convert natural language to a search query 

Well, that's natural language processing and it is hard. Simplest solution would be to require user press the button and either using the whole query as the search parameter, or asking user for a search term. Honestly, forgot to check if WebGPT has any other mechanism. If it does - well, i need to reverse engineer it either way.

Also you can ask ChatGPT to do NLP, as it is NLM :)

**Comment by LuckyHead11** [comment]
> Also need a mechanism for it to detect whether to search or not and convert natural language to a search query

we could use a different package, like for V1: revChatGPT.V1 But for the web access one would be revChatGPT.V1_WEB
or when you do `chatbot.ask` it would have a web parameter as I said in the beginning.

**Comment by NymdaFromSalad** [comment]
> > Also need a mechanism for it to detect whether to search or not and convert natural language to a search query
> 
> we could use a different package, like for V1: revChatGPT.V1 But for the web access one would be revChatGPT.V1_WEB or when you do `chatbot.ask` it would have a web parameter as I said in the beginning.

Oh, in that sense? Then:

0) Needs better name, .webaccess .web or .webgpt are my picks
1) You can create a web-accessing bot class, and either pass it chatbot object, or create internal chatbot instances, then it'll have additional functions to process web stuff and retain the OG ones

I dunno, i have some time on the weekend (and need to take a break from my personal project's SQL hijinx), if you guys want, i can make it (and do something i never done before - write decent code)

(Also, will try and use duckduckgo, as putting feature, that uses other people's (who do opensource, might i add) private servers without their consent into a library is not very nice. We only do it to evil corporations)

**Comment by LuckyHead11** [comment]
> > > Also need a mechanism for it to detect whether to search or not and convert natural language to a search query
> > 
> > 
> > we could use a different package, like for V1: revChatGPT.V1 But for the web access one would be revChatGPT.V1_WEB or when you do `chatbot.ask` it would have a web parameter as I said in the beginning.
> 
> Oh, in that sense? Then:
> 
> 0. Needs better name, .webaccess .web or .webgpt are my picks
> 1. You can create a web-accessing bot class, and either pass it chatbot object, or create internal chatbot instances, then it'll have additional functions to process web stuff and retain the OG ones
> 
> I dunno, i have some time on the weekend (and need to take a break from my personal project's SQL hijinx), if you guys want, i can make it (and do something i never done before - write decent code)
> 
> (Also, will try and use duckduckgo, as putting feature, that uses other people's (who do opensource, might i add) private servers without their consent into a library is not very nice. We only do it to evil corporations)

Good Ideas! It's up to @acheong08 if you should make it.

**Comment by NymdaFromSalad** [comment]
Well, if you guys wanna use it, either way, it'll be time well spent

**Comment by acheong08** [comment]
> (Also, will try and use duckduckgo, as putting feature, that uses other people's (who do opensource, might i add) private servers without their consent into a library is not very nice. We only do it to evil corporations)

There is no need for that. I already wrote my own API for it and currently hosting on Heroku for testing https://github.com/acheong08/DuckDuckGo-API

**Comment by acheong08** [comment]
> I dunno, i have some time on the weekend 

Let me know if you do. There's no point in duplicating efforts.

**Comment by acheong08** [comment]
I prefer scraping locally

**Comment by acheong08** [comment]
I just wrote the API because I couldn't figure out how to scrape reliably locally

**Comment by acheong08** [comment]
I just misunderstood

**Comment by acheong08** [comment]
No way I want more traffic lol. I don't want to pay for that

**Comment by acheong08** [comment]
So are you gonna work on this?

**Comment by LuckyHead11** [comment]
> I just wrote the API because I couldn't figure out how to scrape reliably locally in Python.

How is python unreliable?

**Comment by acheong08** [comment]
> > I just wrote the API because I couldn't figure out how to scrape reliably locally in Python.
> 
> How is python unreliable?

Before OpenAI removed captcha from auth0, there were a ton of issues with the bs4 parser, especially lxml. It just doesn't work on some machines and I have no idea why

**Comment by acheong08** [comment]
I ended up moving to just using regex but that's quite finicky

**Comment by LuckyHead11** [comment]
Ah, that makes sense. Will you be making a new repo or just edit this one?

**Comment by acheong08** [comment]
If @NymdaFromSalad is gonna make a good one, I would rather just like their repo in the readme. Otherwise, It'll probably be a new repo

**Comment by NymdaFromSalad** [comment]
> So are you gonna work on this?

Yes

> If @NymdaFromSalad is gonna make a good one, I would rather just like their repo in the readme. Otherwise, It'll probably be a new repo

I was going to make an addition to this repo. Like, i wanted to make a submodule, not a standalone project - i have enough of those

**Comment by NymdaFromSalad** [comment]
I was just made to play mafia (social game) for 3 hours straight, my brain is on cooldown, i am confused

**Comment by NymdaFromSalad** [comment]
Ok, i figured it out. Implementation tomorrow

**Comment by acheong08** [comment]
I added a quick implementation today. I'll publish release later

**Comment by NymdaFromSalad** [comment]
> I added a quick implementation today. I'll publish release later

So, you already did it? Using your server or not?

**Comment by acheong08** [comment]
> So, you already did it? Using your server or not?

A very basic version using my server. It sucks right now lol. It's just for testing

**Comment by NymdaFromSalad** [comment]
> > So, you already did it? Using your server or not?
> 
> A very basic version using my server. It sucks right now lol. It's just for testing

Oh ok, then my idea still stands

**Comment by acheong08** [comment]
> Oh ok, then my idea still stands

yes.

**Comment by LuckyHead11** [comment]
Is the new Web accessed chatgpt only for V3? @acheong08

**Comment by NymdaFromSalad** [comment]
Ok, sorry for my disappearance. I am trying to get off caffeine and got a massive wave of tiredness, and slept all day. Working on V1 implementation RN, almost finished (editing wiki now). After this, will look into V3

**Comment by LuckyHead11** [comment]
Alright! Great, is there any way I could help?

**Comment by NymdaFromSalad** [comment]
> Alright! Great, is there any way I could help?

Certainly! You can get the extension (or just imitate it, which would be even simpler) and try out different prompt templates for it

Note: it should mark references like this[num], or like[num](url). Since both turn to former format in the end, it is preferable (lil faster)

Also, when testing, it stopped putting direct references at all (no idea, why), so make sure it does reference it. Then, post/send me your results

Also also, try different language prompts (and search results)

This will massively help, since such models are all about prompt crafting

**Comment by LuckyHead11** [comment]
> > Alright! Great, is there any way I could help?
> 
> Certainly! You can get the extension (or just imitate it, which would be even simpler) and try out different prompt templates for it
> 
> Note: it should mark references like this[num], or like[num](url). Since both turn to former format in the end, it is preferable (lil faster)
> 
> Also, when testing, it stopped putting direct references at all (no idea, why), so make sure it does reference it. Then, post/send me your results
> 
> Also also, try different language prompts (and search results)
> 
> This will massively help, since such models are all about prompt crafting

The WebChatGPT extension?

**Comment by LuckyHead11** [comment]
@NymdaFromSalad How do I access the new web-enabled ChatGPT?

**Comment by NymdaFromSalad** [comment]
There is a separate class, in separate submodule. I wrote this all in wiki (https://github.com/NymdaFromSalad/ChatGPT-Web/blob/main/wiki/WebGPT.md). Also has an example in the end

Also, if it is for prompt testing, just use the website, the prompt is not runtime editable (well, it's python, so it is, but it is not supposed to be)

**Comment by LuckyHead11** [comment]
@NymdaFromSalad So you want me to see what works, and what doesn't correct?

**Comment by NymdaFromSalad** [comment]
Ehm, no? I wanted you to make up a better prompt which later be used in the library. So, start with default prompt from extension (luckily, it does not hide the full text) so the chatgpt will return desired output. Library is pretty simple, and all testing which i have not done, will be easier to do in the browser, as it is the text added to the prompt which needs testing and maybe improvement

Sorry for verbosity, i just like to make sure, that we are on the same page

**Comment by NymdaFromSalad** [comment]
Ok, created pull request

**Comment by LuckyHead11** [comment]
@NymdaFromSalad I dont wanna sound stupid ;) but you clarify 1 more time what exactly im doing. I understand python I've been working with it for years. I just don't know what you need. I guess???

**Comment by NymdaFromSalad** [comment]
> @NymdaFromSalad I dont wanna sound stupid ;) but you clarify 1 more time what exactly im doing. I understand python I've been working with it for years. I just don't know what you need. I guess???

Don't worry.

1) How the WebChatGPT works is it puts search results and instructions at the start of each Web-enabled ChatGPT query (well, around the query to be precise), lets call the stuff it puts pattern

2) ChatGPT makes no distinction between message generated with WCGPT, and just copy-pasted message (both are just text), so you can use WCGPT to get links to websites (and a starting point) and then edit it

And what i suggested you do is change instructions and how the pattern is laid out, so it gives better results

**Comment by NymdaFromSalad** [comment]
Btw, if you want to help with the python part, you can check my code, specifically the async part, because i have no idea what i am doing there

**Comment by LuckyHead11** [comment]
@

> Btw, if you want to help with the python part, you can check my code, specifically the async part, because i have no idea what i am doing there

Aysnc my weak part... ask ChatGPT 🤣

**Comment by acheong08** [comment]
There are a few problems with V1 async that needs fixing that I haven't gotten around to. Also don't know async well in Python.

**Comment by acheong08** [comment]
Async V1 responses are slower for an unknown reason

**Comment by LuckyHead11** [comment]
@NymdaFromSalad Try this:
```
Instructions: Using the provided web search results, write a comprehensive reply to the given query. Make sure to cite results using [[number](URL)] notation after the reference. If the provided search results refer to multiple subjects with the same name, write separate answers for each subject.
Query: tele-tubbies
```

**Comment by NymdaFromSalad** [comment]
@acheong08 @LuckyHead11 Gentlemen, my honest reaction to out likemindedness:
![stop-async](https://user-images.githubusercontent.com/97845347/222939978-ef0970e2-a423-4be2-b79b-f5319d15d16f.png)

**Comment by NymdaFromSalad** [comment]
> @NymdaFromSalad Try this:
> 
> ```
> Instructions: Using the provided web search results, write a comprehensive reply to the given query. Make sure to cite results using [[number](URL)] notation after the reference. If the provided search results refer to multiple subjects with the same name, write separate answers for each subject.
> Query: tele-tubbies
> ```

Isn't it same what WebChatGPT uses? Because, thanks, but i already used this instruction, so i asked for any improvements on it or alternative queues

**Comment by LuckyHead11** [comment]
@NymdaFromSalad I did some adjustments..

**Comment by LuckyHead11** [comment]
I'll do some more adjustments tommorow.

**Comment by NymdaFromSalad** [comment]
> I'll do some more adjustments tomorrow.

K, thanks

**Comment by LuckyHead11** [comment]
@NymdaFromSalad I've spent some time testing and this prompt works 99% of the time:

Instructions: You are a chatbot that has access to the web. Use the given web results above to write an easy-to-read and straightforward response. Make sure to cite results using [[number(URL)]. Make sure each website has its own section. All I want you to do is summarize the given web results. Don't say "sure" or anything like that. Just get to the point. Don't forget to cite the results with [[number(URL)] 

Query: **Teletubbies**

Make sure that you replace the query with whatever the user asks, and add the current date and time to the end of the chat. Also for this to work make sure to give ChatGPT the URL of the website for each section.

**Comment by NymdaFromSalad** [comment]
> @NymdaFromSalad I've spent some time testing and this prompt works 99% of the time:
> 
> Instructions: You are a chatbot that has access to the web. Use the given web results above to write an easy-to-read and straightforward response. Make sure to cite results using [[number(URL)]. Make sure each website has its own section. All I want you to do is summarize the given web results. Don't say "sure" or anything like that. Just get to the point. Don't forget to cite the results with [[number(URL)] 
> 
> Query: **Teletubbies**
> 
> Make sure that you replace the query with whatever the user asks, and add the current date and time to the end of the chat. Also for this to work make sure to give ChatGPT the URL of the website for each section.
> 

Ok, thank you very much, will use!

**Comment by LuckyHead11** [comment]
@NymdaFromSalad @acheong08  Should I be concerned?:
![Screenshot 2023-03-05 114420](https://user-images.githubusercontent.com/93405290/222976890-da69b6c5-91f7-43df-96a9-73fc9bf8c7e1.png)

**Comment by NymdaFromSalad** [comment]
> @NymdaFromSalad @acheong08  Should I be concerned?:
> ![Screenshot 2023-03-05 114420](https://user-images.githubusercontent.com/93405290/222976890-da69b6c5-91f7-43df-96a9-73fc9bf8c7e1.png)
> 

That's what we call in the industry "good enough"

**Comment by LuckyHead11** [comment]
@NymdaFromSalad any progress?

**Comment by NymdaFromSalad** [comment]
> @NymdaFromSalad any progress?

On v3? Haven't looked yet, i have some personal matters to attend to. Will look, when done, hopefully won't take me too long

Also, i made a tiny commit to fix version difference in __version__ and version in setup.py

**Comment by qunash** [comment]
Hey everyone. Glad you liked the idea of WebChatGPT extension. @noseon I'd very much appreciate if you didn't put additional load on my backend server. I plan to sunset it anyway, so relying on it is not the best option.

I've made the backend repo public: https://github.com/qunash/ddg-webapp. It's just a thin wrapper around the [duckduckgo-search](https://pypi.org/project/duckduckgo-search/) Python package. You can use it directly instead.

**Comment by NymdaFromSalad** [comment]
> Hey everyone. Glad you liked the idea of WebChatGPT extension. @noseon I'd very much appreciate if you didn't put additional load on my backend server. I plan to sunset it anyway, so relying on it is not the best option.
> 
> I've made the backend repo public: https://github.com/qunash/ddg-webapp. It's just a thin wrapper around the [duckduckgo-search](https://pypi.org/project/duckduckgo-search/) Python package. You can use it directly instead.

Hi, yea, i figured that out myself. Not sure, why you haven't made it public earlier. Will also make V3 use ddg instead soon

(For context, i made WebGPT submodule, noseon - the V3 implementation)

**Comment by acheong08** [comment]
```py
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/acheong/.local/lib/python3.10/site-packages/revChatGPT/WebGPT.py", line 347, in <module>
    main(V1.configure())
  File "/home/acheong/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 55, in wrapper
    out = func(*args, **kwargs)
  File "/home/acheong/.local/lib/python3.10/site-packages/revChatGPT/WebGPT.py", line 325, in main
    for data in chatbot.webAsk(prompt):
  File "/home/acheong/.local/lib/python3.10/site-packages/revChatGPT/WebGPT.py", line 90, in webAsk
    webPrompt, headers = webify(
  File "/home/acheong/.local/lib/python3.10/site-packages/revChatGPT/WebGPT.py", line 48, in webify
    searchResults = ddg(query, numResults, timePeriod, region)
  File "/home/acheong/.local/lib/python3.10/site-packages/duckduckgo_search/ddg.py", line 80, in ddg
    "p": safesearch_base[safesearch.capitalize()],
KeyError: ''
```

**Comment by acheong08** [comment]
> > @NymdaFromSalad any progress?
> 
> On v3? Haven't looked yet, i have some personal matters to attend to. Will look, when done, hopefully won't take me too long

V3 already has web searching implemented

**Comment by acheong08** [comment]
> (For context, i made WebGPT submodule, noseon - the V3 implementation)

I made the V3 implementation, not noseon

**Comment by acheong08** [comment]
@qunash I already stated previously that I would not use third party APIs. I made my own in Go and am using my own server. Don't worry about us abusing your service

**Comment by acheong08** [comment]
> Will also make V3 use ddg instead soon

It already uses DDG
