### ISSUE TITLE
It cannot be called at the same time

### ISSUE THREAD

**Issue by didiplus** [acheong08/ChatGPT#853]
It cannot be called at the same time. If not, the following error will be reported. Is there any way to solve it?

`{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}
Traceback (most recent call last):
  File "E:\python\fastapi\mp\test.py", line 19, in <module>
    for data in chatbot.ask(
  File "D:\Program Files\Python310\lib\site-packages\revChatGPT\V1.py", line 172, in ask
    self.__check_response(response)
  File "D:\Program Files\Python310\lib\site-packages\revChatGPT\V1.py", line 226, in __check_response
    raise error
revChatGPT.V1.Error`

**Comment by acheong08** [comment]
Not my problem. It's a restriction by OpenAI. You can try multi-account cycling
