### ISSUE TITLE
[Bug]: response with some error info

### ISSUE THREAD

**Issue by yhuso** [acheong08/ChatGPT#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

when I ask a question in Chinese, it will respond with some error info.

### Steps to reproduce the problem

1. pip3 install revChatGPT   => exe successfully
2.Save this as $HOME/.config/revChatGPT/config.json 
and  I use access token 
3. python3 -m revChatGPT.V1

### What should have happened?

it seems to be perfect answer if those error info don't show.

### Version where the problem happens

os: mac 
client: terminate
python : python 3.8

### What Python version are you running this with?

Python 3.8.9

### Command Line Arguments

```Shell
python3 -m revChatGPT.V1
```

### Console logs

```Shell
You:
对于四川省坡耕地水土保持有什么建议
Chatbot: 
针对四川省坡耕地水土保持，以下是一些建议：

1. 实施合理的耕地整理：在坡耕地上，要实施合理的耕地整理，以减少耕地坡度，增加耕地平坦面积，降低水土流失。可以通过开展垄行改造、坡改平、旱田改为水田等方式实现。

2. 推广保护2023-02-23 23:50:39,223 - __main__ - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Stack (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 535, in <module>
    main(configure())
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 40, in wrapper
    out = func(*args, **kwargs)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 516, in main
    for data in chatbot.ask(
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
2023-02-23 23:50:39,225 - __main__ - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Stack (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 535, in <module>
    main(configure())
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 40, in wrapper
    out = func(*args, **kwargs)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 516, in main
    for data in chatbot.ask(
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
性耕作措施：耕作措施是防止水土流失的关键。要通过推广保护性耕作措施，例如地膜覆盖、秸秆还田、间作等方式，增强土壤保水保肥能力，减少水土流失。

3. 建立防护林网：在坡耕地周边建立防护林网，以起到抵挡风沙、稳固土壤、促进水源涵养等作用。2023-02-23 23:50:39,233 - __main__ - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Stack (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 535, in <module>
    main(configure())
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 40, in wrapper
    out = func(*args, **kwargs)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 516, in main
    for data in chatbot.ask(
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
2023-02-23 23:50:39,233 - __main__ - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Stack (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 535, in <module>
    main(configure())
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 40, in wrapper
    out = func(*args, **kwargs)
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 516, in main
    for data in chatbot.ask(
  File "/Users/kael/Library/Python/3.8/lib/python/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
同时，在林网内可以实施水土保持措施，如植被复盖、绿化造林等。

4. 加强水土保持技术培训：加强对当地农民的水土保持技术培训，提高农民的水土保持意识和技术水平，促进农业可持续发展。

5. 制定和完善相关法律法规：加强水土保持方面的法律法规制定和完善，加大对水土保持违法行为的惩罚力度，强化水土保持的法制保障。

这些建议可以帮助四川省坡耕地实现水土保持，保护生态环境，同时促进农业可持续发展。

You:
```

**Comment by noseon** [comment]
JSONDecodeError: you are doing debug and releasing this error in case you have to fork and disable it in the code

**Comment by zhimin-z** [comment]
I am having the same error in the response. @yhuso 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/8592144/221016803-adad7035-7fc9-41a7-84ff-8bbf90459d79.png">

**Comment by acheong08** [comment]
ChatGPT was down

**Comment by acheong08** [comment]
As for 
>     log.exception("Error parsing JSON", stack_info=True)

I'm unsure what the issue is. Mind printing the error message?

**Comment by zhimin-z** [comment]
> 

```
2023-02-23 18:59:02,369 - revChatGPT.V1 - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Stack (most recent call last):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 619, in start
    self.io_loop.start()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 539, in execute_request
    self.do_execute(
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2866, in run_cell
    result = self._run_cell(
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3071, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-47-f3c198acb94b>", line 23, in <module>
    for data in chatbot.ask(qa):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
2023-02-23 18:59:02,372 - revChatGPT.V1 - ERROR - ask - Error parsing JSON
Traceback (most recent call last):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 254, in ask
    line = json.loads(line)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Stack (most recent call last):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 619, in start
    self.io_loop.start()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 539, in execute_request
    self.do_execute(
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2866, in run_cell
    result = self._run_cell(
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3071, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-47-f3c198acb94b>", line 23, in <module>
    for data in chatbot.ask(qa):
  File "/Users/jimmy/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 256, in ask
    log.exception("Error parsing JSON", stack_info=True)
```
@acheong08

**Comment by noseon** [comment]
The new version no longer has this error.

**Comment by acheong08** [comment]
fixed

**Comment by yhuso** [comment]
yeah, it's fixed. i have tested it.
thanks.

**Comment by zhimin-z** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/8592144/221222937-2aa58162-f452-4189-a857-a04237644dd7.png"> 
I run with revChatGPT==2.3.7 but it still prints it (though it does not throw exception any more). @acheong08 @yhuso @noseon

**Comment by acheong08** [comment]
Latest is https://github.com/acheong08/ChatGPT/releases/tag/2.3.10
