### ISSUE TITLE
[Bug]: Error: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443)

### ISSUE THREAD

**Issue by chelishchev** [acheong08/ChatGPT#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I use V1 and everything was fine. But suddenly I got error

`Error: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1038343a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))`

### Steps to reproduce the problem

1. Just run a example from a demo with V1 API

### What should have happened?

It should work :)

### Version where the problem happens

2.3.14

### What Python version are you running this with?

3.10.5

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x101930af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x101930af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x101930af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ivan/Projects/test/chatgpt.py", line 275, in <module>
    asyncio.run(run_infinitive())
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ivan/Projects/test/chatgpt.py", line 264, in run_infinitive
    raise e
  File "/Users/ivan/Projects/test/chatgpt.py", line 258, in run_infinitive
    await work_with_posts(chatbot)
  File "/Users/ivan/Projects/test/chatgpt.py", line 208, in work_with_posts
    answer = await ask_chatgpt(chatbot, text_to_ask)
  File "/Users/ivan/Projects/test/chatgpt.py", line 158, in ask_chatgpt
    json_answer = await ask_chatgpt_inner(chatbot, question)
  File "/Users/ivan/Projects/test/chatgpt.py", line 140, in ask_chatgpt_inner
    for part_answer in chatbot.ask(question):
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/V1.py", line 356, in ask
    response = self.session.post(
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x101930af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by acheong08** [comment]
Debug: `dig chatgpt.duti.tech`

**Comment by chelishchev** [comment]
@acheong08 
```
ig chatgpt.duti.tech

; <<>> DiG 9.10.6 <<>> chatgpt.duti.tech
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17935
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 13

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;chatgpt.duti.tech.		IN	A

;; ANSWER SECTION:
chatgpt.duti.tech.	300	IN	A	24.199.71.182

;; AUTHORITY SECTION:
duti.tech.		3600	IN	NS	khloe.ns.cloudflare.com.
duti.tech.		3600	IN	NS	zeus.ns.cloudflare.com.

;; ADDITIONAL SECTION:
zeus.ns.cloudflare.com.	37693	IN	A	108.162.193.249
zeus.ns.cloudflare.com.	37693	IN	A	172.64.33.249
zeus.ns.cloudflare.com.	37693	IN	A	173.245.59.249
khloe.ns.cloudflare.com. 29343	IN	A	108.162.194.139
khloe.ns.cloudflare.com. 29343	IN	A	162.159.38.139
khloe.ns.cloudflare.com. 29343	IN	A	172.64.34.139
zeus.ns.cloudflare.com.	154175	IN	AAAA	2606:4700:58::adf5:3bf9
zeus.ns.cloudflare.com.	154175	IN	AAAA	2803:f800:50::6ca2:c1f9
zeus.ns.cloudflare.com.	154175	IN	AAAA	2a06:98c1:50::ac40:21f9
khloe.ns.cloudflare.com. 154695	IN	AAAA	2a06:98c1:50::ac40:228b
khloe.ns.cloudflare.com. 154695	IN	AAAA	2606:4700:50::a29f:268b
khloe.ns.cloudflare.com. 154695	IN	AAAA	2803:f800:50::6ca2:c28b

;; Query time: 127 msec
;; SERVER: 10.100.102.1#53(10.100.102.1)
;; WHEN: Sun Feb 26 13:41:39 IST 2023
;; MSG SIZE  rcvd: 382
```


So from Chrome, from console I can connect with `chatgpt.duti.tech`.
I tried write simple python script – it works.

```python
import requests
url = 'https://chatgpt.duti.tech/api/conversation'
data = {'message': 'Hello, ChatGPT!'}
headers = {'Content-Type': 'application/json'}
response = requests.post(url, json=data, headers=headers)
if response.status_code == 200:
    print(response.json())
else:
    print(f"Error: {response.status_code}")
```

`{'detail': {'message': 'Unauthorized - Access token is missing'}}`

**Comment by acheong08** [comment]
Try running V1 again and now it should work

**Comment by acheong08** [comment]
Could have been temporary internet issue on your end

**Comment by chelishchev** [comment]
> Try running V1 again and now it should work
Yes, right now it wokrs. Thanks



> Could have been temporary internet issue on your end

It's strange because from Terminal it works, I tested by httpie and verified ssl.

**Comment by acheong08** [comment]
Where does it not work?

**Comment by chelishchev** [comment]
It did not work when I run as 

`python3 /Users/ivan/Projects/test/chatgpt.py`

I think it could be some dns cache.

**Comment by acheong08** [comment]
Networking issues are out of scope for GitHub issues

**Comment by obiscr** [comment]
I always get this response when I make a request in Java. I'm sure the header payloads are all set correctly.

```
{"detail":"Method Not Allowed"} 
```

**Comment by sigridjineth** [comment]
I had an similar issue but would work after changing network. donn know what was the problem imao
