### ISSUE TITLE
[Bug]: ChatGPT Plus account throws `OpenAIAuth.Error` in `__part_five`

### ISSUE THREAD

**Issue by nbsp1221** [acheong08/ChatGPT#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I am using ChatGPT Plus paid account, and I copied and ran the example code from the README.md file. However, I encountered an `OpenAIAuth.Error` in the `__part_five` section, and the OpenAI server returned a 400 Bad Request. What's strange is that I can successfully sign in using my browser.

Here is my source code:
```python
import os
from dotenv import load_dotenv
from revChatGPT.V1 import Chatbot

load_dotenv()

OPENAI_EMAIL = os.getenv('OPENAI_EMAIL')
OPENAI_PASSWORD = os.getenv('OPENAI_PASSWORD')

chatbot = Chatbot(config={
  "email": OPENAI_EMAIL,
  "password": OPENAI_PASSWORD,
})

print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
```

### Steps to reproduce the problem

1. You should need ChatGPT Plus account.
2. Copy the example code from README.md file.
3. Run the code.

### What should have happened?

No authentication errors.

### Version where the problem happens
```
Name: revChatGPT
Version: 2.3.14
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests
Required-by:
```
### What Python version are you running this with?
```
Python 3.10.6
```
### What is your operating system ?
WSL
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
### Command Line Arguments

```Shell
No.
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/src/third-party/chatgpt.py", line 10, in <module>
    chatbot = Chatbot(config={
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 147, in __init__
    self.__check_credentials()
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 163, in __check_credentials
    raise error
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 161, in __check_credentials
    self.__login()
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/revChatGPT/V1.py", line 267, in __login
    auth.begin()
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/home/retn0/repositories/nbsp1221/pns-chatgpt/.venv/lib/python3.10/site-packages/OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error
```

**Comment by marc-dsalab** [comment]
Did you try to add: 

'paid': True

to the config? I'm also working with a ChatGPT+ account, although with access_token, but it works fine.

**Comment by nbsp1221** [comment]
> Did you try to add:
> 
> 'paid': True
> 
> to the config? I'm also working with a ChatGPT+ account, although with access_token, but it works fine.

Thank you for the suggestion. I did try it, but still it's not working.

**Comment by nbsp1221** [comment]
When I tried running it on a different Ubuntu server (not on WSL), it worked fine. This leads me to suspect that the issue might not be with this library itself, but rather with the OpenAI server blocking access based on IP or other factors.

**Comment by xlorne** [comment]
i debug that error. then i found response status was 307. error info was not supperot cuntry. so i setting proxy with config, then was success.
```
from revChatGPT.V1 import Chatbot

chatbot = Chatbot(
    config={
        "email": "xxxx",
        "password": "xxxx",
        "proxy": "http://127.0.0.1:7890",
    }
)
```
