### ISSUE TITLE
[Bug]: I made a mistake

### ISSUE THREAD

**Issue by HITxuefeng** [acheong08/ChatGPT#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xuefeng/projects/douyin/generate_ultimate_content.py", line 19, in <module>
    content_abstract = get_chat_gpt_completion(content_prompt)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuefeng/projects/douyin/request_chatgpt.py", line 12, in get_chat_gpt_completion
    for data in chat_bot.ask(prompt):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/revChatGPT/V1.py", line 363, in ask
    for line in response.iter_lines():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

It works for a while, and then it fails

### Version where the problem happens

Name: revChatGPT
Version: 2.3.14
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests
Required-by: 

### What Python version are you running this with?

3.11

### Command Line Arguments

```Shell
idea run
```

### Console logs

```Shell
On top
```

**Comment by acheong08** [comment]
This issue is stale because it has been open for 2 days with no activity.

**Comment by HITxuefeng** [comment]
maybe  prompt is to longer ，Official api limit 4096 token
