### ISSUE TITLE
[Feature Request]: Make ending the input with `^d` (`<CTRL>+<d>`, `EOF`-character) terminate the executable gracefully.

### ISSUE THREAD

**Issue by dreirund** [acheong08/ChatGPT#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

It would make `revchatgpt` follow the unix-style command line tool convention to exit by pressig `<control>+<d>`, without spitting out error messages.

### Proposed workflow

1. Start `revchatgpt`.
2. Speack with the chatbot.
3. When finished, press `<ctrl>+<d>` to exit gracefully.

### Additional information

Currently, pressinng `<ctrl>+<d>` results in the following output, indicating that it is not gracefully handled:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 977, in <module>
    main(configure())
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 948, in main
    prompt = get_input(session=session)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/revChatGPT/utils.py", line 16, in get_input
    user_input = session.prompt(
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 978, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 885, in run_async
    return await _run_async(f)
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 750, in _run_async
    result = await f
EOFError
```

**Comment by dreirund** [comment]
On Wed, 01 Mar 2023 01:38:57 -0800, Antonio Cheong
***@***.***> wrote about "Re: [acheong08/ChatGPT]
[Feature Request]: Make ending the input with `^d` (`<CTRL>+<d>`,
`EOF`-character) terminate the executable gracefully. (Issue #967)":

> Closed #967 as completed via 43f80df1e83e79a55b86566b1ffc0ba3e733c91f.

Still not working.

Installed version: 2.3.19.r1087.20230301.39d290b (just cloned the git
repo after I received your message.)

When I press `^d` on the prompt after a first message with ChatGPT, I
get

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 981, in <module>
    main(configure())
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 949, in main
    prompt = get_input(session=session)
  File "/usr/lib/python3.10/site-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/revChatGPT/utils.py", line 16, in get_input
    user_input = session.prompt(
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 978, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 885, in run_async
    return await _run_async(f)
  File "/usr/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 750, in _run_async
    result = await f
EOFError
```

Note that `^d` at the very first prompt seems to be ignored

**Comment by acheong08** [comment]
Use ^c which is the standard keyboard interrupt

**Comment by acheong08** [comment]
My terminal doesn't respond to ^d

**Comment by dreirund** [comment]
> Use ^c which is the standard keyboard interrupt

This is "killing the programme". It works, but is not the Unix standard.

> My terminal doesn't respond to ^d

If you open a bash, then press `^d` on an empty prompt, the bash does
not quit?

If you start `cat`, then press `^d` on am empty line, it does not
terminate?
